from _typeshed import ReadableBuffer as ReadableBuffer
from io import BytesIO
from typing import Any

class ContextFramesBytesIO(BytesIO):
    def __init__(self, initial_bytes: ReadableBuffer) -> None: ...
    def seek_in_frame(self, pos: int, *args: Any, **kwargs: Any) -> None: ...
    def push_frame(self, offset: int) -> None: ...
    def pop_frame(self) -> None: ...
