import abc
from . import decoding as decoding, encoding as encoding, exceptions as exceptions, grammar as grammar
from .base import BaseCoder as BaseCoder
from .exceptions import MultipleEntriesFound as MultipleEntriesFound, NoEntriesFound as NoEntriesFound
from .io import ContextFramesBytesIO as ContextFramesBytesIO
from _typeshed import Incomplete
from eth_typing import TypeStr
from typing import Any, Callable, Generic, Iterator, TypeVar
from typing_extensions import Concatenate, ParamSpec, Self

T = TypeVar('T')
P = ParamSpec('P')
Lookup = TypeStr | Callable[[TypeStr], bool]
EncoderCallable = Callable[[Any], bytes]
DecoderCallable = Callable[[ContextFramesBytesIO], Any]
Encoder = EncoderCallable | type[encoding.BaseEncoder]
Decoder = DecoderCallable | type[decoding.BaseDecoder]

class Copyable(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def copy(self): ...
    def __copy__(self): ...
    def __deepcopy__(self, *args): ...

class PredicateMapping(Copyable, Generic[T]):
    _name: Incomplete
    _values: Incomplete
    _labeled_predicates: Incomplete
    def __init__(self, name: str) -> None: ...
    def add(self, predicate: Lookup, value: T, label: str | None = None) -> None: ...
    def find(self, type_str: TypeStr) -> T: ...
    def remove_by_equality(self, predicate: Lookup) -> None: ...
    def _label_for_predicate(self, predicate: Lookup) -> str: ...
    def remove_by_label(self, label: str) -> None: ...
    def remove(self, predicate_or_label: Lookup | str) -> None: ...
    def copy(self) -> Self: ...

class Predicate(Generic[T]):
    __slots__: Incomplete
    _string: str | None
    __hash: Incomplete
    def __init__(self) -> None: ...
    def __call__(self, arg: TypeStr) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[T]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Predicate) -> bool: ...

class Equals(Predicate[str]):
    __slots__: Incomplete
    value: Incomplete
    def __init__(self, value: str) -> None: ...
    def __call__(self, other: TypeStr) -> bool: ...
    _string: Incomplete
    def __str__(self) -> str: ...
    def __iter__(self) -> Iterator[str]: ...

class BaseEquals(Predicate[str | bool | None]):
    __slots__: Incomplete
    base: Incomplete
    with_sub: Incomplete
    def __init__(self, base: TypeStr, *, with_sub: bool | None = None) -> None: ...
    def __call__(self, type_str: TypeStr) -> bool: ...
    _string: Incomplete
    def __str__(self) -> str: ...
    def __iter__(self) -> Iterator[str | bool | None]: ...

def has_arrlist(type_str: TypeStr) -> bool: ...
def is_base_tuple(type_str: TypeStr) -> bool: ...
def _clear_encoder_cache(old_method: Callable[Concatenate['ABIRegistry', P], T]) -> Callable[Concatenate['ABIRegistry', P], T]: ...
def _clear_decoder_cache(old_method: Callable[Concatenate['ABIRegistry', P], T]) -> Callable[Concatenate['ABIRegistry', P], T]: ...

class BaseRegistry:
    @staticmethod
    def _register(mapping: PredicateMapping[T], lookup: Lookup, value: T, label: str | None = None) -> None: ...
    @staticmethod
    def _unregister(mapping: PredicateMapping[Any], lookup_or_label: Lookup) -> None: ...
    @staticmethod
    def _get_registration(mapping: PredicateMapping[T], type_str: TypeStr) -> T: ...

class ABIRegistry(Copyable, BaseRegistry):
    _encoders: Incomplete
    _decoders: Incomplete
    get_encoder: Incomplete
    get_decoder: Incomplete
    get_tuple_encoder: Incomplete
    get_tuple_decoder: Incomplete
    def __init__(self) -> None: ...
    def _get_registration(self, mapping, type_str): ...
    def register_encoder(self, lookup: Lookup, encoder: Encoder, label: str | None = None) -> None: ...
    def unregister_encoder(self, lookup_or_label: Lookup) -> None: ...
    def register_decoder(self, lookup: Lookup, decoder: Decoder, label: str | None = None) -> None: ...
    def unregister_decoder(self, lookup_or_label: Lookup) -> None: ...
    def register(self, lookup: Lookup, encoder: Encoder, decoder: Decoder, label: str | None = None) -> None: ...
    def unregister(self, label: str | None) -> None: ...
    def _get_encoder_uncached(self, type_str: TypeStr) -> Encoder: ...
    def _get_tuple_encoder_uncached(self, *type_strs: TypeStr) -> encoding.TupleEncoder: ...
    def has_encoder(self, type_str: TypeStr) -> bool: ...
    def _get_decoder_uncached(self, type_str: TypeStr, strict: bool = True) -> Decoder: ...
    def _get_tuple_decoder_uncached(self, *type_strs: TypeStr, strict: bool = True) -> decoding.TupleDecoder: ...
    def copy(self) -> Self: ...

registry: Incomplete
registry_packed: Incomplete
