import abc
from . import decoding as decoding, encoding as encoding, exceptions as exceptions, grammar as grammar
from .base import BaseCoder as BaseCoder
from .exceptions import MultipleEntriesFound as MultipleEntriesFound, NoEntriesFound as NoEntriesFound
from .io import ContextFramesBytesIO as ContextFramesBytesIO
from _typeshed import Incomplete
from eth_typing import TypeStr
from typing import Any, Callable, Generic, Iterator, TypeVar
from typing_extensions import ParamSpec, Self

T = TypeVar('T')
P = ParamSpec('P')
Lookup = TypeStr | Callable[[TypeStr], bool]
EncoderCallable = Callable[[Any], bytes]
DecoderCallable = Callable[[ContextFramesBytesIO], Any]
Encoder = EncoderCallable | type[encoding.BaseEncoder]
Decoder = DecoderCallable | type[decoding.BaseDecoder]

class Copyable(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def copy(self): ...
    def __copy__(self): ...
    def __deepcopy__(self, *args): ...

class PredicateMapping(Copyable, Generic[T]):
    def __init__(self, name: str) -> None: ...
    def add(self, predicate: Lookup, value: T, label: str | None = None) -> None: ...
    def find(self, type_str: TypeStr) -> T: ...
    def remove_by_equality(self, predicate: Lookup) -> None: ...
    def remove_by_label(self, label: str) -> None: ...
    def remove(self, predicate_or_label: Lookup | str) -> None: ...
    def copy(self) -> Self: ...

class Predicate(Generic[T]):
    def __init__(self) -> None: ...
    def __call__(self, arg: TypeStr) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Predicate) -> bool: ...

class Equals(Predicate[str]):
    value: Incomplete
    def __init__(self, value: str) -> None: ...
    def __call__(self, other: TypeStr) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...

class BaseEquals(Predicate[str | bool | None]):
    base: Incomplete
    with_sub: Incomplete
    def __init__(self, base: TypeStr, *, with_sub: bool | None = None) -> None: ...
    def __call__(self, type_str: TypeStr) -> bool: ...
    def __iter__(self) -> Iterator[str | bool | None]: ...

def has_arrlist(type_str: TypeStr) -> bool: ...
def is_base_tuple(type_str: TypeStr) -> bool: ...

class BaseRegistry: ...

class ABIRegistry(Copyable, BaseRegistry):
    get_encoder: Incomplete
    get_decoder: Incomplete
    get_tuple_encoder: Incomplete
    get_tuple_decoder: Incomplete
    def __init__(self) -> None: ...
    def register_encoder(self, lookup: Lookup, encoder: Encoder, label: str | None = None) -> None: ...
    def unregister_encoder(self, lookup_or_label: Lookup) -> None: ...
    def register_decoder(self, lookup: Lookup, decoder: Decoder, label: str | None = None) -> None: ...
    def unregister_decoder(self, lookup_or_label: Lookup) -> None: ...
    def register(self, lookup: Lookup, encoder: Encoder, decoder: Decoder, label: str | None = None) -> None: ...
    def unregister(self, label: str | None) -> None: ...
    def has_encoder(self, type_str: TypeStr) -> bool: ...
    def copy(self) -> Self: ...

registry: Incomplete
registry_packed: Incomplete
