# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(decoder.decode(["uint96", "bool"], data), Tuple[Union[bool, int], ...])  # iterable case 10101
assert_type(decoder.decode(["uint96", "bytes"], data), Tuple[Union[bytes, int], ...])  # iterable case 10102
assert_type(decoder.decode(["uint96", "bytes1"], data), Tuple[Union[bytes, int], ...])  # iterable case 10103
assert_type(decoder.decode(["uint96", "bytes10"], data), Tuple[Union[bytes, int], ...])  # iterable case 10104
assert_type(decoder.decode(["uint96", "bytes11"], data), Tuple[Union[bytes, int], ...])  # iterable case 10105
assert_type(decoder.decode(["uint96", "bytes12"], data), Tuple[Union[bytes, int], ...])  # iterable case 10106
assert_type(decoder.decode(["uint96", "bytes13"], data), Tuple[Union[bytes, int], ...])  # iterable case 10107
assert_type(decoder.decode(["uint96", "bytes14"], data), Tuple[Union[bytes, int], ...])  # iterable case 10108
assert_type(decoder.decode(["uint96", "bytes15"], data), Tuple[Union[bytes, int], ...])  # iterable case 10109
assert_type(decoder.decode(["uint96", "bytes16"], data), Tuple[Union[bytes, int], ...])  # iterable case 10110
assert_type(decoder.decode(["uint96", "bytes17"], data), Tuple[Union[bytes, int], ...])  # iterable case 10111
assert_type(decoder.decode(["uint96", "bytes18"], data), Tuple[Union[bytes, int], ...])  # iterable case 10112
assert_type(decoder.decode(["uint96", "bytes19"], data), Tuple[Union[bytes, int], ...])  # iterable case 10113
assert_type(decoder.decode(["uint96", "bytes2"], data), Tuple[Union[bytes, int], ...])  # iterable case 10114
assert_type(decoder.decode(["uint96", "bytes20"], data), Tuple[Union[bytes, int], ...])  # iterable case 10115
assert_type(decoder.decode(["uint96", "bytes21"], data), Tuple[Union[bytes, int], ...])  # iterable case 10116
assert_type(decoder.decode(["uint96", "bytes22"], data), Tuple[Union[bytes, int], ...])  # iterable case 10117
assert_type(decoder.decode(["uint96", "bytes23"], data), Tuple[Union[bytes, int], ...])  # iterable case 10118
assert_type(decoder.decode(["uint96", "bytes24"], data), Tuple[Union[bytes, int], ...])  # iterable case 10119
assert_type(decoder.decode(["uint96", "bytes25"], data), Tuple[Union[bytes, int], ...])  # iterable case 10120
assert_type(decoder.decode(["uint96", "bytes26"], data), Tuple[Union[bytes, int], ...])  # iterable case 10121
assert_type(decoder.decode(["uint96", "bytes27"], data), Tuple[Union[bytes, int], ...])  # iterable case 10122
assert_type(decoder.decode(["uint96", "bytes28"], data), Tuple[Union[bytes, int], ...])  # iterable case 10123
assert_type(decoder.decode(["uint96", "bytes29"], data), Tuple[Union[bytes, int], ...])  # iterable case 10124
assert_type(decoder.decode(["uint96", "bytes3"], data), Tuple[Union[bytes, int], ...])  # iterable case 10125
assert_type(decoder.decode(["uint96", "bytes30"], data), Tuple[Union[bytes, int], ...])  # iterable case 10126
assert_type(decoder.decode(["uint96", "bytes31"], data), Tuple[Union[bytes, int], ...])  # iterable case 10127
assert_type(decoder.decode(["uint96", "bytes32"], data), Tuple[Union[bytes, int], ...])  # iterable case 10128
assert_type(decoder.decode(["uint96", "bytes4"], data), Tuple[Union[bytes, int], ...])  # iterable case 10129
assert_type(decoder.decode(["uint96", "bytes5"], data), Tuple[Union[bytes, int], ...])  # iterable case 10130
assert_type(decoder.decode(["uint96", "bytes6"], data), Tuple[Union[bytes, int], ...])  # iterable case 10131
assert_type(decoder.decode(["uint96", "bytes7"], data), Tuple[Union[bytes, int], ...])  # iterable case 10132
assert_type(decoder.decode(["uint96", "bytes8"], data), Tuple[Union[bytes, int], ...])  # iterable case 10133
assert_type(decoder.decode(["uint96", "bytes9"], data), Tuple[Union[bytes, int], ...])  # iterable case 10134
assert_type(decoder.decode(["uint96", "int104"], data), Tuple[int, ...])  # iterable case 10135
assert_type(decoder.decode(["uint96", "int112"], data), Tuple[int, ...])  # iterable case 10136
assert_type(decoder.decode(["uint96", "int120"], data), Tuple[int, ...])  # iterable case 10137
assert_type(decoder.decode(["uint96", "int128"], data), Tuple[int, ...])  # iterable case 10138
assert_type(decoder.decode(["uint96", "int136"], data), Tuple[int, ...])  # iterable case 10139
assert_type(decoder.decode(["uint96", "int144"], data), Tuple[int, ...])  # iterable case 10140
assert_type(decoder.decode(["uint96", "int152"], data), Tuple[int, ...])  # iterable case 10141
assert_type(decoder.decode(["uint96", "int16"], data), Tuple[int, ...])  # iterable case 10142
assert_type(decoder.decode(["uint96", "int160"], data), Tuple[int, ...])  # iterable case 10143
assert_type(decoder.decode(["uint96", "int168"], data), Tuple[int, ...])  # iterable case 10144
assert_type(decoder.decode(["uint96", "int176"], data), Tuple[int, ...])  # iterable case 10145
assert_type(decoder.decode(["uint96", "int184"], data), Tuple[int, ...])  # iterable case 10146
assert_type(decoder.decode(["uint96", "int192"], data), Tuple[int, ...])  # iterable case 10147
assert_type(decoder.decode(["uint96", "int200"], data), Tuple[int, ...])  # iterable case 10148
assert_type(decoder.decode(["uint96", "int208"], data), Tuple[int, ...])  # iterable case 10149
assert_type(decoder.decode(["uint96", "int216"], data), Tuple[int, ...])  # iterable case 10150
assert_type(decoder.decode(["uint96", "int224"], data), Tuple[int, ...])  # iterable case 10151
assert_type(decoder.decode(["uint96", "int232"], data), Tuple[int, ...])  # iterable case 10152
assert_type(decoder.decode(["uint96", "int24"], data), Tuple[int, ...])  # iterable case 10153
assert_type(decoder.decode(["uint96", "int240"], data), Tuple[int, ...])  # iterable case 10154
assert_type(decoder.decode(["uint96", "int248"], data), Tuple[int, ...])  # iterable case 10155
assert_type(decoder.decode(["uint96", "int256"], data), Tuple[int, ...])  # iterable case 10156
assert_type(decoder.decode(["uint96", "int32"], data), Tuple[int, ...])  # iterable case 10157
assert_type(decoder.decode(["uint96", "int40"], data), Tuple[int, ...])  # iterable case 10158
assert_type(decoder.decode(["uint96", "int48"], data), Tuple[int, ...])  # iterable case 10159
assert_type(decoder.decode(["uint96", "int56"], data), Tuple[int, ...])  # iterable case 10160
assert_type(decoder.decode(["uint96", "int64"], data), Tuple[int, ...])  # iterable case 10161
assert_type(decoder.decode(["uint96", "int72"], data), Tuple[int, ...])  # iterable case 10162
assert_type(decoder.decode(["uint96", "int8"], data), Tuple[int, ...])  # iterable case 10163
assert_type(decoder.decode(["uint96", "int80"], data), Tuple[int, ...])  # iterable case 10164
assert_type(decoder.decode(["uint96", "int88"], data), Tuple[int, ...])  # iterable case 10165
assert_type(decoder.decode(["uint96", "int96"], data), Tuple[int, ...])  # iterable case 10166
assert_type(decoder.decode(["uint96", "string"], data), Tuple[Union[int, str], ...])  # iterable case 10167
assert_type(decoder.decode(["uint96", "uint104"], data), Tuple[int, ...])  # iterable case 10168
assert_type(decoder.decode(["uint96", "uint112"], data), Tuple[int, ...])  # iterable case 10169
assert_type(decoder.decode(["uint96", "uint120"], data), Tuple[int, ...])  # iterable case 10170
assert_type(decoder.decode(["uint96", "uint128"], data), Tuple[int, ...])  # iterable case 10171
assert_type(decoder.decode(["uint96", "uint136"], data), Tuple[int, ...])  # iterable case 10172
assert_type(decoder.decode(["uint96", "uint144"], data), Tuple[int, ...])  # iterable case 10173
assert_type(decoder.decode(["uint96", "uint152"], data), Tuple[int, ...])  # iterable case 10174
assert_type(decoder.decode(["uint96", "uint16"], data), Tuple[int, ...])  # iterable case 10175
assert_type(decoder.decode(["uint96", "uint160"], data), Tuple[int, ...])  # iterable case 10176
assert_type(decoder.decode(["uint96", "uint168"], data), Tuple[int, ...])  # iterable case 10177
assert_type(decoder.decode(["uint96", "uint176"], data), Tuple[int, ...])  # iterable case 10178
assert_type(decoder.decode(["uint96", "uint184"], data), Tuple[int, ...])  # iterable case 10179
assert_type(decoder.decode(["uint96", "uint192"], data), Tuple[int, ...])  # iterable case 10180
assert_type(decoder.decode(["uint96", "uint200"], data), Tuple[int, ...])  # iterable case 10181
assert_type(decoder.decode(["uint96", "uint208"], data), Tuple[int, ...])  # iterable case 10182
assert_type(decoder.decode(["uint96", "uint216"], data), Tuple[int, ...])  # iterable case 10183
assert_type(decoder.decode(["uint96", "uint224"], data), Tuple[int, ...])  # iterable case 10184
assert_type(decoder.decode(["uint96", "uint232"], data), Tuple[int, ...])  # iterable case 10185
assert_type(decoder.decode(["uint96", "uint24"], data), Tuple[int, ...])  # iterable case 10186
assert_type(decoder.decode(["uint96", "uint240"], data), Tuple[int, ...])  # iterable case 10187
assert_type(decoder.decode(["uint96", "uint248"], data), Tuple[int, ...])  # iterable case 10188
assert_type(decoder.decode(["uint96", "uint256"], data), Tuple[int, ...])  # iterable case 10189
assert_type(decoder.decode(["uint96", "uint32"], data), Tuple[int, ...])  # iterable case 10190
assert_type(decoder.decode(["uint96", "uint40"], data), Tuple[int, ...])  # iterable case 10191
assert_type(decoder.decode(["uint96", "uint48"], data), Tuple[int, ...])  # iterable case 10192
assert_type(decoder.decode(["uint96", "uint56"], data), Tuple[int, ...])  # iterable case 10193
assert_type(decoder.decode(["uint96", "uint64"], data), Tuple[int, ...])  # iterable case 10194
assert_type(decoder.decode(["uint96", "uint72"], data), Tuple[int, ...])  # iterable case 10195
assert_type(decoder.decode(["uint96", "uint8"], data), Tuple[int, ...])  # iterable case 10196
assert_type(decoder.decode(["uint96", "uint80"], data), Tuple[int, ...])  # iterable case 10197
assert_type(decoder.decode(["uint96", "uint88"], data), Tuple[int, ...])  # iterable case 10198
assert_type(decoder.decode(["uint96", "uint96"], data), Tuple[int, ...])  # iterable case 10199
assert_type(decoder.decode(["uint96", "someothertype"], data), Tuple[Any, ...])  # iterable case 10200
assert_type(decoder.decode(["someothertype", "address"], data), Tuple[Any, ...])  # iterable case 10201
assert_type(decoder.decode(["someothertype", "bool"], data), Tuple[Any, ...])  # iterable case 10202
assert_type(decoder.decode(["someothertype", "bytes"], data), Tuple[Any, ...])  # iterable case 10203
assert_type(decoder.decode(["someothertype", "bytes1"], data), Tuple[Any, ...])  # iterable case 10204
assert_type(decoder.decode(["someothertype", "bytes10"], data), Tuple[Any, ...])  # iterable case 10205
assert_type(decoder.decode(["someothertype", "bytes11"], data), Tuple[Any, ...])  # iterable case 10206
assert_type(decoder.decode(["someothertype", "bytes12"], data), Tuple[Any, ...])  # iterable case 10207
assert_type(decoder.decode(["someothertype", "bytes13"], data), Tuple[Any, ...])  # iterable case 10208
assert_type(decoder.decode(["someothertype", "bytes14"], data), Tuple[Any, ...])  # iterable case 10209
assert_type(decoder.decode(["someothertype", "bytes15"], data), Tuple[Any, ...])  # iterable case 10210
assert_type(decoder.decode(["someothertype", "bytes16"], data), Tuple[Any, ...])  # iterable case 10211
assert_type(decoder.decode(["someothertype", "bytes17"], data), Tuple[Any, ...])  # iterable case 10212
assert_type(decoder.decode(["someothertype", "bytes18"], data), Tuple[Any, ...])  # iterable case 10213
assert_type(decoder.decode(["someothertype", "bytes19"], data), Tuple[Any, ...])  # iterable case 10214
assert_type(decoder.decode(["someothertype", "bytes2"], data), Tuple[Any, ...])  # iterable case 10215
assert_type(decoder.decode(["someothertype", "bytes20"], data), Tuple[Any, ...])  # iterable case 10216
assert_type(decoder.decode(["someothertype", "bytes21"], data), Tuple[Any, ...])  # iterable case 10217
assert_type(decoder.decode(["someothertype", "bytes22"], data), Tuple[Any, ...])  # iterable case 10218
assert_type(decoder.decode(["someothertype", "bytes23"], data), Tuple[Any, ...])  # iterable case 10219
assert_type(decoder.decode(["someothertype", "bytes24"], data), Tuple[Any, ...])  # iterable case 10220
assert_type(decoder.decode(["someothertype", "bytes25"], data), Tuple[Any, ...])  # iterable case 10221
assert_type(decoder.decode(["someothertype", "bytes26"], data), Tuple[Any, ...])  # iterable case 10222
assert_type(decoder.decode(["someothertype", "bytes27"], data), Tuple[Any, ...])  # iterable case 10223
assert_type(decoder.decode(["someothertype", "bytes28"], data), Tuple[Any, ...])  # iterable case 10224
assert_type(decoder.decode(["someothertype", "bytes29"], data), Tuple[Any, ...])  # iterable case 10225
assert_type(decoder.decode(["someothertype", "bytes3"], data), Tuple[Any, ...])  # iterable case 10226
assert_type(decoder.decode(["someothertype", "bytes30"], data), Tuple[Any, ...])  # iterable case 10227
assert_type(decoder.decode(["someothertype", "bytes31"], data), Tuple[Any, ...])  # iterable case 10228
assert_type(decoder.decode(["someothertype", "bytes32"], data), Tuple[Any, ...])  # iterable case 10229
assert_type(decoder.decode(["someothertype", "bytes4"], data), Tuple[Any, ...])  # iterable case 10230
assert_type(decoder.decode(["someothertype", "bytes5"], data), Tuple[Any, ...])  # iterable case 10231
assert_type(decoder.decode(["someothertype", "bytes6"], data), Tuple[Any, ...])  # iterable case 10232
assert_type(decoder.decode(["someothertype", "bytes7"], data), Tuple[Any, ...])  # iterable case 10233
assert_type(decoder.decode(["someothertype", "bytes8"], data), Tuple[Any, ...])  # iterable case 10234
assert_type(decoder.decode(["someothertype", "bytes9"], data), Tuple[Any, ...])  # iterable case 10235
assert_type(decoder.decode(["someothertype", "int104"], data), Tuple[Any, ...])  # iterable case 10236
assert_type(decoder.decode(["someothertype", "int112"], data), Tuple[Any, ...])  # iterable case 10237
assert_type(decoder.decode(["someothertype", "int120"], data), Tuple[Any, ...])  # iterable case 10238
assert_type(decoder.decode(["someothertype", "int128"], data), Tuple[Any, ...])  # iterable case 10239
assert_type(decoder.decode(["someothertype", "int136"], data), Tuple[Any, ...])  # iterable case 10240
assert_type(decoder.decode(["someothertype", "int144"], data), Tuple[Any, ...])  # iterable case 10241
assert_type(decoder.decode(["someothertype", "int152"], data), Tuple[Any, ...])  # iterable case 10242
assert_type(decoder.decode(["someothertype", "int16"], data), Tuple[Any, ...])  # iterable case 10243
assert_type(decoder.decode(["someothertype", "int160"], data), Tuple[Any, ...])  # iterable case 10244
assert_type(decoder.decode(["someothertype", "int168"], data), Tuple[Any, ...])  # iterable case 10245
assert_type(decoder.decode(["someothertype", "int176"], data), Tuple[Any, ...])  # iterable case 10246
assert_type(decoder.decode(["someothertype", "int184"], data), Tuple[Any, ...])  # iterable case 10247
assert_type(decoder.decode(["someothertype", "int192"], data), Tuple[Any, ...])  # iterable case 10248
assert_type(decoder.decode(["someothertype", "int200"], data), Tuple[Any, ...])  # iterable case 10249
assert_type(decoder.decode(["someothertype", "int208"], data), Tuple[Any, ...])  # iterable case 10250
assert_type(decoder.decode(["someothertype", "int216"], data), Tuple[Any, ...])  # iterable case 10251
assert_type(decoder.decode(["someothertype", "int224"], data), Tuple[Any, ...])  # iterable case 10252
assert_type(decoder.decode(["someothertype", "int232"], data), Tuple[Any, ...])  # iterable case 10253
assert_type(decoder.decode(["someothertype", "int24"], data), Tuple[Any, ...])  # iterable case 10254
assert_type(decoder.decode(["someothertype", "int240"], data), Tuple[Any, ...])  # iterable case 10255
assert_type(decoder.decode(["someothertype", "int248"], data), Tuple[Any, ...])  # iterable case 10256
assert_type(decoder.decode(["someothertype", "int256"], data), Tuple[Any, ...])  # iterable case 10257
assert_type(decoder.decode(["someothertype", "int32"], data), Tuple[Any, ...])  # iterable case 10258
assert_type(decoder.decode(["someothertype", "int40"], data), Tuple[Any, ...])  # iterable case 10259
assert_type(decoder.decode(["someothertype", "int48"], data), Tuple[Any, ...])  # iterable case 10260
assert_type(decoder.decode(["someothertype", "int56"], data), Tuple[Any, ...])  # iterable case 10261
assert_type(decoder.decode(["someothertype", "int64"], data), Tuple[Any, ...])  # iterable case 10262
assert_type(decoder.decode(["someothertype", "int72"], data), Tuple[Any, ...])  # iterable case 10263
assert_type(decoder.decode(["someothertype", "int8"], data), Tuple[Any, ...])  # iterable case 10264
assert_type(decoder.decode(["someothertype", "int80"], data), Tuple[Any, ...])  # iterable case 10265
assert_type(decoder.decode(["someothertype", "int88"], data), Tuple[Any, ...])  # iterable case 10266
assert_type(decoder.decode(["someothertype", "int96"], data), Tuple[Any, ...])  # iterable case 10267
assert_type(decoder.decode(["someothertype", "string"], data), Tuple[Any, ...])  # iterable case 10268
assert_type(decoder.decode(["someothertype", "uint104"], data), Tuple[Any, ...])  # iterable case 10269
assert_type(decoder.decode(["someothertype", "uint112"], data), Tuple[Any, ...])  # iterable case 10270
assert_type(decoder.decode(["someothertype", "uint120"], data), Tuple[Any, ...])  # iterable case 10271
assert_type(decoder.decode(["someothertype", "uint128"], data), Tuple[Any, ...])  # iterable case 10272
assert_type(decoder.decode(["someothertype", "uint136"], data), Tuple[Any, ...])  # iterable case 10273
assert_type(decoder.decode(["someothertype", "uint144"], data), Tuple[Any, ...])  # iterable case 10274
assert_type(decoder.decode(["someothertype", "uint152"], data), Tuple[Any, ...])  # iterable case 10275
assert_type(decoder.decode(["someothertype", "uint16"], data), Tuple[Any, ...])  # iterable case 10276
assert_type(decoder.decode(["someothertype", "uint160"], data), Tuple[Any, ...])  # iterable case 10277
assert_type(decoder.decode(["someothertype", "uint168"], data), Tuple[Any, ...])  # iterable case 10278
assert_type(decoder.decode(["someothertype", "uint176"], data), Tuple[Any, ...])  # iterable case 10279
assert_type(decoder.decode(["someothertype", "uint184"], data), Tuple[Any, ...])  # iterable case 10280
assert_type(decoder.decode(["someothertype", "uint192"], data), Tuple[Any, ...])  # iterable case 10281
assert_type(decoder.decode(["someothertype", "uint200"], data), Tuple[Any, ...])  # iterable case 10282
assert_type(decoder.decode(["someothertype", "uint208"], data), Tuple[Any, ...])  # iterable case 10283
assert_type(decoder.decode(["someothertype", "uint216"], data), Tuple[Any, ...])  # iterable case 10284
assert_type(decoder.decode(["someothertype", "uint224"], data), Tuple[Any, ...])  # iterable case 10285
assert_type(decoder.decode(["someothertype", "uint232"], data), Tuple[Any, ...])  # iterable case 10286
assert_type(decoder.decode(["someothertype", "uint24"], data), Tuple[Any, ...])  # iterable case 10287
assert_type(decoder.decode(["someothertype", "uint240"], data), Tuple[Any, ...])  # iterable case 10288
assert_type(decoder.decode(["someothertype", "uint248"], data), Tuple[Any, ...])  # iterable case 10289
assert_type(decoder.decode(["someothertype", "uint256"], data), Tuple[Any, ...])  # iterable case 10290
assert_type(decoder.decode(["someothertype", "uint32"], data), Tuple[Any, ...])  # iterable case 10291
assert_type(decoder.decode(["someothertype", "uint40"], data), Tuple[Any, ...])  # iterable case 10292
assert_type(decoder.decode(["someothertype", "uint48"], data), Tuple[Any, ...])  # iterable case 10293
assert_type(decoder.decode(["someothertype", "uint56"], data), Tuple[Any, ...])  # iterable case 10294
assert_type(decoder.decode(["someothertype", "uint64"], data), Tuple[Any, ...])  # iterable case 10295
assert_type(decoder.decode(["someothertype", "uint72"], data), Tuple[Any, ...])  # iterable case 10296
assert_type(decoder.decode(["someothertype", "uint8"], data), Tuple[Any, ...])  # iterable case 10297
assert_type(decoder.decode(["someothertype", "uint80"], data), Tuple[Any, ...])  # iterable case 10298
assert_type(decoder.decode(["someothertype", "uint88"], data), Tuple[Any, ...])  # iterable case 10299
assert_type(decoder.decode(["someothertype", "uint96"], data), Tuple[Any, ...])  # iterable case 10300
assert_type(decoder.decode(["someothertype", "someothertype"], data), Tuple[Any, ...])  # iterable case 10301
