# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi import abi
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(abi.decode(['uint96', 'bool'], data, Tuple[Union[bool, int], ...]))  # iterable case 20202
assert_type(decoder.decode(['uint96', 'bool'], data, Tuple[Union[bool, int], ...]))  # iterable case 20203
assert_type(abi.decode(['uint96', 'bytes'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20204
assert_type(decoder.decode(['uint96', 'bytes'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20205
assert_type(abi.decode(['uint96', 'bytes1'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20206
assert_type(decoder.decode(['uint96', 'bytes1'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20207
assert_type(abi.decode(['uint96', 'bytes10'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20208
assert_type(decoder.decode(['uint96', 'bytes10'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20209
assert_type(abi.decode(['uint96', 'bytes11'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20210
assert_type(decoder.decode(['uint96', 'bytes11'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20211
assert_type(abi.decode(['uint96', 'bytes12'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20212
assert_type(decoder.decode(['uint96', 'bytes12'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20213
assert_type(abi.decode(['uint96', 'bytes13'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20214
assert_type(decoder.decode(['uint96', 'bytes13'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20215
assert_type(abi.decode(['uint96', 'bytes14'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20216
assert_type(decoder.decode(['uint96', 'bytes14'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20217
assert_type(abi.decode(['uint96', 'bytes15'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20218
assert_type(decoder.decode(['uint96', 'bytes15'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20219
assert_type(abi.decode(['uint96', 'bytes16'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20220
assert_type(decoder.decode(['uint96', 'bytes16'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20221
assert_type(abi.decode(['uint96', 'bytes17'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20222
assert_type(decoder.decode(['uint96', 'bytes17'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20223
assert_type(abi.decode(['uint96', 'bytes18'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20224
assert_type(decoder.decode(['uint96', 'bytes18'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20225
assert_type(abi.decode(['uint96', 'bytes19'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20226
assert_type(decoder.decode(['uint96', 'bytes19'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20227
assert_type(abi.decode(['uint96', 'bytes2'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20228
assert_type(decoder.decode(['uint96', 'bytes2'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20229
assert_type(abi.decode(['uint96', 'bytes20'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20230
assert_type(decoder.decode(['uint96', 'bytes20'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20231
assert_type(abi.decode(['uint96', 'bytes21'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20232
assert_type(decoder.decode(['uint96', 'bytes21'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20233
assert_type(abi.decode(['uint96', 'bytes22'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20234
assert_type(decoder.decode(['uint96', 'bytes22'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20235
assert_type(abi.decode(['uint96', 'bytes23'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20236
assert_type(decoder.decode(['uint96', 'bytes23'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20237
assert_type(abi.decode(['uint96', 'bytes24'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20238
assert_type(decoder.decode(['uint96', 'bytes24'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20239
assert_type(abi.decode(['uint96', 'bytes25'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20240
assert_type(decoder.decode(['uint96', 'bytes25'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20241
assert_type(abi.decode(['uint96', 'bytes26'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20242
assert_type(decoder.decode(['uint96', 'bytes26'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20243
assert_type(abi.decode(['uint96', 'bytes27'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20244
assert_type(decoder.decode(['uint96', 'bytes27'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20245
assert_type(abi.decode(['uint96', 'bytes28'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20246
assert_type(decoder.decode(['uint96', 'bytes28'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20247
assert_type(abi.decode(['uint96', 'bytes29'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20248
assert_type(decoder.decode(['uint96', 'bytes29'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20249
assert_type(abi.decode(['uint96', 'bytes3'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20250
assert_type(decoder.decode(['uint96', 'bytes3'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20251
assert_type(abi.decode(['uint96', 'bytes30'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20252
assert_type(decoder.decode(['uint96', 'bytes30'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20253
assert_type(abi.decode(['uint96', 'bytes31'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20254
assert_type(decoder.decode(['uint96', 'bytes31'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20255
assert_type(abi.decode(['uint96', 'bytes32'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20256
assert_type(decoder.decode(['uint96', 'bytes32'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20257
assert_type(abi.decode(['uint96', 'bytes4'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20258
assert_type(decoder.decode(['uint96', 'bytes4'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20259
assert_type(abi.decode(['uint96', 'bytes5'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20260
assert_type(decoder.decode(['uint96', 'bytes5'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20261
assert_type(abi.decode(['uint96', 'bytes6'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20262
assert_type(decoder.decode(['uint96', 'bytes6'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20263
assert_type(abi.decode(['uint96', 'bytes7'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20264
assert_type(decoder.decode(['uint96', 'bytes7'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20265
assert_type(abi.decode(['uint96', 'bytes8'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20266
assert_type(decoder.decode(['uint96', 'bytes8'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20267
assert_type(abi.decode(['uint96', 'bytes9'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20268
assert_type(decoder.decode(['uint96', 'bytes9'], data, Tuple[Union[bytes, int], ...]))  # iterable case 20269
assert_type(abi.decode(['uint96', 'int104'], data, Tuple[int, ...]))  # iterable case 20270
assert_type(decoder.decode(['uint96', 'int104'], data, Tuple[int, ...]))  # iterable case 20271
assert_type(abi.decode(['uint96', 'int112'], data, Tuple[int, ...]))  # iterable case 20272
assert_type(decoder.decode(['uint96', 'int112'], data, Tuple[int, ...]))  # iterable case 20273
assert_type(abi.decode(['uint96', 'int120'], data, Tuple[int, ...]))  # iterable case 20274
assert_type(decoder.decode(['uint96', 'int120'], data, Tuple[int, ...]))  # iterable case 20275
assert_type(abi.decode(['uint96', 'int128'], data, Tuple[int, ...]))  # iterable case 20276
assert_type(decoder.decode(['uint96', 'int128'], data, Tuple[int, ...]))  # iterable case 20277
assert_type(abi.decode(['uint96', 'int136'], data, Tuple[int, ...]))  # iterable case 20278
assert_type(decoder.decode(['uint96', 'int136'], data, Tuple[int, ...]))  # iterable case 20279
assert_type(abi.decode(['uint96', 'int144'], data, Tuple[int, ...]))  # iterable case 20280
assert_type(decoder.decode(['uint96', 'int144'], data, Tuple[int, ...]))  # iterable case 20281
assert_type(abi.decode(['uint96', 'int152'], data, Tuple[int, ...]))  # iterable case 20282
assert_type(decoder.decode(['uint96', 'int152'], data, Tuple[int, ...]))  # iterable case 20283
assert_type(abi.decode(['uint96', 'int16'], data, Tuple[int, ...]))  # iterable case 20284
assert_type(decoder.decode(['uint96', 'int16'], data, Tuple[int, ...]))  # iterable case 20285
assert_type(abi.decode(['uint96', 'int160'], data, Tuple[int, ...]))  # iterable case 20286
assert_type(decoder.decode(['uint96', 'int160'], data, Tuple[int, ...]))  # iterable case 20287
assert_type(abi.decode(['uint96', 'int168'], data, Tuple[int, ...]))  # iterable case 20288
assert_type(decoder.decode(['uint96', 'int168'], data, Tuple[int, ...]))  # iterable case 20289
assert_type(abi.decode(['uint96', 'int176'], data, Tuple[int, ...]))  # iterable case 20290
assert_type(decoder.decode(['uint96', 'int176'], data, Tuple[int, ...]))  # iterable case 20291
assert_type(abi.decode(['uint96', 'int184'], data, Tuple[int, ...]))  # iterable case 20292
assert_type(decoder.decode(['uint96', 'int184'], data, Tuple[int, ...]))  # iterable case 20293
assert_type(abi.decode(['uint96', 'int192'], data, Tuple[int, ...]))  # iterable case 20294
assert_type(decoder.decode(['uint96', 'int192'], data, Tuple[int, ...]))  # iterable case 20295
assert_type(abi.decode(['uint96', 'int200'], data, Tuple[int, ...]))  # iterable case 20296
assert_type(decoder.decode(['uint96', 'int200'], data, Tuple[int, ...]))  # iterable case 20297
assert_type(abi.decode(['uint96', 'int208'], data, Tuple[int, ...]))  # iterable case 20298
assert_type(decoder.decode(['uint96', 'int208'], data, Tuple[int, ...]))  # iterable case 20299
assert_type(abi.decode(['uint96', 'int216'], data, Tuple[int, ...]))  # iterable case 20300
assert_type(decoder.decode(['uint96', 'int216'], data, Tuple[int, ...]))  # iterable case 20301
assert_type(abi.decode(['uint96', 'int224'], data, Tuple[int, ...]))  # iterable case 20302
assert_type(decoder.decode(['uint96', 'int224'], data, Tuple[int, ...]))  # iterable case 20303
assert_type(abi.decode(['uint96', 'int232'], data, Tuple[int, ...]))  # iterable case 20304
assert_type(decoder.decode(['uint96', 'int232'], data, Tuple[int, ...]))  # iterable case 20305
assert_type(abi.decode(['uint96', 'int24'], data, Tuple[int, ...]))  # iterable case 20306
assert_type(decoder.decode(['uint96', 'int24'], data, Tuple[int, ...]))  # iterable case 20307
assert_type(abi.decode(['uint96', 'int240'], data, Tuple[int, ...]))  # iterable case 20308
assert_type(decoder.decode(['uint96', 'int240'], data, Tuple[int, ...]))  # iterable case 20309
assert_type(abi.decode(['uint96', 'int248'], data, Tuple[int, ...]))  # iterable case 20310
assert_type(decoder.decode(['uint96', 'int248'], data, Tuple[int, ...]))  # iterable case 20311
assert_type(abi.decode(['uint96', 'int256'], data, Tuple[int, ...]))  # iterable case 20312
assert_type(decoder.decode(['uint96', 'int256'], data, Tuple[int, ...]))  # iterable case 20313
assert_type(abi.decode(['uint96', 'int32'], data, Tuple[int, ...]))  # iterable case 20314
assert_type(decoder.decode(['uint96', 'int32'], data, Tuple[int, ...]))  # iterable case 20315
assert_type(abi.decode(['uint96', 'int40'], data, Tuple[int, ...]))  # iterable case 20316
assert_type(decoder.decode(['uint96', 'int40'], data, Tuple[int, ...]))  # iterable case 20317
assert_type(abi.decode(['uint96', 'int48'], data, Tuple[int, ...]))  # iterable case 20318
assert_type(decoder.decode(['uint96', 'int48'], data, Tuple[int, ...]))  # iterable case 20319
assert_type(abi.decode(['uint96', 'int56'], data, Tuple[int, ...]))  # iterable case 20320
assert_type(decoder.decode(['uint96', 'int56'], data, Tuple[int, ...]))  # iterable case 20321
assert_type(abi.decode(['uint96', 'int64'], data, Tuple[int, ...]))  # iterable case 20322
assert_type(decoder.decode(['uint96', 'int64'], data, Tuple[int, ...]))  # iterable case 20323
assert_type(abi.decode(['uint96', 'int72'], data, Tuple[int, ...]))  # iterable case 20324
assert_type(decoder.decode(['uint96', 'int72'], data, Tuple[int, ...]))  # iterable case 20325
assert_type(abi.decode(['uint96', 'int8'], data, Tuple[int, ...]))  # iterable case 20326
assert_type(decoder.decode(['uint96', 'int8'], data, Tuple[int, ...]))  # iterable case 20327
assert_type(abi.decode(['uint96', 'int80'], data, Tuple[int, ...]))  # iterable case 20328
assert_type(decoder.decode(['uint96', 'int80'], data, Tuple[int, ...]))  # iterable case 20329
assert_type(abi.decode(['uint96', 'int88'], data, Tuple[int, ...]))  # iterable case 20330
assert_type(decoder.decode(['uint96', 'int88'], data, Tuple[int, ...]))  # iterable case 20331
assert_type(abi.decode(['uint96', 'int96'], data, Tuple[int, ...]))  # iterable case 20332
assert_type(decoder.decode(['uint96', 'int96'], data, Tuple[int, ...]))  # iterable case 20333
assert_type(abi.decode(['uint96', 'string'], data, Tuple[Union[int, str], ...]))  # iterable case 20334
assert_type(decoder.decode(['uint96', 'string'], data, Tuple[Union[int, str], ...]))  # iterable case 20335
assert_type(abi.decode(['uint96', 'uint104'], data, Tuple[int, ...]))  # iterable case 20336
assert_type(decoder.decode(['uint96', 'uint104'], data, Tuple[int, ...]))  # iterable case 20337
assert_type(abi.decode(['uint96', 'uint112'], data, Tuple[int, ...]))  # iterable case 20338
assert_type(decoder.decode(['uint96', 'uint112'], data, Tuple[int, ...]))  # iterable case 20339
assert_type(abi.decode(['uint96', 'uint120'], data, Tuple[int, ...]))  # iterable case 20340
assert_type(decoder.decode(['uint96', 'uint120'], data, Tuple[int, ...]))  # iterable case 20341
assert_type(abi.decode(['uint96', 'uint128'], data, Tuple[int, ...]))  # iterable case 20342
assert_type(decoder.decode(['uint96', 'uint128'], data, Tuple[int, ...]))  # iterable case 20343
assert_type(abi.decode(['uint96', 'uint136'], data, Tuple[int, ...]))  # iterable case 20344
assert_type(decoder.decode(['uint96', 'uint136'], data, Tuple[int, ...]))  # iterable case 20345
assert_type(abi.decode(['uint96', 'uint144'], data, Tuple[int, ...]))  # iterable case 20346
assert_type(decoder.decode(['uint96', 'uint144'], data, Tuple[int, ...]))  # iterable case 20347
assert_type(abi.decode(['uint96', 'uint152'], data, Tuple[int, ...]))  # iterable case 20348
assert_type(decoder.decode(['uint96', 'uint152'], data, Tuple[int, ...]))  # iterable case 20349
assert_type(abi.decode(['uint96', 'uint16'], data, Tuple[int, ...]))  # iterable case 20350
assert_type(decoder.decode(['uint96', 'uint16'], data, Tuple[int, ...]))  # iterable case 20351
assert_type(abi.decode(['uint96', 'uint160'], data, Tuple[int, ...]))  # iterable case 20352
assert_type(decoder.decode(['uint96', 'uint160'], data, Tuple[int, ...]))  # iterable case 20353
assert_type(abi.decode(['uint96', 'uint168'], data, Tuple[int, ...]))  # iterable case 20354
assert_type(decoder.decode(['uint96', 'uint168'], data, Tuple[int, ...]))  # iterable case 20355
assert_type(abi.decode(['uint96', 'uint176'], data, Tuple[int, ...]))  # iterable case 20356
assert_type(decoder.decode(['uint96', 'uint176'], data, Tuple[int, ...]))  # iterable case 20357
assert_type(abi.decode(['uint96', 'uint184'], data, Tuple[int, ...]))  # iterable case 20358
assert_type(decoder.decode(['uint96', 'uint184'], data, Tuple[int, ...]))  # iterable case 20359
assert_type(abi.decode(['uint96', 'uint192'], data, Tuple[int, ...]))  # iterable case 20360
assert_type(decoder.decode(['uint96', 'uint192'], data, Tuple[int, ...]))  # iterable case 20361
assert_type(abi.decode(['uint96', 'uint200'], data, Tuple[int, ...]))  # iterable case 20362
assert_type(decoder.decode(['uint96', 'uint200'], data, Tuple[int, ...]))  # iterable case 20363
assert_type(abi.decode(['uint96', 'uint208'], data, Tuple[int, ...]))  # iterable case 20364
assert_type(decoder.decode(['uint96', 'uint208'], data, Tuple[int, ...]))  # iterable case 20365
assert_type(abi.decode(['uint96', 'uint216'], data, Tuple[int, ...]))  # iterable case 20366
assert_type(decoder.decode(['uint96', 'uint216'], data, Tuple[int, ...]))  # iterable case 20367
assert_type(abi.decode(['uint96', 'uint224'], data, Tuple[int, ...]))  # iterable case 20368
assert_type(decoder.decode(['uint96', 'uint224'], data, Tuple[int, ...]))  # iterable case 20369
assert_type(abi.decode(['uint96', 'uint232'], data, Tuple[int, ...]))  # iterable case 20370
assert_type(decoder.decode(['uint96', 'uint232'], data, Tuple[int, ...]))  # iterable case 20371
assert_type(abi.decode(['uint96', 'uint24'], data, Tuple[int, ...]))  # iterable case 20372
assert_type(decoder.decode(['uint96', 'uint24'], data, Tuple[int, ...]))  # iterable case 20373
assert_type(abi.decode(['uint96', 'uint240'], data, Tuple[int, ...]))  # iterable case 20374
assert_type(decoder.decode(['uint96', 'uint240'], data, Tuple[int, ...]))  # iterable case 20375
assert_type(abi.decode(['uint96', 'uint248'], data, Tuple[int, ...]))  # iterable case 20376
assert_type(decoder.decode(['uint96', 'uint248'], data, Tuple[int, ...]))  # iterable case 20377
assert_type(abi.decode(['uint96', 'uint256'], data, Tuple[int, ...]))  # iterable case 20378
assert_type(decoder.decode(['uint96', 'uint256'], data, Tuple[int, ...]))  # iterable case 20379
assert_type(abi.decode(['uint96', 'uint32'], data, Tuple[int, ...]))  # iterable case 20380
assert_type(decoder.decode(['uint96', 'uint32'], data, Tuple[int, ...]))  # iterable case 20381
assert_type(abi.decode(['uint96', 'uint40'], data, Tuple[int, ...]))  # iterable case 20382
assert_type(decoder.decode(['uint96', 'uint40'], data, Tuple[int, ...]))  # iterable case 20383
assert_type(abi.decode(['uint96', 'uint48'], data, Tuple[int, ...]))  # iterable case 20384
assert_type(decoder.decode(['uint96', 'uint48'], data, Tuple[int, ...]))  # iterable case 20385
assert_type(abi.decode(['uint96', 'uint56'], data, Tuple[int, ...]))  # iterable case 20386
assert_type(decoder.decode(['uint96', 'uint56'], data, Tuple[int, ...]))  # iterable case 20387
assert_type(abi.decode(['uint96', 'uint64'], data, Tuple[int, ...]))  # iterable case 20388
assert_type(decoder.decode(['uint96', 'uint64'], data, Tuple[int, ...]))  # iterable case 20389
assert_type(abi.decode(['uint96', 'uint72'], data, Tuple[int, ...]))  # iterable case 20390
assert_type(decoder.decode(['uint96', 'uint72'], data, Tuple[int, ...]))  # iterable case 20391
assert_type(abi.decode(['uint96', 'uint8'], data, Tuple[int, ...]))  # iterable case 20392
assert_type(decoder.decode(['uint96', 'uint8'], data, Tuple[int, ...]))  # iterable case 20393
assert_type(abi.decode(['uint96', 'uint80'], data, Tuple[int, ...]))  # iterable case 20394
assert_type(decoder.decode(['uint96', 'uint80'], data, Tuple[int, ...]))  # iterable case 20395
assert_type(abi.decode(['uint96', 'uint88'], data, Tuple[int, ...]))  # iterable case 20396
assert_type(decoder.decode(['uint96', 'uint88'], data, Tuple[int, ...]))  # iterable case 20397
assert_type(abi.decode(['uint96', 'uint96'], data, Tuple[int, ...]))  # iterable case 20398
assert_type(decoder.decode(['uint96', 'uint96'], data, Tuple[int, ...]))  # iterable case 20399
assert_type(abi.decode(['uint96', 'someothertype'], data, Tuple[Any, ...]))  # iterable case 20400
assert_type(decoder.decode(['uint96', 'someothertype'], data, Tuple[Any, ...]))  # iterable case 20401
assert_type(abi.decode(['someothertype', 'address'], data, Tuple[Any, ...]))  # iterable case 20402
assert_type(decoder.decode(['someothertype', 'address'], data, Tuple[Any, ...]))  # iterable case 20403
assert_type(abi.decode(['someothertype', 'bool'], data, Tuple[Any, ...]))  # iterable case 20404
assert_type(decoder.decode(['someothertype', 'bool'], data, Tuple[Any, ...]))  # iterable case 20405
assert_type(abi.decode(['someothertype', 'bytes'], data, Tuple[Any, ...]))  # iterable case 20406
assert_type(decoder.decode(['someothertype', 'bytes'], data, Tuple[Any, ...]))  # iterable case 20407
assert_type(abi.decode(['someothertype', 'bytes1'], data, Tuple[Any, ...]))  # iterable case 20408
assert_type(decoder.decode(['someothertype', 'bytes1'], data, Tuple[Any, ...]))  # iterable case 20409
assert_type(abi.decode(['someothertype', 'bytes10'], data, Tuple[Any, ...]))  # iterable case 20410
assert_type(decoder.decode(['someothertype', 'bytes10'], data, Tuple[Any, ...]))  # iterable case 20411
assert_type(abi.decode(['someothertype', 'bytes11'], data, Tuple[Any, ...]))  # iterable case 20412
assert_type(decoder.decode(['someothertype', 'bytes11'], data, Tuple[Any, ...]))  # iterable case 20413
assert_type(abi.decode(['someothertype', 'bytes12'], data, Tuple[Any, ...]))  # iterable case 20414
assert_type(decoder.decode(['someothertype', 'bytes12'], data, Tuple[Any, ...]))  # iterable case 20415
assert_type(abi.decode(['someothertype', 'bytes13'], data, Tuple[Any, ...]))  # iterable case 20416
assert_type(decoder.decode(['someothertype', 'bytes13'], data, Tuple[Any, ...]))  # iterable case 20417
assert_type(abi.decode(['someothertype', 'bytes14'], data, Tuple[Any, ...]))  # iterable case 20418
assert_type(decoder.decode(['someothertype', 'bytes14'], data, Tuple[Any, ...]))  # iterable case 20419
assert_type(abi.decode(['someothertype', 'bytes15'], data, Tuple[Any, ...]))  # iterable case 20420
assert_type(decoder.decode(['someothertype', 'bytes15'], data, Tuple[Any, ...]))  # iterable case 20421
assert_type(abi.decode(['someothertype', 'bytes16'], data, Tuple[Any, ...]))  # iterable case 20422
assert_type(decoder.decode(['someothertype', 'bytes16'], data, Tuple[Any, ...]))  # iterable case 20423
assert_type(abi.decode(['someothertype', 'bytes17'], data, Tuple[Any, ...]))  # iterable case 20424
assert_type(decoder.decode(['someothertype', 'bytes17'], data, Tuple[Any, ...]))  # iterable case 20425
assert_type(abi.decode(['someothertype', 'bytes18'], data, Tuple[Any, ...]))  # iterable case 20426
assert_type(decoder.decode(['someothertype', 'bytes18'], data, Tuple[Any, ...]))  # iterable case 20427
assert_type(abi.decode(['someothertype', 'bytes19'], data, Tuple[Any, ...]))  # iterable case 20428
assert_type(decoder.decode(['someothertype', 'bytes19'], data, Tuple[Any, ...]))  # iterable case 20429
assert_type(abi.decode(['someothertype', 'bytes2'], data, Tuple[Any, ...]))  # iterable case 20430
assert_type(decoder.decode(['someothertype', 'bytes2'], data, Tuple[Any, ...]))  # iterable case 20431
assert_type(abi.decode(['someothertype', 'bytes20'], data, Tuple[Any, ...]))  # iterable case 20432
assert_type(decoder.decode(['someothertype', 'bytes20'], data, Tuple[Any, ...]))  # iterable case 20433
assert_type(abi.decode(['someothertype', 'bytes21'], data, Tuple[Any, ...]))  # iterable case 20434
assert_type(decoder.decode(['someothertype', 'bytes21'], data, Tuple[Any, ...]))  # iterable case 20435
assert_type(abi.decode(['someothertype', 'bytes22'], data, Tuple[Any, ...]))  # iterable case 20436
assert_type(decoder.decode(['someothertype', 'bytes22'], data, Tuple[Any, ...]))  # iterable case 20437
assert_type(abi.decode(['someothertype', 'bytes23'], data, Tuple[Any, ...]))  # iterable case 20438
assert_type(decoder.decode(['someothertype', 'bytes23'], data, Tuple[Any, ...]))  # iterable case 20439
assert_type(abi.decode(['someothertype', 'bytes24'], data, Tuple[Any, ...]))  # iterable case 20440
assert_type(decoder.decode(['someothertype', 'bytes24'], data, Tuple[Any, ...]))  # iterable case 20441
assert_type(abi.decode(['someothertype', 'bytes25'], data, Tuple[Any, ...]))  # iterable case 20442
assert_type(decoder.decode(['someothertype', 'bytes25'], data, Tuple[Any, ...]))  # iterable case 20443
assert_type(abi.decode(['someothertype', 'bytes26'], data, Tuple[Any, ...]))  # iterable case 20444
assert_type(decoder.decode(['someothertype', 'bytes26'], data, Tuple[Any, ...]))  # iterable case 20445
assert_type(abi.decode(['someothertype', 'bytes27'], data, Tuple[Any, ...]))  # iterable case 20446
assert_type(decoder.decode(['someothertype', 'bytes27'], data, Tuple[Any, ...]))  # iterable case 20447
assert_type(abi.decode(['someothertype', 'bytes28'], data, Tuple[Any, ...]))  # iterable case 20448
assert_type(decoder.decode(['someothertype', 'bytes28'], data, Tuple[Any, ...]))  # iterable case 20449
assert_type(abi.decode(['someothertype', 'bytes29'], data, Tuple[Any, ...]))  # iterable case 20450
assert_type(decoder.decode(['someothertype', 'bytes29'], data, Tuple[Any, ...]))  # iterable case 20451
assert_type(abi.decode(['someothertype', 'bytes3'], data, Tuple[Any, ...]))  # iterable case 20452
assert_type(decoder.decode(['someothertype', 'bytes3'], data, Tuple[Any, ...]))  # iterable case 20453
assert_type(abi.decode(['someothertype', 'bytes30'], data, Tuple[Any, ...]))  # iterable case 20454
assert_type(decoder.decode(['someothertype', 'bytes30'], data, Tuple[Any, ...]))  # iterable case 20455
assert_type(abi.decode(['someothertype', 'bytes31'], data, Tuple[Any, ...]))  # iterable case 20456
assert_type(decoder.decode(['someothertype', 'bytes31'], data, Tuple[Any, ...]))  # iterable case 20457
assert_type(abi.decode(['someothertype', 'bytes32'], data, Tuple[Any, ...]))  # iterable case 20458
assert_type(decoder.decode(['someothertype', 'bytes32'], data, Tuple[Any, ...]))  # iterable case 20459
assert_type(abi.decode(['someothertype', 'bytes4'], data, Tuple[Any, ...]))  # iterable case 20460
assert_type(decoder.decode(['someothertype', 'bytes4'], data, Tuple[Any, ...]))  # iterable case 20461
assert_type(abi.decode(['someothertype', 'bytes5'], data, Tuple[Any, ...]))  # iterable case 20462
assert_type(decoder.decode(['someothertype', 'bytes5'], data, Tuple[Any, ...]))  # iterable case 20463
assert_type(abi.decode(['someothertype', 'bytes6'], data, Tuple[Any, ...]))  # iterable case 20464
assert_type(decoder.decode(['someothertype', 'bytes6'], data, Tuple[Any, ...]))  # iterable case 20465
assert_type(abi.decode(['someothertype', 'bytes7'], data, Tuple[Any, ...]))  # iterable case 20466
assert_type(decoder.decode(['someothertype', 'bytes7'], data, Tuple[Any, ...]))  # iterable case 20467
assert_type(abi.decode(['someothertype', 'bytes8'], data, Tuple[Any, ...]))  # iterable case 20468
assert_type(decoder.decode(['someothertype', 'bytes8'], data, Tuple[Any, ...]))  # iterable case 20469
assert_type(abi.decode(['someothertype', 'bytes9'], data, Tuple[Any, ...]))  # iterable case 20470
assert_type(decoder.decode(['someothertype', 'bytes9'], data, Tuple[Any, ...]))  # iterable case 20471
assert_type(abi.decode(['someothertype', 'int104'], data, Tuple[Any, ...]))  # iterable case 20472
assert_type(decoder.decode(['someothertype', 'int104'], data, Tuple[Any, ...]))  # iterable case 20473
assert_type(abi.decode(['someothertype', 'int112'], data, Tuple[Any, ...]))  # iterable case 20474
assert_type(decoder.decode(['someothertype', 'int112'], data, Tuple[Any, ...]))  # iterable case 20475
assert_type(abi.decode(['someothertype', 'int120'], data, Tuple[Any, ...]))  # iterable case 20476
assert_type(decoder.decode(['someothertype', 'int120'], data, Tuple[Any, ...]))  # iterable case 20477
assert_type(abi.decode(['someothertype', 'int128'], data, Tuple[Any, ...]))  # iterable case 20478
assert_type(decoder.decode(['someothertype', 'int128'], data, Tuple[Any, ...]))  # iterable case 20479
assert_type(abi.decode(['someothertype', 'int136'], data, Tuple[Any, ...]))  # iterable case 20480
assert_type(decoder.decode(['someothertype', 'int136'], data, Tuple[Any, ...]))  # iterable case 20481
assert_type(abi.decode(['someothertype', 'int144'], data, Tuple[Any, ...]))  # iterable case 20482
assert_type(decoder.decode(['someothertype', 'int144'], data, Tuple[Any, ...]))  # iterable case 20483
assert_type(abi.decode(['someothertype', 'int152'], data, Tuple[Any, ...]))  # iterable case 20484
assert_type(decoder.decode(['someothertype', 'int152'], data, Tuple[Any, ...]))  # iterable case 20485
assert_type(abi.decode(['someothertype', 'int16'], data, Tuple[Any, ...]))  # iterable case 20486
assert_type(decoder.decode(['someothertype', 'int16'], data, Tuple[Any, ...]))  # iterable case 20487
assert_type(abi.decode(['someothertype', 'int160'], data, Tuple[Any, ...]))  # iterable case 20488
assert_type(decoder.decode(['someothertype', 'int160'], data, Tuple[Any, ...]))  # iterable case 20489
assert_type(abi.decode(['someothertype', 'int168'], data, Tuple[Any, ...]))  # iterable case 20490
assert_type(decoder.decode(['someothertype', 'int168'], data, Tuple[Any, ...]))  # iterable case 20491
assert_type(abi.decode(['someothertype', 'int176'], data, Tuple[Any, ...]))  # iterable case 20492
assert_type(decoder.decode(['someothertype', 'int176'], data, Tuple[Any, ...]))  # iterable case 20493
assert_type(abi.decode(['someothertype', 'int184'], data, Tuple[Any, ...]))  # iterable case 20494
assert_type(decoder.decode(['someothertype', 'int184'], data, Tuple[Any, ...]))  # iterable case 20495
assert_type(abi.decode(['someothertype', 'int192'], data, Tuple[Any, ...]))  # iterable case 20496
assert_type(decoder.decode(['someothertype', 'int192'], data, Tuple[Any, ...]))  # iterable case 20497
assert_type(abi.decode(['someothertype', 'int200'], data, Tuple[Any, ...]))  # iterable case 20498
assert_type(decoder.decode(['someothertype', 'int200'], data, Tuple[Any, ...]))  # iterable case 20499
assert_type(abi.decode(['someothertype', 'int208'], data, Tuple[Any, ...]))  # iterable case 20500
assert_type(decoder.decode(['someothertype', 'int208'], data, Tuple[Any, ...]))  # iterable case 20501
assert_type(abi.decode(['someothertype', 'int216'], data, Tuple[Any, ...]))  # iterable case 20502
assert_type(decoder.decode(['someothertype', 'int216'], data, Tuple[Any, ...]))  # iterable case 20503
assert_type(abi.decode(['someothertype', 'int224'], data, Tuple[Any, ...]))  # iterable case 20504
assert_type(decoder.decode(['someothertype', 'int224'], data, Tuple[Any, ...]))  # iterable case 20505
assert_type(abi.decode(['someothertype', 'int232'], data, Tuple[Any, ...]))  # iterable case 20506
assert_type(decoder.decode(['someothertype', 'int232'], data, Tuple[Any, ...]))  # iterable case 20507
assert_type(abi.decode(['someothertype', 'int24'], data, Tuple[Any, ...]))  # iterable case 20508
assert_type(decoder.decode(['someothertype', 'int24'], data, Tuple[Any, ...]))  # iterable case 20509
assert_type(abi.decode(['someothertype', 'int240'], data, Tuple[Any, ...]))  # iterable case 20510
assert_type(decoder.decode(['someothertype', 'int240'], data, Tuple[Any, ...]))  # iterable case 20511
assert_type(abi.decode(['someothertype', 'int248'], data, Tuple[Any, ...]))  # iterable case 20512
assert_type(decoder.decode(['someothertype', 'int248'], data, Tuple[Any, ...]))  # iterable case 20513
assert_type(abi.decode(['someothertype', 'int256'], data, Tuple[Any, ...]))  # iterable case 20514
assert_type(decoder.decode(['someothertype', 'int256'], data, Tuple[Any, ...]))  # iterable case 20515
assert_type(abi.decode(['someothertype', 'int32'], data, Tuple[Any, ...]))  # iterable case 20516
assert_type(decoder.decode(['someothertype', 'int32'], data, Tuple[Any, ...]))  # iterable case 20517
assert_type(abi.decode(['someothertype', 'int40'], data, Tuple[Any, ...]))  # iterable case 20518
assert_type(decoder.decode(['someothertype', 'int40'], data, Tuple[Any, ...]))  # iterable case 20519
assert_type(abi.decode(['someothertype', 'int48'], data, Tuple[Any, ...]))  # iterable case 20520
assert_type(decoder.decode(['someothertype', 'int48'], data, Tuple[Any, ...]))  # iterable case 20521
assert_type(abi.decode(['someothertype', 'int56'], data, Tuple[Any, ...]))  # iterable case 20522
assert_type(decoder.decode(['someothertype', 'int56'], data, Tuple[Any, ...]))  # iterable case 20523
assert_type(abi.decode(['someothertype', 'int64'], data, Tuple[Any, ...]))  # iterable case 20524
assert_type(decoder.decode(['someothertype', 'int64'], data, Tuple[Any, ...]))  # iterable case 20525
assert_type(abi.decode(['someothertype', 'int72'], data, Tuple[Any, ...]))  # iterable case 20526
assert_type(decoder.decode(['someothertype', 'int72'], data, Tuple[Any, ...]))  # iterable case 20527
assert_type(abi.decode(['someothertype', 'int8'], data, Tuple[Any, ...]))  # iterable case 20528
assert_type(decoder.decode(['someothertype', 'int8'], data, Tuple[Any, ...]))  # iterable case 20529
assert_type(abi.decode(['someothertype', 'int80'], data, Tuple[Any, ...]))  # iterable case 20530
assert_type(decoder.decode(['someothertype', 'int80'], data, Tuple[Any, ...]))  # iterable case 20531
assert_type(abi.decode(['someothertype', 'int88'], data, Tuple[Any, ...]))  # iterable case 20532
assert_type(decoder.decode(['someothertype', 'int88'], data, Tuple[Any, ...]))  # iterable case 20533
assert_type(abi.decode(['someothertype', 'int96'], data, Tuple[Any, ...]))  # iterable case 20534
assert_type(decoder.decode(['someothertype', 'int96'], data, Tuple[Any, ...]))  # iterable case 20535
assert_type(abi.decode(['someothertype', 'string'], data, Tuple[Any, ...]))  # iterable case 20536
assert_type(decoder.decode(['someothertype', 'string'], data, Tuple[Any, ...]))  # iterable case 20537
assert_type(abi.decode(['someothertype', 'uint104'], data, Tuple[Any, ...]))  # iterable case 20538
assert_type(decoder.decode(['someothertype', 'uint104'], data, Tuple[Any, ...]))  # iterable case 20539
assert_type(abi.decode(['someothertype', 'uint112'], data, Tuple[Any, ...]))  # iterable case 20540
assert_type(decoder.decode(['someothertype', 'uint112'], data, Tuple[Any, ...]))  # iterable case 20541
assert_type(abi.decode(['someothertype', 'uint120'], data, Tuple[Any, ...]))  # iterable case 20542
assert_type(decoder.decode(['someothertype', 'uint120'], data, Tuple[Any, ...]))  # iterable case 20543
assert_type(abi.decode(['someothertype', 'uint128'], data, Tuple[Any, ...]))  # iterable case 20544
assert_type(decoder.decode(['someothertype', 'uint128'], data, Tuple[Any, ...]))  # iterable case 20545
assert_type(abi.decode(['someothertype', 'uint136'], data, Tuple[Any, ...]))  # iterable case 20546
assert_type(decoder.decode(['someothertype', 'uint136'], data, Tuple[Any, ...]))  # iterable case 20547
assert_type(abi.decode(['someothertype', 'uint144'], data, Tuple[Any, ...]))  # iterable case 20548
assert_type(decoder.decode(['someothertype', 'uint144'], data, Tuple[Any, ...]))  # iterable case 20549
assert_type(abi.decode(['someothertype', 'uint152'], data, Tuple[Any, ...]))  # iterable case 20550
assert_type(decoder.decode(['someothertype', 'uint152'], data, Tuple[Any, ...]))  # iterable case 20551
assert_type(abi.decode(['someothertype', 'uint16'], data, Tuple[Any, ...]))  # iterable case 20552
assert_type(decoder.decode(['someothertype', 'uint16'], data, Tuple[Any, ...]))  # iterable case 20553
assert_type(abi.decode(['someothertype', 'uint160'], data, Tuple[Any, ...]))  # iterable case 20554
assert_type(decoder.decode(['someothertype', 'uint160'], data, Tuple[Any, ...]))  # iterable case 20555
assert_type(abi.decode(['someothertype', 'uint168'], data, Tuple[Any, ...]))  # iterable case 20556
assert_type(decoder.decode(['someothertype', 'uint168'], data, Tuple[Any, ...]))  # iterable case 20557
assert_type(abi.decode(['someothertype', 'uint176'], data, Tuple[Any, ...]))  # iterable case 20558
assert_type(decoder.decode(['someothertype', 'uint176'], data, Tuple[Any, ...]))  # iterable case 20559
assert_type(abi.decode(['someothertype', 'uint184'], data, Tuple[Any, ...]))  # iterable case 20560
assert_type(decoder.decode(['someothertype', 'uint184'], data, Tuple[Any, ...]))  # iterable case 20561
assert_type(abi.decode(['someothertype', 'uint192'], data, Tuple[Any, ...]))  # iterable case 20562
assert_type(decoder.decode(['someothertype', 'uint192'], data, Tuple[Any, ...]))  # iterable case 20563
assert_type(abi.decode(['someothertype', 'uint200'], data, Tuple[Any, ...]))  # iterable case 20564
assert_type(decoder.decode(['someothertype', 'uint200'], data, Tuple[Any, ...]))  # iterable case 20565
assert_type(abi.decode(['someothertype', 'uint208'], data, Tuple[Any, ...]))  # iterable case 20566
assert_type(decoder.decode(['someothertype', 'uint208'], data, Tuple[Any, ...]))  # iterable case 20567
assert_type(abi.decode(['someothertype', 'uint216'], data, Tuple[Any, ...]))  # iterable case 20568
assert_type(decoder.decode(['someothertype', 'uint216'], data, Tuple[Any, ...]))  # iterable case 20569
assert_type(abi.decode(['someothertype', 'uint224'], data, Tuple[Any, ...]))  # iterable case 20570
assert_type(decoder.decode(['someothertype', 'uint224'], data, Tuple[Any, ...]))  # iterable case 20571
assert_type(abi.decode(['someothertype', 'uint232'], data, Tuple[Any, ...]))  # iterable case 20572
assert_type(decoder.decode(['someothertype', 'uint232'], data, Tuple[Any, ...]))  # iterable case 20573
assert_type(abi.decode(['someothertype', 'uint24'], data, Tuple[Any, ...]))  # iterable case 20574
assert_type(decoder.decode(['someothertype', 'uint24'], data, Tuple[Any, ...]))  # iterable case 20575
assert_type(abi.decode(['someothertype', 'uint240'], data, Tuple[Any, ...]))  # iterable case 20576
assert_type(decoder.decode(['someothertype', 'uint240'], data, Tuple[Any, ...]))  # iterable case 20577
assert_type(abi.decode(['someothertype', 'uint248'], data, Tuple[Any, ...]))  # iterable case 20578
assert_type(decoder.decode(['someothertype', 'uint248'], data, Tuple[Any, ...]))  # iterable case 20579
assert_type(abi.decode(['someothertype', 'uint256'], data, Tuple[Any, ...]))  # iterable case 20580
assert_type(decoder.decode(['someothertype', 'uint256'], data, Tuple[Any, ...]))  # iterable case 20581
assert_type(abi.decode(['someothertype', 'uint32'], data, Tuple[Any, ...]))  # iterable case 20582
assert_type(decoder.decode(['someothertype', 'uint32'], data, Tuple[Any, ...]))  # iterable case 20583
assert_type(abi.decode(['someothertype', 'uint40'], data, Tuple[Any, ...]))  # iterable case 20584
assert_type(decoder.decode(['someothertype', 'uint40'], data, Tuple[Any, ...]))  # iterable case 20585
assert_type(abi.decode(['someothertype', 'uint48'], data, Tuple[Any, ...]))  # iterable case 20586
assert_type(decoder.decode(['someothertype', 'uint48'], data, Tuple[Any, ...]))  # iterable case 20587
assert_type(abi.decode(['someothertype', 'uint56'], data, Tuple[Any, ...]))  # iterable case 20588
assert_type(decoder.decode(['someothertype', 'uint56'], data, Tuple[Any, ...]))  # iterable case 20589
assert_type(abi.decode(['someothertype', 'uint64'], data, Tuple[Any, ...]))  # iterable case 20590
assert_type(decoder.decode(['someothertype', 'uint64'], data, Tuple[Any, ...]))  # iterable case 20591
assert_type(abi.decode(['someothertype', 'uint72'], data, Tuple[Any, ...]))  # iterable case 20592
assert_type(decoder.decode(['someothertype', 'uint72'], data, Tuple[Any, ...]))  # iterable case 20593
assert_type(abi.decode(['someothertype', 'uint8'], data, Tuple[Any, ...]))  # iterable case 20594
assert_type(decoder.decode(['someothertype', 'uint8'], data, Tuple[Any, ...]))  # iterable case 20595
assert_type(abi.decode(['someothertype', 'uint80'], data, Tuple[Any, ...]))  # iterable case 20596
assert_type(decoder.decode(['someothertype', 'uint80'], data, Tuple[Any, ...]))  # iterable case 20597
assert_type(abi.decode(['someothertype', 'uint88'], data, Tuple[Any, ...]))  # iterable case 20598
assert_type(decoder.decode(['someothertype', 'uint88'], data, Tuple[Any, ...]))  # iterable case 20599
assert_type(abi.decode(['someothertype', 'uint96'], data, Tuple[Any, ...]))  # iterable case 20600
assert_type(decoder.decode(['someothertype', 'uint96'], data, Tuple[Any, ...]))  # iterable case 20601
assert_type(abi.decode(['someothertype', 'someothertype'], data, Tuple[Any, ...]))  # iterable case 20602
assert_type(decoder.decode(['someothertype', 'someothertype'], data, Tuple[Any, ...]))  # iterable case 20603
