# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy extras
# To run: pip install mypy && mypy tests/typecheck

# alias some things so we can minimize test data size in source control
from typing import Any as A
from typing import Tuple as T
from typing import Union as U
from typing_extensions import assert_type as ck
from eth_typing import HexAddress as HA
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

# more aliases to save a bunch more chars
bo = bool
by = bytes
i = int
s = str

TA = T[A, ...]

decoder = ABIDecoder(ABIRegistry())

# the callable we are checking
f = decoder.decode

# input data
D = b"\x00" * 32
ck(f(['uint56', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10104
ck(f(['uint56', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10105
ck(f(['uint56', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10106
ck(f(['uint56', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10107
ck(f(['uint56', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10108
ck(f(['uint56', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10109
ck(f(['uint56', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10110
ck(f(['uint56', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10111
ck(f(['uint56', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10112
ck(f(['uint56', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10113
ck(f(['uint56', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10114
ck(f(['uint56', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10115
ck(f(['uint56', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10116
ck(f(['uint56', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10117
ck(f(['uint56', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10118
ck(f(['uint56', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10119
ck(f(['uint56', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10120
ck(f(['uint56', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10121
ck(f(['uint56', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10122
ck(f(['uint56', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10123
ck(f(['uint56', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10124
ck(f(['uint56', 'int104'], D), T[i, ...])  # iterable case 10125
ck(f(['uint56', 'int112'], D), T[i, ...])  # iterable case 10126
ck(f(['uint56', 'int120'], D), T[i, ...])  # iterable case 10127
ck(f(['uint56', 'int128'], D), T[i, ...])  # iterable case 10128
ck(f(['uint56', 'int136'], D), T[i, ...])  # iterable case 10129
ck(f(['uint56', 'int144'], D), T[i, ...])  # iterable case 10130
ck(f(['uint56', 'int152'], D), T[i, ...])  # iterable case 10131
ck(f(['uint56', 'int16'], D), T[i, ...])  # iterable case 10132
ck(f(['uint56', 'int160'], D), T[i, ...])  # iterable case 10133
ck(f(['uint56', 'int168'], D), T[i, ...])  # iterable case 10134
ck(f(['uint56', 'int176'], D), T[i, ...])  # iterable case 10135
ck(f(['uint56', 'int184'], D), T[i, ...])  # iterable case 10136
ck(f(['uint56', 'int192'], D), T[i, ...])  # iterable case 10137
ck(f(['uint56', 'int200'], D), T[i, ...])  # iterable case 10138
ck(f(['uint56', 'int208'], D), T[i, ...])  # iterable case 10139
ck(f(['uint56', 'int216'], D), T[i, ...])  # iterable case 10140
ck(f(['uint56', 'int224'], D), T[i, ...])  # iterable case 10141
ck(f(['uint56', 'int232'], D), T[i, ...])  # iterable case 10142
ck(f(['uint56', 'int24'], D), T[i, ...])  # iterable case 10143
ck(f(['uint56', 'int240'], D), T[i, ...])  # iterable case 10144
ck(f(['uint56', 'int248'], D), T[i, ...])  # iterable case 10145
ck(f(['uint56', 'int256'], D), T[i, ...])  # iterable case 10146
ck(f(['uint56', 'int32'], D), T[i, ...])  # iterable case 10147
ck(f(['uint56', 'int40'], D), T[i, ...])  # iterable case 10148
ck(f(['uint56', 'int48'], D), T[i, ...])  # iterable case 10149
ck(f(['uint56', 'int56'], D), T[i, ...])  # iterable case 10150
ck(f(['uint56', 'int64'], D), T[i, ...])  # iterable case 10151
ck(f(['uint56', 'int72'], D), T[i, ...])  # iterable case 10152
ck(f(['uint56', 'int8'], D), T[i, ...])  # iterable case 10153
ck(f(['uint56', 'int80'], D), T[i, ...])  # iterable case 10154
ck(f(['uint56', 'int88'], D), T[i, ...])  # iterable case 10155
ck(f(['uint56', 'int96'], D), T[i, ...])  # iterable case 10156
ck(f(['uint56', 'string'], D), T[U[i, s], ...])  # iterable case 10157
ck(f(['uint56', 'string[]'], D), TA)  # iterable case 10158
ck(f(['uint56', 'uint104'], D), T[i, ...])  # iterable case 10159
ck(f(['uint56', 'uint112'], D), T[i, ...])  # iterable case 10160
ck(f(['uint56', 'uint120'], D), T[i, ...])  # iterable case 10161
ck(f(['uint56', 'uint128'], D), T[i, ...])  # iterable case 10162
ck(f(['uint56', 'uint136'], D), T[i, ...])  # iterable case 10163
ck(f(['uint56', 'uint144'], D), T[i, ...])  # iterable case 10164
ck(f(['uint56', 'uint152'], D), T[i, ...])  # iterable case 10165
ck(f(['uint56', 'uint16'], D), T[i, ...])  # iterable case 10166
ck(f(['uint56', 'uint160'], D), T[i, ...])  # iterable case 10167
ck(f(['uint56', 'uint168'], D), T[i, ...])  # iterable case 10168
ck(f(['uint56', 'uint176'], D), T[i, ...])  # iterable case 10169
ck(f(['uint56', 'uint184'], D), T[i, ...])  # iterable case 10170
ck(f(['uint56', 'uint192'], D), T[i, ...])  # iterable case 10171
ck(f(['uint56', 'uint200'], D), T[i, ...])  # iterable case 10172
ck(f(['uint56', 'uint208'], D), T[i, ...])  # iterable case 10173
ck(f(['uint56', 'uint216'], D), T[i, ...])  # iterable case 10174
ck(f(['uint56', 'uint224'], D), T[i, ...])  # iterable case 10175
ck(f(['uint56', 'uint232'], D), T[i, ...])  # iterable case 10176
ck(f(['uint56', 'uint24'], D), T[i, ...])  # iterable case 10177
ck(f(['uint56', 'uint240'], D), T[i, ...])  # iterable case 10178
ck(f(['uint56', 'uint248'], D), T[i, ...])  # iterable case 10179
ck(f(['uint56', 'uint256'], D), T[i, ...])  # iterable case 10180
ck(f(['uint56', 'uint32'], D), T[i, ...])  # iterable case 10181
ck(f(['uint56', 'uint40'], D), T[i, ...])  # iterable case 10182
ck(f(['uint56', 'uint48'], D), T[i, ...])  # iterable case 10183
ck(f(['uint56', 'uint56'], D), T[i, ...])  # iterable case 10184
ck(f(['uint56', 'uint64'], D), T[i, ...])  # iterable case 10185
ck(f(['uint56', 'uint72'], D), T[i, ...])  # iterable case 10186
ck(f(['uint56', 'uint8'], D), T[i, ...])  # iterable case 10187
ck(f(['uint56', 'uint80'], D), T[i, ...])  # iterable case 10188
ck(f(['uint56', 'uint88'], D), T[i, ...])  # iterable case 10189
ck(f(['uint56', 'uint96'], D), T[i, ...])  # iterable case 10190
ck(f(['uint56', '?'], D), TA)  # iterable case 10191
ck(f(['uint64', 'address'], D), T[U[HA, i], ...])  # iterable case 10192
ck(f(['uint64', 'address[]'], D), TA)  # iterable case 10193
ck(f(['uint64', 'bool'], D), T[U[bo, i], ...])  # iterable case 10194
ck(f(['uint64', 'bool[]'], D), TA)  # iterable case 10195
ck(f(['uint64', 'bytes'], D), T[U[by, i], ...])  # iterable case 10196
ck(f(['uint64', 'bytes1'], D), T[U[by, i], ...])  # iterable case 10197
ck(f(['uint64', 'bytes10'], D), T[U[by, i], ...])  # iterable case 10198
ck(f(['uint64', 'bytes11'], D), T[U[by, i], ...])  # iterable case 10199
ck(f(['uint64', 'bytes12'], D), T[U[by, i], ...])  # iterable case 10200
ck(f(['uint64', 'bytes13'], D), T[U[by, i], ...])  # iterable case 10201
ck(f(['uint64', 'bytes14'], D), T[U[by, i], ...])  # iterable case 10202
ck(f(['uint64', 'bytes15'], D), T[U[by, i], ...])  # iterable case 10203
ck(f(['uint64', 'bytes16'], D), T[U[by, i], ...])  # iterable case 10204
ck(f(['uint64', 'bytes17'], D), T[U[by, i], ...])  # iterable case 10205
ck(f(['uint64', 'bytes18'], D), T[U[by, i], ...])  # iterable case 10206
ck(f(['uint64', 'bytes19'], D), T[U[by, i], ...])  # iterable case 10207
ck(f(['uint64', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10208
ck(f(['uint64', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10209
ck(f(['uint64', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10210
ck(f(['uint64', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10211
ck(f(['uint64', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10212
ck(f(['uint64', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10213
ck(f(['uint64', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10214
ck(f(['uint64', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10215
ck(f(['uint64', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10216
ck(f(['uint64', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10217
ck(f(['uint64', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10218
ck(f(['uint64', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10219
ck(f(['uint64', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10220
ck(f(['uint64', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10221
ck(f(['uint64', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10222
ck(f(['uint64', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10223
ck(f(['uint64', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10224
ck(f(['uint64', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10225
ck(f(['uint64', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10226
ck(f(['uint64', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10227
ck(f(['uint64', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10228
ck(f(['uint64', 'int104'], D), T[i, ...])  # iterable case 10229
ck(f(['uint64', 'int112'], D), T[i, ...])  # iterable case 10230
ck(f(['uint64', 'int120'], D), T[i, ...])  # iterable case 10231
ck(f(['uint64', 'int128'], D), T[i, ...])  # iterable case 10232
ck(f(['uint64', 'int136'], D), T[i, ...])  # iterable case 10233
ck(f(['uint64', 'int144'], D), T[i, ...])  # iterable case 10234
ck(f(['uint64', 'int152'], D), T[i, ...])  # iterable case 10235
ck(f(['uint64', 'int16'], D), T[i, ...])  # iterable case 10236
ck(f(['uint64', 'int160'], D), T[i, ...])  # iterable case 10237
ck(f(['uint64', 'int168'], D), T[i, ...])  # iterable case 10238
ck(f(['uint64', 'int176'], D), T[i, ...])  # iterable case 10239
ck(f(['uint64', 'int184'], D), T[i, ...])  # iterable case 10240
ck(f(['uint64', 'int192'], D), T[i, ...])  # iterable case 10241
ck(f(['uint64', 'int200'], D), T[i, ...])  # iterable case 10242
ck(f(['uint64', 'int208'], D), T[i, ...])  # iterable case 10243
ck(f(['uint64', 'int216'], D), T[i, ...])  # iterable case 10244
ck(f(['uint64', 'int224'], D), T[i, ...])  # iterable case 10245
ck(f(['uint64', 'int232'], D), T[i, ...])  # iterable case 10246
ck(f(['uint64', 'int24'], D), T[i, ...])  # iterable case 10247
ck(f(['uint64', 'int240'], D), T[i, ...])  # iterable case 10248
ck(f(['uint64', 'int248'], D), T[i, ...])  # iterable case 10249
ck(f(['uint64', 'int256'], D), T[i, ...])  # iterable case 10250
ck(f(['uint64', 'int32'], D), T[i, ...])  # iterable case 10251
ck(f(['uint64', 'int40'], D), T[i, ...])  # iterable case 10252
ck(f(['uint64', 'int48'], D), T[i, ...])  # iterable case 10253
ck(f(['uint64', 'int56'], D), T[i, ...])  # iterable case 10254
ck(f(['uint64', 'int64'], D), T[i, ...])  # iterable case 10255
ck(f(['uint64', 'int72'], D), T[i, ...])  # iterable case 10256
ck(f(['uint64', 'int8'], D), T[i, ...])  # iterable case 10257
ck(f(['uint64', 'int80'], D), T[i, ...])  # iterable case 10258
ck(f(['uint64', 'int88'], D), T[i, ...])  # iterable case 10259
ck(f(['uint64', 'int96'], D), T[i, ...])  # iterable case 10260
ck(f(['uint64', 'string'], D), T[U[i, s], ...])  # iterable case 10261
ck(f(['uint64', 'string[]'], D), TA)  # iterable case 10262
ck(f(['uint64', 'uint104'], D), T[i, ...])  # iterable case 10263
ck(f(['uint64', 'uint112'], D), T[i, ...])  # iterable case 10264
ck(f(['uint64', 'uint120'], D), T[i, ...])  # iterable case 10265
ck(f(['uint64', 'uint128'], D), T[i, ...])  # iterable case 10266
ck(f(['uint64', 'uint136'], D), T[i, ...])  # iterable case 10267
ck(f(['uint64', 'uint144'], D), T[i, ...])  # iterable case 10268
ck(f(['uint64', 'uint152'], D), T[i, ...])  # iterable case 10269
ck(f(['uint64', 'uint16'], D), T[i, ...])  # iterable case 10270
ck(f(['uint64', 'uint160'], D), T[i, ...])  # iterable case 10271
ck(f(['uint64', 'uint168'], D), T[i, ...])  # iterable case 10272
ck(f(['uint64', 'uint176'], D), T[i, ...])  # iterable case 10273
ck(f(['uint64', 'uint184'], D), T[i, ...])  # iterable case 10274
ck(f(['uint64', 'uint192'], D), T[i, ...])  # iterable case 10275
ck(f(['uint64', 'uint200'], D), T[i, ...])  # iterable case 10276
ck(f(['uint64', 'uint208'], D), T[i, ...])  # iterable case 10277
ck(f(['uint64', 'uint216'], D), T[i, ...])  # iterable case 10278
ck(f(['uint64', 'uint224'], D), T[i, ...])  # iterable case 10279
ck(f(['uint64', 'uint232'], D), T[i, ...])  # iterable case 10280
ck(f(['uint64', 'uint24'], D), T[i, ...])  # iterable case 10281
ck(f(['uint64', 'uint240'], D), T[i, ...])  # iterable case 10282
ck(f(['uint64', 'uint248'], D), T[i, ...])  # iterable case 10283
ck(f(['uint64', 'uint256'], D), T[i, ...])  # iterable case 10284
ck(f(['uint64', 'uint32'], D), T[i, ...])  # iterable case 10285
ck(f(['uint64', 'uint40'], D), T[i, ...])  # iterable case 10286
ck(f(['uint64', 'uint48'], D), T[i, ...])  # iterable case 10287
ck(f(['uint64', 'uint56'], D), T[i, ...])  # iterable case 10288
ck(f(['uint64', 'uint64'], D), T[i, ...])  # iterable case 10289
ck(f(['uint64', 'uint72'], D), T[i, ...])  # iterable case 10290
ck(f(['uint64', 'uint8'], D), T[i, ...])  # iterable case 10291
ck(f(['uint64', 'uint80'], D), T[i, ...])  # iterable case 10292
ck(f(['uint64', 'uint88'], D), T[i, ...])  # iterable case 10293
ck(f(['uint64', 'uint96'], D), T[i, ...])  # iterable case 10294
ck(f(['uint64', '?'], D), TA)  # iterable case 10295
ck(f(['uint72', 'address'], D), T[U[HA, i], ...])  # iterable case 10296
ck(f(['uint72', 'address[]'], D), TA)  # iterable case 10297
ck(f(['uint72', 'bool'], D), T[U[bo, i], ...])  # iterable case 10298
ck(f(['uint72', 'bool[]'], D), TA)  # iterable case 10299
ck(f(['uint72', 'bytes'], D), T[U[by, i], ...])  # iterable case 10300
ck(f(['uint72', 'bytes1'], D), T[U[by, i], ...])  # iterable case 10301
ck(f(['uint72', 'bytes10'], D), T[U[by, i], ...])  # iterable case 10302
ck(f(['uint72', 'bytes11'], D), T[U[by, i], ...])  # iterable case 10303
ck(f(['uint72', 'bytes12'], D), T[U[by, i], ...])  # iterable case 10304
ck(f(['uint72', 'bytes13'], D), T[U[by, i], ...])  # iterable case 10305
ck(f(['uint72', 'bytes14'], D), T[U[by, i], ...])  # iterable case 10306
ck(f(['uint72', 'bytes15'], D), T[U[by, i], ...])  # iterable case 10307
ck(f(['uint72', 'bytes16'], D), T[U[by, i], ...])  # iterable case 10308
ck(f(['uint72', 'bytes17'], D), T[U[by, i], ...])  # iterable case 10309
ck(f(['uint72', 'bytes18'], D), T[U[by, i], ...])  # iterable case 10310
ck(f(['uint72', 'bytes19'], D), T[U[by, i], ...])  # iterable case 10311
ck(f(['uint72', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10312
ck(f(['uint72', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10313
ck(f(['uint72', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10314
ck(f(['uint72', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10315
ck(f(['uint72', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10316
ck(f(['uint72', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10317
ck(f(['uint72', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10318
ck(f(['uint72', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10319
ck(f(['uint72', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10320
ck(f(['uint72', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10321
ck(f(['uint72', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10322
ck(f(['uint72', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10323
ck(f(['uint72', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10324
ck(f(['uint72', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10325
ck(f(['uint72', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10326
ck(f(['uint72', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10327
ck(f(['uint72', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10328
ck(f(['uint72', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10329
ck(f(['uint72', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10330
ck(f(['uint72', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10331
ck(f(['uint72', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10332
ck(f(['uint72', 'int104'], D), T[i, ...])  # iterable case 10333
ck(f(['uint72', 'int112'], D), T[i, ...])  # iterable case 10334
ck(f(['uint72', 'int120'], D), T[i, ...])  # iterable case 10335
ck(f(['uint72', 'int128'], D), T[i, ...])  # iterable case 10336
ck(f(['uint72', 'int136'], D), T[i, ...])  # iterable case 10337
ck(f(['uint72', 'int144'], D), T[i, ...])  # iterable case 10338
ck(f(['uint72', 'int152'], D), T[i, ...])  # iterable case 10339
ck(f(['uint72', 'int16'], D), T[i, ...])  # iterable case 10340
ck(f(['uint72', 'int160'], D), T[i, ...])  # iterable case 10341
ck(f(['uint72', 'int168'], D), T[i, ...])  # iterable case 10342
ck(f(['uint72', 'int176'], D), T[i, ...])  # iterable case 10343
ck(f(['uint72', 'int184'], D), T[i, ...])  # iterable case 10344
ck(f(['uint72', 'int192'], D), T[i, ...])  # iterable case 10345
ck(f(['uint72', 'int200'], D), T[i, ...])  # iterable case 10346
ck(f(['uint72', 'int208'], D), T[i, ...])  # iterable case 10347
ck(f(['uint72', 'int216'], D), T[i, ...])  # iterable case 10348
ck(f(['uint72', 'int224'], D), T[i, ...])  # iterable case 10349
ck(f(['uint72', 'int232'], D), T[i, ...])  # iterable case 10350
ck(f(['uint72', 'int24'], D), T[i, ...])  # iterable case 10351
ck(f(['uint72', 'int240'], D), T[i, ...])  # iterable case 10352
ck(f(['uint72', 'int248'], D), T[i, ...])  # iterable case 10353
ck(f(['uint72', 'int256'], D), T[i, ...])  # iterable case 10354
ck(f(['uint72', 'int32'], D), T[i, ...])  # iterable case 10355
ck(f(['uint72', 'int40'], D), T[i, ...])  # iterable case 10356
ck(f(['uint72', 'int48'], D), T[i, ...])  # iterable case 10357
ck(f(['uint72', 'int56'], D), T[i, ...])  # iterable case 10358
ck(f(['uint72', 'int64'], D), T[i, ...])  # iterable case 10359
ck(f(['uint72', 'int72'], D), T[i, ...])  # iterable case 10360
ck(f(['uint72', 'int8'], D), T[i, ...])  # iterable case 10361
ck(f(['uint72', 'int80'], D), T[i, ...])  # iterable case 10362
ck(f(['uint72', 'int88'], D), T[i, ...])  # iterable case 10363
ck(f(['uint72', 'int96'], D), T[i, ...])  # iterable case 10364
ck(f(['uint72', 'string'], D), T[U[i, s], ...])  # iterable case 10365
ck(f(['uint72', 'string[]'], D), TA)  # iterable case 10366
ck(f(['uint72', 'uint104'], D), T[i, ...])  # iterable case 10367
ck(f(['uint72', 'uint112'], D), T[i, ...])  # iterable case 10368
ck(f(['uint72', 'uint120'], D), T[i, ...])  # iterable case 10369
ck(f(['uint72', 'uint128'], D), T[i, ...])  # iterable case 10370
ck(f(['uint72', 'uint136'], D), T[i, ...])  # iterable case 10371
ck(f(['uint72', 'uint144'], D), T[i, ...])  # iterable case 10372
ck(f(['uint72', 'uint152'], D), T[i, ...])  # iterable case 10373
ck(f(['uint72', 'uint16'], D), T[i, ...])  # iterable case 10374
ck(f(['uint72', 'uint160'], D), T[i, ...])  # iterable case 10375
ck(f(['uint72', 'uint168'], D), T[i, ...])  # iterable case 10376
ck(f(['uint72', 'uint176'], D), T[i, ...])  # iterable case 10377
ck(f(['uint72', 'uint184'], D), T[i, ...])  # iterable case 10378
ck(f(['uint72', 'uint192'], D), T[i, ...])  # iterable case 10379
ck(f(['uint72', 'uint200'], D), T[i, ...])  # iterable case 10380
ck(f(['uint72', 'uint208'], D), T[i, ...])  # iterable case 10381
ck(f(['uint72', 'uint216'], D), T[i, ...])  # iterable case 10382
ck(f(['uint72', 'uint224'], D), T[i, ...])  # iterable case 10383
ck(f(['uint72', 'uint232'], D), T[i, ...])  # iterable case 10384
ck(f(['uint72', 'uint24'], D), T[i, ...])  # iterable case 10385
ck(f(['uint72', 'uint240'], D), T[i, ...])  # iterable case 10386
ck(f(['uint72', 'uint248'], D), T[i, ...])  # iterable case 10387
ck(f(['uint72', 'uint256'], D), T[i, ...])  # iterable case 10388
ck(f(['uint72', 'uint32'], D), T[i, ...])  # iterable case 10389
ck(f(['uint72', 'uint40'], D), T[i, ...])  # iterable case 10390
ck(f(['uint72', 'uint48'], D), T[i, ...])  # iterable case 10391
ck(f(['uint72', 'uint56'], D), T[i, ...])  # iterable case 10392
ck(f(['uint72', 'uint64'], D), T[i, ...])  # iterable case 10393
ck(f(['uint72', 'uint72'], D), T[i, ...])  # iterable case 10394
ck(f(['uint72', 'uint8'], D), T[i, ...])  # iterable case 10395
ck(f(['uint72', 'uint80'], D), T[i, ...])  # iterable case 10396
ck(f(['uint72', 'uint88'], D), T[i, ...])  # iterable case 10397
ck(f(['uint72', 'uint96'], D), T[i, ...])  # iterable case 10398
ck(f(['uint72', '?'], D), TA)  # iterable case 10399
ck(f(['uint8', 'address'], D), T[U[HA, i], ...])  # iterable case 10400
ck(f(['uint8', 'address[]'], D), TA)  # iterable case 10401
ck(f(['uint8', 'bool'], D), T[U[bo, i], ...])  # iterable case 10402
ck(f(['uint8', 'bool[]'], D), TA)  # iterable case 10403
ck(f(['uint8', 'bytes'], D), T[U[by, i], ...])  # iterable case 10404
ck(f(['uint8', 'bytes1'], D), T[U[by, i], ...])  # iterable case 10405
ck(f(['uint8', 'bytes10'], D), T[U[by, i], ...])  # iterable case 10406
ck(f(['uint8', 'bytes11'], D), T[U[by, i], ...])  # iterable case 10407
ck(f(['uint8', 'bytes12'], D), T[U[by, i], ...])  # iterable case 10408
ck(f(['uint8', 'bytes13'], D), T[U[by, i], ...])  # iterable case 10409
ck(f(['uint8', 'bytes14'], D), T[U[by, i], ...])  # iterable case 10410
ck(f(['uint8', 'bytes15'], D), T[U[by, i], ...])  # iterable case 10411
ck(f(['uint8', 'bytes16'], D), T[U[by, i], ...])  # iterable case 10412
ck(f(['uint8', 'bytes17'], D), T[U[by, i], ...])  # iterable case 10413
ck(f(['uint8', 'bytes18'], D), T[U[by, i], ...])  # iterable case 10414
ck(f(['uint8', 'bytes19'], D), T[U[by, i], ...])  # iterable case 10415
ck(f(['uint8', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10416
ck(f(['uint8', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10417
ck(f(['uint8', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10418
ck(f(['uint8', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10419
ck(f(['uint8', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10420
ck(f(['uint8', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10421
ck(f(['uint8', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10422
ck(f(['uint8', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10423
ck(f(['uint8', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10424
ck(f(['uint8', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10425
ck(f(['uint8', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10426
ck(f(['uint8', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10427
ck(f(['uint8', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10428
ck(f(['uint8', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10429
ck(f(['uint8', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10430
ck(f(['uint8', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10431
ck(f(['uint8', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10432
ck(f(['uint8', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10433
ck(f(['uint8', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10434
ck(f(['uint8', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10435
ck(f(['uint8', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10436
ck(f(['uint8', 'int104'], D), T[i, ...])  # iterable case 10437
ck(f(['uint8', 'int112'], D), T[i, ...])  # iterable case 10438
ck(f(['uint8', 'int120'], D), T[i, ...])  # iterable case 10439
ck(f(['uint8', 'int128'], D), T[i, ...])  # iterable case 10440
ck(f(['uint8', 'int136'], D), T[i, ...])  # iterable case 10441
ck(f(['uint8', 'int144'], D), T[i, ...])  # iterable case 10442
ck(f(['uint8', 'int152'], D), T[i, ...])  # iterable case 10443
ck(f(['uint8', 'int16'], D), T[i, ...])  # iterable case 10444
ck(f(['uint8', 'int160'], D), T[i, ...])  # iterable case 10445
ck(f(['uint8', 'int168'], D), T[i, ...])  # iterable case 10446
ck(f(['uint8', 'int176'], D), T[i, ...])  # iterable case 10447
ck(f(['uint8', 'int184'], D), T[i, ...])  # iterable case 10448
ck(f(['uint8', 'int192'], D), T[i, ...])  # iterable case 10449
ck(f(['uint8', 'int200'], D), T[i, ...])  # iterable case 10450
ck(f(['uint8', 'int208'], D), T[i, ...])  # iterable case 10451
ck(f(['uint8', 'int216'], D), T[i, ...])  # iterable case 10452
ck(f(['uint8', 'int224'], D), T[i, ...])  # iterable case 10453
ck(f(['uint8', 'int232'], D), T[i, ...])  # iterable case 10454
ck(f(['uint8', 'int24'], D), T[i, ...])  # iterable case 10455
ck(f(['uint8', 'int240'], D), T[i, ...])  # iterable case 10456
ck(f(['uint8', 'int248'], D), T[i, ...])  # iterable case 10457
ck(f(['uint8', 'int256'], D), T[i, ...])  # iterable case 10458
ck(f(['uint8', 'int32'], D), T[i, ...])  # iterable case 10459
ck(f(['uint8', 'int40'], D), T[i, ...])  # iterable case 10460
ck(f(['uint8', 'int48'], D), T[i, ...])  # iterable case 10461
ck(f(['uint8', 'int56'], D), T[i, ...])  # iterable case 10462
ck(f(['uint8', 'int64'], D), T[i, ...])  # iterable case 10463
ck(f(['uint8', 'int72'], D), T[i, ...])  # iterable case 10464
ck(f(['uint8', 'int8'], D), T[i, ...])  # iterable case 10465
ck(f(['uint8', 'int80'], D), T[i, ...])  # iterable case 10466
ck(f(['uint8', 'int88'], D), T[i, ...])  # iterable case 10467
ck(f(['uint8', 'int96'], D), T[i, ...])  # iterable case 10468
ck(f(['uint8', 'string'], D), T[U[i, s], ...])  # iterable case 10469
ck(f(['uint8', 'string[]'], D), TA)  # iterable case 10470
ck(f(['uint8', 'uint104'], D), T[i, ...])  # iterable case 10471
ck(f(['uint8', 'uint112'], D), T[i, ...])  # iterable case 10472
ck(f(['uint8', 'uint120'], D), T[i, ...])  # iterable case 10473
ck(f(['uint8', 'uint128'], D), T[i, ...])  # iterable case 10474
ck(f(['uint8', 'uint136'], D), T[i, ...])  # iterable case 10475
ck(f(['uint8', 'uint144'], D), T[i, ...])  # iterable case 10476
ck(f(['uint8', 'uint152'], D), T[i, ...])  # iterable case 10477
ck(f(['uint8', 'uint16'], D), T[i, ...])  # iterable case 10478
ck(f(['uint8', 'uint160'], D), T[i, ...])  # iterable case 10479
ck(f(['uint8', 'uint168'], D), T[i, ...])  # iterable case 10480
ck(f(['uint8', 'uint176'], D), T[i, ...])  # iterable case 10481
ck(f(['uint8', 'uint184'], D), T[i, ...])  # iterable case 10482
ck(f(['uint8', 'uint192'], D), T[i, ...])  # iterable case 10483
ck(f(['uint8', 'uint200'], D), T[i, ...])  # iterable case 10484
ck(f(['uint8', 'uint208'], D), T[i, ...])  # iterable case 10485
ck(f(['uint8', 'uint216'], D), T[i, ...])  # iterable case 10486
ck(f(['uint8', 'uint224'], D), T[i, ...])  # iterable case 10487
ck(f(['uint8', 'uint232'], D), T[i, ...])  # iterable case 10488
ck(f(['uint8', 'uint24'], D), T[i, ...])  # iterable case 10489
ck(f(['uint8', 'uint240'], D), T[i, ...])  # iterable case 10490
ck(f(['uint8', 'uint248'], D), T[i, ...])  # iterable case 10491
ck(f(['uint8', 'uint256'], D), T[i, ...])  # iterable case 10492
ck(f(['uint8', 'uint32'], D), T[i, ...])  # iterable case 10493
ck(f(['uint8', 'uint40'], D), T[i, ...])  # iterable case 10494
ck(f(['uint8', 'uint48'], D), T[i, ...])  # iterable case 10495
ck(f(['uint8', 'uint56'], D), T[i, ...])  # iterable case 10496
ck(f(['uint8', 'uint64'], D), T[i, ...])  # iterable case 10497
ck(f(['uint8', 'uint72'], D), T[i, ...])  # iterable case 10498
ck(f(['uint8', 'uint8'], D), T[i, ...])  # iterable case 10499
ck(f(['uint8', 'uint80'], D), T[i, ...])  # iterable case 10500
ck(f(['uint8', 'uint88'], D), T[i, ...])  # iterable case 10501
ck(f(['uint8', 'uint96'], D), T[i, ...])  # iterable case 10502
ck(f(['uint8', '?'], D), TA)  # iterable case 10503
ck(f(['uint80', 'address'], D), T[U[HA, i], ...])  # iterable case 10504
ck(f(['uint80', 'address[]'], D), TA)  # iterable case 10505
ck(f(['uint80', 'bool'], D), T[U[bo, i], ...])  # iterable case 10506
ck(f(['uint80', 'bool[]'], D), TA)  # iterable case 10507
ck(f(['uint80', 'bytes'], D), T[U[by, i], ...])  # iterable case 10508
ck(f(['uint80', 'bytes1'], D), T[U[by, i], ...])  # iterable case 10509
ck(f(['uint80', 'bytes10'], D), T[U[by, i], ...])  # iterable case 10510
ck(f(['uint80', 'bytes11'], D), T[U[by, i], ...])  # iterable case 10511
ck(f(['uint80', 'bytes12'], D), T[U[by, i], ...])  # iterable case 10512
ck(f(['uint80', 'bytes13'], D), T[U[by, i], ...])  # iterable case 10513
ck(f(['uint80', 'bytes14'], D), T[U[by, i], ...])  # iterable case 10514
ck(f(['uint80', 'bytes15'], D), T[U[by, i], ...])  # iterable case 10515
ck(f(['uint80', 'bytes16'], D), T[U[by, i], ...])  # iterable case 10516
ck(f(['uint80', 'bytes17'], D), T[U[by, i], ...])  # iterable case 10517
ck(f(['uint80', 'bytes18'], D), T[U[by, i], ...])  # iterable case 10518
ck(f(['uint80', 'bytes19'], D), T[U[by, i], ...])  # iterable case 10519
ck(f(['uint80', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10520
ck(f(['uint80', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10521
ck(f(['uint80', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10522
ck(f(['uint80', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10523
ck(f(['uint80', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10524
ck(f(['uint80', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10525
ck(f(['uint80', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10526
ck(f(['uint80', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10527
ck(f(['uint80', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10528
ck(f(['uint80', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10529
ck(f(['uint80', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10530
ck(f(['uint80', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10531
ck(f(['uint80', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10532
ck(f(['uint80', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10533
ck(f(['uint80', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10534
ck(f(['uint80', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10535
ck(f(['uint80', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10536
ck(f(['uint80', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10537
ck(f(['uint80', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10538
ck(f(['uint80', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10539
ck(f(['uint80', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10540
ck(f(['uint80', 'int104'], D), T[i, ...])  # iterable case 10541
ck(f(['uint80', 'int112'], D), T[i, ...])  # iterable case 10542
ck(f(['uint80', 'int120'], D), T[i, ...])  # iterable case 10543
ck(f(['uint80', 'int128'], D), T[i, ...])  # iterable case 10544
ck(f(['uint80', 'int136'], D), T[i, ...])  # iterable case 10545
ck(f(['uint80', 'int144'], D), T[i, ...])  # iterable case 10546
ck(f(['uint80', 'int152'], D), T[i, ...])  # iterable case 10547
ck(f(['uint80', 'int16'], D), T[i, ...])  # iterable case 10548
ck(f(['uint80', 'int160'], D), T[i, ...])  # iterable case 10549
ck(f(['uint80', 'int168'], D), T[i, ...])  # iterable case 10550
ck(f(['uint80', 'int176'], D), T[i, ...])  # iterable case 10551
ck(f(['uint80', 'int184'], D), T[i, ...])  # iterable case 10552
ck(f(['uint80', 'int192'], D), T[i, ...])  # iterable case 10553
ck(f(['uint80', 'int200'], D), T[i, ...])  # iterable case 10554
ck(f(['uint80', 'int208'], D), T[i, ...])  # iterable case 10555
ck(f(['uint80', 'int216'], D), T[i, ...])  # iterable case 10556
ck(f(['uint80', 'int224'], D), T[i, ...])  # iterable case 10557
ck(f(['uint80', 'int232'], D), T[i, ...])  # iterable case 10558
ck(f(['uint80', 'int24'], D), T[i, ...])  # iterable case 10559
ck(f(['uint80', 'int240'], D), T[i, ...])  # iterable case 10560
ck(f(['uint80', 'int248'], D), T[i, ...])  # iterable case 10561
ck(f(['uint80', 'int256'], D), T[i, ...])  # iterable case 10562
ck(f(['uint80', 'int32'], D), T[i, ...])  # iterable case 10563
ck(f(['uint80', 'int40'], D), T[i, ...])  # iterable case 10564
ck(f(['uint80', 'int48'], D), T[i, ...])  # iterable case 10565
ck(f(['uint80', 'int56'], D), T[i, ...])  # iterable case 10566
ck(f(['uint80', 'int64'], D), T[i, ...])  # iterable case 10567
ck(f(['uint80', 'int72'], D), T[i, ...])  # iterable case 10568
ck(f(['uint80', 'int8'], D), T[i, ...])  # iterable case 10569
ck(f(['uint80', 'int80'], D), T[i, ...])  # iterable case 10570
ck(f(['uint80', 'int88'], D), T[i, ...])  # iterable case 10571
ck(f(['uint80', 'int96'], D), T[i, ...])  # iterable case 10572
ck(f(['uint80', 'string'], D), T[U[i, s], ...])  # iterable case 10573
ck(f(['uint80', 'string[]'], D), TA)  # iterable case 10574
ck(f(['uint80', 'uint104'], D), T[i, ...])  # iterable case 10575
ck(f(['uint80', 'uint112'], D), T[i, ...])  # iterable case 10576
ck(f(['uint80', 'uint120'], D), T[i, ...])  # iterable case 10577
ck(f(['uint80', 'uint128'], D), T[i, ...])  # iterable case 10578
ck(f(['uint80', 'uint136'], D), T[i, ...])  # iterable case 10579
ck(f(['uint80', 'uint144'], D), T[i, ...])  # iterable case 10580
ck(f(['uint80', 'uint152'], D), T[i, ...])  # iterable case 10581
ck(f(['uint80', 'uint16'], D), T[i, ...])  # iterable case 10582
ck(f(['uint80', 'uint160'], D), T[i, ...])  # iterable case 10583
ck(f(['uint80', 'uint168'], D), T[i, ...])  # iterable case 10584
ck(f(['uint80', 'uint176'], D), T[i, ...])  # iterable case 10585
ck(f(['uint80', 'uint184'], D), T[i, ...])  # iterable case 10586
ck(f(['uint80', 'uint192'], D), T[i, ...])  # iterable case 10587
ck(f(['uint80', 'uint200'], D), T[i, ...])  # iterable case 10588
ck(f(['uint80', 'uint208'], D), T[i, ...])  # iterable case 10589
ck(f(['uint80', 'uint216'], D), T[i, ...])  # iterable case 10590
ck(f(['uint80', 'uint224'], D), T[i, ...])  # iterable case 10591
ck(f(['uint80', 'uint232'], D), T[i, ...])  # iterable case 10592
ck(f(['uint80', 'uint24'], D), T[i, ...])  # iterable case 10593
ck(f(['uint80', 'uint240'], D), T[i, ...])  # iterable case 10594
ck(f(['uint80', 'uint248'], D), T[i, ...])  # iterable case 10595
ck(f(['uint80', 'uint256'], D), T[i, ...])  # iterable case 10596
ck(f(['uint80', 'uint32'], D), T[i, ...])  # iterable case 10597
ck(f(['uint80', 'uint40'], D), T[i, ...])  # iterable case 10598
ck(f(['uint80', 'uint48'], D), T[i, ...])  # iterable case 10599
ck(f(['uint80', 'uint56'], D), T[i, ...])  # iterable case 10600
ck(f(['uint80', 'uint64'], D), T[i, ...])  # iterable case 10601
ck(f(['uint80', 'uint72'], D), T[i, ...])  # iterable case 10602
ck(f(['uint80', 'uint8'], D), T[i, ...])  # iterable case 10603
ck(f(['uint80', 'uint80'], D), T[i, ...])  # iterable case 10604
ck(f(['uint80', 'uint88'], D), T[i, ...])  # iterable case 10605
ck(f(['uint80', 'uint96'], D), T[i, ...])  # iterable case 10606
ck(f(['uint80', '?'], D), TA)  # iterable case 10607
ck(f(['uint88', 'address'], D), T[U[HA, i], ...])  # iterable case 10608
ck(f(['uint88', 'address[]'], D), TA)  # iterable case 10609
ck(f(['uint88', 'bool'], D), T[U[bo, i], ...])  # iterable case 10610
ck(f(['uint88', 'bool[]'], D), TA)  # iterable case 10611
ck(f(['uint88', 'bytes'], D), T[U[by, i], ...])  # iterable case 10612
ck(f(['uint88', 'bytes1'], D), T[U[by, i], ...])  # iterable case 10613
ck(f(['uint88', 'bytes10'], D), T[U[by, i], ...])  # iterable case 10614
ck(f(['uint88', 'bytes11'], D), T[U[by, i], ...])  # iterable case 10615
ck(f(['uint88', 'bytes12'], D), T[U[by, i], ...])  # iterable case 10616
ck(f(['uint88', 'bytes13'], D), T[U[by, i], ...])  # iterable case 10617
ck(f(['uint88', 'bytes14'], D), T[U[by, i], ...])  # iterable case 10618
ck(f(['uint88', 'bytes15'], D), T[U[by, i], ...])  # iterable case 10619
ck(f(['uint88', 'bytes16'], D), T[U[by, i], ...])  # iterable case 10620
ck(f(['uint88', 'bytes17'], D), T[U[by, i], ...])  # iterable case 10621
ck(f(['uint88', 'bytes18'], D), T[U[by, i], ...])  # iterable case 10622
ck(f(['uint88', 'bytes19'], D), T[U[by, i], ...])  # iterable case 10623
ck(f(['uint88', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10624
ck(f(['uint88', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10625
ck(f(['uint88', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10626
ck(f(['uint88', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10627
ck(f(['uint88', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10628
ck(f(['uint88', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10629
ck(f(['uint88', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10630
ck(f(['uint88', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10631
ck(f(['uint88', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10632
ck(f(['uint88', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10633
ck(f(['uint88', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10634
ck(f(['uint88', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10635
ck(f(['uint88', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10636
ck(f(['uint88', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10637
ck(f(['uint88', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10638
ck(f(['uint88', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10639
ck(f(['uint88', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10640
ck(f(['uint88', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10641
ck(f(['uint88', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10642
ck(f(['uint88', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10643
ck(f(['uint88', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10644
ck(f(['uint88', 'int104'], D), T[i, ...])  # iterable case 10645
ck(f(['uint88', 'int112'], D), T[i, ...])  # iterable case 10646
ck(f(['uint88', 'int120'], D), T[i, ...])  # iterable case 10647
ck(f(['uint88', 'int128'], D), T[i, ...])  # iterable case 10648
ck(f(['uint88', 'int136'], D), T[i, ...])  # iterable case 10649
ck(f(['uint88', 'int144'], D), T[i, ...])  # iterable case 10650
ck(f(['uint88', 'int152'], D), T[i, ...])  # iterable case 10651
ck(f(['uint88', 'int16'], D), T[i, ...])  # iterable case 10652
ck(f(['uint88', 'int160'], D), T[i, ...])  # iterable case 10653
ck(f(['uint88', 'int168'], D), T[i, ...])  # iterable case 10654
ck(f(['uint88', 'int176'], D), T[i, ...])  # iterable case 10655
ck(f(['uint88', 'int184'], D), T[i, ...])  # iterable case 10656
ck(f(['uint88', 'int192'], D), T[i, ...])  # iterable case 10657
ck(f(['uint88', 'int200'], D), T[i, ...])  # iterable case 10658
ck(f(['uint88', 'int208'], D), T[i, ...])  # iterable case 10659
ck(f(['uint88', 'int216'], D), T[i, ...])  # iterable case 10660
ck(f(['uint88', 'int224'], D), T[i, ...])  # iterable case 10661
ck(f(['uint88', 'int232'], D), T[i, ...])  # iterable case 10662
ck(f(['uint88', 'int24'], D), T[i, ...])  # iterable case 10663
ck(f(['uint88', 'int240'], D), T[i, ...])  # iterable case 10664
ck(f(['uint88', 'int248'], D), T[i, ...])  # iterable case 10665
ck(f(['uint88', 'int256'], D), T[i, ...])  # iterable case 10666
ck(f(['uint88', 'int32'], D), T[i, ...])  # iterable case 10667
ck(f(['uint88', 'int40'], D), T[i, ...])  # iterable case 10668
ck(f(['uint88', 'int48'], D), T[i, ...])  # iterable case 10669
ck(f(['uint88', 'int56'], D), T[i, ...])  # iterable case 10670
ck(f(['uint88', 'int64'], D), T[i, ...])  # iterable case 10671
ck(f(['uint88', 'int72'], D), T[i, ...])  # iterable case 10672
ck(f(['uint88', 'int8'], D), T[i, ...])  # iterable case 10673
ck(f(['uint88', 'int80'], D), T[i, ...])  # iterable case 10674
ck(f(['uint88', 'int88'], D), T[i, ...])  # iterable case 10675
ck(f(['uint88', 'int96'], D), T[i, ...])  # iterable case 10676
ck(f(['uint88', 'string'], D), T[U[i, s], ...])  # iterable case 10677
ck(f(['uint88', 'string[]'], D), TA)  # iterable case 10678
ck(f(['uint88', 'uint104'], D), T[i, ...])  # iterable case 10679
ck(f(['uint88', 'uint112'], D), T[i, ...])  # iterable case 10680
ck(f(['uint88', 'uint120'], D), T[i, ...])  # iterable case 10681
ck(f(['uint88', 'uint128'], D), T[i, ...])  # iterable case 10682
ck(f(['uint88', 'uint136'], D), T[i, ...])  # iterable case 10683
ck(f(['uint88', 'uint144'], D), T[i, ...])  # iterable case 10684
ck(f(['uint88', 'uint152'], D), T[i, ...])  # iterable case 10685
ck(f(['uint88', 'uint16'], D), T[i, ...])  # iterable case 10686
ck(f(['uint88', 'uint160'], D), T[i, ...])  # iterable case 10687
ck(f(['uint88', 'uint168'], D), T[i, ...])  # iterable case 10688
ck(f(['uint88', 'uint176'], D), T[i, ...])  # iterable case 10689
ck(f(['uint88', 'uint184'], D), T[i, ...])  # iterable case 10690
ck(f(['uint88', 'uint192'], D), T[i, ...])  # iterable case 10691
ck(f(['uint88', 'uint200'], D), T[i, ...])  # iterable case 10692
ck(f(['uint88', 'uint208'], D), T[i, ...])  # iterable case 10693
ck(f(['uint88', 'uint216'], D), T[i, ...])  # iterable case 10694
ck(f(['uint88', 'uint224'], D), T[i, ...])  # iterable case 10695
ck(f(['uint88', 'uint232'], D), T[i, ...])  # iterable case 10696
ck(f(['uint88', 'uint24'], D), T[i, ...])  # iterable case 10697
ck(f(['uint88', 'uint240'], D), T[i, ...])  # iterable case 10698
ck(f(['uint88', 'uint248'], D), T[i, ...])  # iterable case 10699
ck(f(['uint88', 'uint256'], D), T[i, ...])  # iterable case 10700
ck(f(['uint88', 'uint32'], D), T[i, ...])  # iterable case 10701
ck(f(['uint88', 'uint40'], D), T[i, ...])  # iterable case 10702
ck(f(['uint88', 'uint48'], D), T[i, ...])  # iterable case 10703
ck(f(['uint88', 'uint56'], D), T[i, ...])  # iterable case 10704
ck(f(['uint88', 'uint64'], D), T[i, ...])  # iterable case 10705
ck(f(['uint88', 'uint72'], D), T[i, ...])  # iterable case 10706
ck(f(['uint88', 'uint8'], D), T[i, ...])  # iterable case 10707
ck(f(['uint88', 'uint80'], D), T[i, ...])  # iterable case 10708
ck(f(['uint88', 'uint88'], D), T[i, ...])  # iterable case 10709
ck(f(['uint88', 'uint96'], D), T[i, ...])  # iterable case 10710
ck(f(['uint88', '?'], D), TA)  # iterable case 10711
ck(f(['uint96', 'address'], D), T[U[HA, i], ...])  # iterable case 10712
ck(f(['uint96', 'address[]'], D), TA)  # iterable case 10713
ck(f(['uint96', 'bool'], D), T[U[bo, i], ...])  # iterable case 10714
ck(f(['uint96', 'bool[]'], D), TA)  # iterable case 10715
ck(f(['uint96', 'bytes'], D), T[U[by, i], ...])  # iterable case 10716
ck(f(['uint96', 'bytes1'], D), T[U[by, i], ...])  # iterable case 10717
ck(f(['uint96', 'bytes10'], D), T[U[by, i], ...])  # iterable case 10718
ck(f(['uint96', 'bytes11'], D), T[U[by, i], ...])  # iterable case 10719
ck(f(['uint96', 'bytes12'], D), T[U[by, i], ...])  # iterable case 10720
ck(f(['uint96', 'bytes13'], D), T[U[by, i], ...])  # iterable case 10721
ck(f(['uint96', 'bytes14'], D), T[U[by, i], ...])  # iterable case 10722
ck(f(['uint96', 'bytes15'], D), T[U[by, i], ...])  # iterable case 10723
ck(f(['uint96', 'bytes16'], D), T[U[by, i], ...])  # iterable case 10724
ck(f(['uint96', 'bytes17'], D), T[U[by, i], ...])  # iterable case 10725
ck(f(['uint96', 'bytes18'], D), T[U[by, i], ...])  # iterable case 10726
ck(f(['uint96', 'bytes19'], D), T[U[by, i], ...])  # iterable case 10727
ck(f(['uint96', 'bytes2'], D), T[U[by, i], ...])  # iterable case 10728
ck(f(['uint96', 'bytes20'], D), T[U[by, i], ...])  # iterable case 10729
ck(f(['uint96', 'bytes21'], D), T[U[by, i], ...])  # iterable case 10730
ck(f(['uint96', 'bytes22'], D), T[U[by, i], ...])  # iterable case 10731
ck(f(['uint96', 'bytes23'], D), T[U[by, i], ...])  # iterable case 10732
ck(f(['uint96', 'bytes24'], D), T[U[by, i], ...])  # iterable case 10733
ck(f(['uint96', 'bytes25'], D), T[U[by, i], ...])  # iterable case 10734
ck(f(['uint96', 'bytes26'], D), T[U[by, i], ...])  # iterable case 10735
ck(f(['uint96', 'bytes27'], D), T[U[by, i], ...])  # iterable case 10736
ck(f(['uint96', 'bytes28'], D), T[U[by, i], ...])  # iterable case 10737
ck(f(['uint96', 'bytes29'], D), T[U[by, i], ...])  # iterable case 10738
ck(f(['uint96', 'bytes3'], D), T[U[by, i], ...])  # iterable case 10739
ck(f(['uint96', 'bytes30'], D), T[U[by, i], ...])  # iterable case 10740
ck(f(['uint96', 'bytes31'], D), T[U[by, i], ...])  # iterable case 10741
ck(f(['uint96', 'bytes32'], D), T[U[by, i], ...])  # iterable case 10742
ck(f(['uint96', 'bytes4'], D), T[U[by, i], ...])  # iterable case 10743
ck(f(['uint96', 'bytes5'], D), T[U[by, i], ...])  # iterable case 10744
ck(f(['uint96', 'bytes6'], D), T[U[by, i], ...])  # iterable case 10745
ck(f(['uint96', 'bytes7'], D), T[U[by, i], ...])  # iterable case 10746
ck(f(['uint96', 'bytes8'], D), T[U[by, i], ...])  # iterable case 10747
ck(f(['uint96', 'bytes9'], D), T[U[by, i], ...])  # iterable case 10748
ck(f(['uint96', 'int104'], D), T[i, ...])  # iterable case 10749
ck(f(['uint96', 'int112'], D), T[i, ...])  # iterable case 10750
ck(f(['uint96', 'int120'], D), T[i, ...])  # iterable case 10751
ck(f(['uint96', 'int128'], D), T[i, ...])  # iterable case 10752
ck(f(['uint96', 'int136'], D), T[i, ...])  # iterable case 10753
ck(f(['uint96', 'int144'], D), T[i, ...])  # iterable case 10754
ck(f(['uint96', 'int152'], D), T[i, ...])  # iterable case 10755
ck(f(['uint96', 'int16'], D), T[i, ...])  # iterable case 10756
ck(f(['uint96', 'int160'], D), T[i, ...])  # iterable case 10757
ck(f(['uint96', 'int168'], D), T[i, ...])  # iterable case 10758
ck(f(['uint96', 'int176'], D), T[i, ...])  # iterable case 10759
ck(f(['uint96', 'int184'], D), T[i, ...])  # iterable case 10760
ck(f(['uint96', 'int192'], D), T[i, ...])  # iterable case 10761
ck(f(['uint96', 'int200'], D), T[i, ...])  # iterable case 10762
ck(f(['uint96', 'int208'], D), T[i, ...])  # iterable case 10763
ck(f(['uint96', 'int216'], D), T[i, ...])  # iterable case 10764
ck(f(['uint96', 'int224'], D), T[i, ...])  # iterable case 10765
ck(f(['uint96', 'int232'], D), T[i, ...])  # iterable case 10766
ck(f(['uint96', 'int24'], D), T[i, ...])  # iterable case 10767
ck(f(['uint96', 'int240'], D), T[i, ...])  # iterable case 10768
ck(f(['uint96', 'int248'], D), T[i, ...])  # iterable case 10769
ck(f(['uint96', 'int256'], D), T[i, ...])  # iterable case 10770
ck(f(['uint96', 'int32'], D), T[i, ...])  # iterable case 10771
ck(f(['uint96', 'int40'], D), T[i, ...])  # iterable case 10772
ck(f(['uint96', 'int48'], D), T[i, ...])  # iterable case 10773
ck(f(['uint96', 'int56'], D), T[i, ...])  # iterable case 10774
ck(f(['uint96', 'int64'], D), T[i, ...])  # iterable case 10775
ck(f(['uint96', 'int72'], D), T[i, ...])  # iterable case 10776
ck(f(['uint96', 'int8'], D), T[i, ...])  # iterable case 10777
ck(f(['uint96', 'int80'], D), T[i, ...])  # iterable case 10778
ck(f(['uint96', 'int88'], D), T[i, ...])  # iterable case 10779
ck(f(['uint96', 'int96'], D), T[i, ...])  # iterable case 10780
ck(f(['uint96', 'string'], D), T[U[i, s], ...])  # iterable case 10781
ck(f(['uint96', 'string[]'], D), TA)  # iterable case 10782
ck(f(['uint96', 'uint104'], D), T[i, ...])  # iterable case 10783
ck(f(['uint96', 'uint112'], D), T[i, ...])  # iterable case 10784
ck(f(['uint96', 'uint120'], D), T[i, ...])  # iterable case 10785
ck(f(['uint96', 'uint128'], D), T[i, ...])  # iterable case 10786
ck(f(['uint96', 'uint136'], D), T[i, ...])  # iterable case 10787
ck(f(['uint96', 'uint144'], D), T[i, ...])  # iterable case 10788
ck(f(['uint96', 'uint152'], D), T[i, ...])  # iterable case 10789
ck(f(['uint96', 'uint16'], D), T[i, ...])  # iterable case 10790
ck(f(['uint96', 'uint160'], D), T[i, ...])  # iterable case 10791
ck(f(['uint96', 'uint168'], D), T[i, ...])  # iterable case 10792
ck(f(['uint96', 'uint176'], D), T[i, ...])  # iterable case 10793
ck(f(['uint96', 'uint184'], D), T[i, ...])  # iterable case 10794
ck(f(['uint96', 'uint192'], D), T[i, ...])  # iterable case 10795
ck(f(['uint96', 'uint200'], D), T[i, ...])  # iterable case 10796
ck(f(['uint96', 'uint208'], D), T[i, ...])  # iterable case 10797
ck(f(['uint96', 'uint216'], D), T[i, ...])  # iterable case 10798
ck(f(['uint96', 'uint224'], D), T[i, ...])  # iterable case 10799
ck(f(['uint96', 'uint232'], D), T[i, ...])  # iterable case 10800
ck(f(['uint96', 'uint24'], D), T[i, ...])  # iterable case 10801
ck(f(['uint96', 'uint240'], D), T[i, ...])  # iterable case 10802
ck(f(['uint96', 'uint248'], D), T[i, ...])  # iterable case 10803
ck(f(['uint96', 'uint256'], D), T[i, ...])  # iterable case 10804
ck(f(['uint96', 'uint32'], D), T[i, ...])  # iterable case 10805
ck(f(['uint96', 'uint40'], D), T[i, ...])  # iterable case 10806
ck(f(['uint96', 'uint48'], D), T[i, ...])  # iterable case 10807
ck(f(['uint96', 'uint56'], D), T[i, ...])  # iterable case 10808
ck(f(['uint96', 'uint64'], D), T[i, ...])  # iterable case 10809
ck(f(['uint96', 'uint72'], D), T[i, ...])  # iterable case 10810
ck(f(['uint96', 'uint8'], D), T[i, ...])  # iterable case 10811
ck(f(['uint96', 'uint80'], D), T[i, ...])  # iterable case 10812
ck(f(['uint96', 'uint88'], D), T[i, ...])  # iterable case 10813
ck(f(['uint96', 'uint96'], D), T[i, ...])  # iterable case 10814
ck(f(['uint96', '?'], D), TA)  # iterable case 10815
ck(f(['?', 'address'], D), TA)  # iterable case 10816
ck(f(['?', 'address[]'], D), TA)  # iterable case 10817
ck(f(['?', 'bool'], D), TA)  # iterable case 10818
ck(f(['?', 'bool[]'], D), TA)  # iterable case 10819
ck(f(['?', 'bytes'], D), TA)  # iterable case 10820
ck(f(['?', 'bytes1'], D), TA)  # iterable case 10821
ck(f(['?', 'bytes10'], D), TA)  # iterable case 10822
ck(f(['?', 'bytes11'], D), TA)  # iterable case 10823
ck(f(['?', 'bytes12'], D), TA)  # iterable case 10824
ck(f(['?', 'bytes13'], D), TA)  # iterable case 10825
ck(f(['?', 'bytes14'], D), TA)  # iterable case 10826
ck(f(['?', 'bytes15'], D), TA)  # iterable case 10827
ck(f(['?', 'bytes16'], D), TA)  # iterable case 10828
ck(f(['?', 'bytes17'], D), TA)  # iterable case 10829
ck(f(['?', 'bytes18'], D), TA)  # iterable case 10830
ck(f(['?', 'bytes19'], D), TA)  # iterable case 10831
ck(f(['?', 'bytes2'], D), TA)  # iterable case 10832
ck(f(['?', 'bytes20'], D), TA)  # iterable case 10833
ck(f(['?', 'bytes21'], D), TA)  # iterable case 10834
ck(f(['?', 'bytes22'], D), TA)  # iterable case 10835
ck(f(['?', 'bytes23'], D), TA)  # iterable case 10836
ck(f(['?', 'bytes24'], D), TA)  # iterable case 10837
ck(f(['?', 'bytes25'], D), TA)  # iterable case 10838
ck(f(['?', 'bytes26'], D), TA)  # iterable case 10839
ck(f(['?', 'bytes27'], D), TA)  # iterable case 10840
ck(f(['?', 'bytes28'], D), TA)  # iterable case 10841
ck(f(['?', 'bytes29'], D), TA)  # iterable case 10842
ck(f(['?', 'bytes3'], D), TA)  # iterable case 10843
ck(f(['?', 'bytes30'], D), TA)  # iterable case 10844
ck(f(['?', 'bytes31'], D), TA)  # iterable case 10845
ck(f(['?', 'bytes32'], D), TA)  # iterable case 10846
ck(f(['?', 'bytes4'], D), TA)  # iterable case 10847
ck(f(['?', 'bytes5'], D), TA)  # iterable case 10848
ck(f(['?', 'bytes6'], D), TA)  # iterable case 10849
ck(f(['?', 'bytes7'], D), TA)  # iterable case 10850
ck(f(['?', 'bytes8'], D), TA)  # iterable case 10851
ck(f(['?', 'bytes9'], D), TA)  # iterable case 10852
ck(f(['?', 'int104'], D), TA)  # iterable case 10853
ck(f(['?', 'int112'], D), TA)  # iterable case 10854
ck(f(['?', 'int120'], D), TA)  # iterable case 10855
ck(f(['?', 'int128'], D), TA)  # iterable case 10856
ck(f(['?', 'int136'], D), TA)  # iterable case 10857
ck(f(['?', 'int144'], D), TA)  # iterable case 10858
ck(f(['?', 'int152'], D), TA)  # iterable case 10859
ck(f(['?', 'int16'], D), TA)  # iterable case 10860
ck(f(['?', 'int160'], D), TA)  # iterable case 10861
ck(f(['?', 'int168'], D), TA)  # iterable case 10862
ck(f(['?', 'int176'], D), TA)  # iterable case 10863
ck(f(['?', 'int184'], D), TA)  # iterable case 10864
ck(f(['?', 'int192'], D), TA)  # iterable case 10865
ck(f(['?', 'int200'], D), TA)  # iterable case 10866
ck(f(['?', 'int208'], D), TA)  # iterable case 10867
ck(f(['?', 'int216'], D), TA)  # iterable case 10868
ck(f(['?', 'int224'], D), TA)  # iterable case 10869
ck(f(['?', 'int232'], D), TA)  # iterable case 10870
ck(f(['?', 'int24'], D), TA)  # iterable case 10871
ck(f(['?', 'int240'], D), TA)  # iterable case 10872
ck(f(['?', 'int248'], D), TA)  # iterable case 10873
ck(f(['?', 'int256'], D), TA)  # iterable case 10874
ck(f(['?', 'int32'], D), TA)  # iterable case 10875
ck(f(['?', 'int40'], D), TA)  # iterable case 10876
ck(f(['?', 'int48'], D), TA)  # iterable case 10877
ck(f(['?', 'int56'], D), TA)  # iterable case 10878
ck(f(['?', 'int64'], D), TA)  # iterable case 10879
ck(f(['?', 'int72'], D), TA)  # iterable case 10880
ck(f(['?', 'int8'], D), TA)  # iterable case 10881
ck(f(['?', 'int80'], D), TA)  # iterable case 10882
ck(f(['?', 'int88'], D), TA)  # iterable case 10883
ck(f(['?', 'int96'], D), TA)  # iterable case 10884
ck(f(['?', 'string'], D), TA)  # iterable case 10885
ck(f(['?', 'string[]'], D), TA)  # iterable case 10886
ck(f(['?', 'uint104'], D), TA)  # iterable case 10887
ck(f(['?', 'uint112'], D), TA)  # iterable case 10888
ck(f(['?', 'uint120'], D), TA)  # iterable case 10889
ck(f(['?', 'uint128'], D), TA)  # iterable case 10890
ck(f(['?', 'uint136'], D), TA)  # iterable case 10891
ck(f(['?', 'uint144'], D), TA)  # iterable case 10892
ck(f(['?', 'uint152'], D), TA)  # iterable case 10893
ck(f(['?', 'uint16'], D), TA)  # iterable case 10894
ck(f(['?', 'uint160'], D), TA)  # iterable case 10895
ck(f(['?', 'uint168'], D), TA)  # iterable case 10896
ck(f(['?', 'uint176'], D), TA)  # iterable case 10897
ck(f(['?', 'uint184'], D), TA)  # iterable case 10898
ck(f(['?', 'uint192'], D), TA)  # iterable case 10899
ck(f(['?', 'uint200'], D), TA)  # iterable case 10900
ck(f(['?', 'uint208'], D), TA)  # iterable case 10901
ck(f(['?', 'uint216'], D), TA)  # iterable case 10902
ck(f(['?', 'uint224'], D), TA)  # iterable case 10903
ck(f(['?', 'uint232'], D), TA)  # iterable case 10904
ck(f(['?', 'uint24'], D), TA)  # iterable case 10905
ck(f(['?', 'uint240'], D), TA)  # iterable case 10906
ck(f(['?', 'uint248'], D), TA)  # iterable case 10907
ck(f(['?', 'uint256'], D), TA)  # iterable case 10908
ck(f(['?', 'uint32'], D), TA)  # iterable case 10909
ck(f(['?', 'uint40'], D), TA)  # iterable case 10910
ck(f(['?', 'uint48'], D), TA)  # iterable case 10911
ck(f(['?', 'uint56'], D), TA)  # iterable case 10912
ck(f(['?', 'uint64'], D), TA)  # iterable case 10913
ck(f(['?', 'uint72'], D), TA)  # iterable case 10914
ck(f(['?', 'uint8'], D), TA)  # iterable case 10915
ck(f(['?', 'uint80'], D), TA)  # iterable case 10916
ck(f(['?', 'uint88'], D), TA)  # iterable case 10917
ck(f(['?', 'uint96'], D), TA)  # iterable case 10918
ck(f(['?', '?'], D), TA)  # iterable case 10919
