# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(decoder.decode(("uint96[]", "address[]"), data), Tuple[Tuple[int, ...], Tuple[HexAddress, ...]])  # tuple case 40201
assert_type(decoder.decode(("uint96[]", "bool"), data), Tuple[Tuple[int, ...], bool])  # tuple case 40202
assert_type(decoder.decode(("uint96[]", "bool[]"), data), Tuple[Tuple[int, ...], Tuple[bool, ...]])  # tuple case 40203
assert_type(decoder.decode(("uint96[]", "bytes"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40204
assert_type(decoder.decode(("uint96[]", "bytes1"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40205
assert_type(decoder.decode(("uint96[]", "bytes10"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40206
assert_type(decoder.decode(("uint96[]", "bytes10[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40207
assert_type(decoder.decode(("uint96[]", "bytes11"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40208
assert_type(decoder.decode(("uint96[]", "bytes11[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40209
assert_type(decoder.decode(("uint96[]", "bytes12"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40210
assert_type(decoder.decode(("uint96[]", "bytes12[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40211
assert_type(decoder.decode(("uint96[]", "bytes13"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40212
assert_type(decoder.decode(("uint96[]", "bytes13[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40213
assert_type(decoder.decode(("uint96[]", "bytes14"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40214
assert_type(decoder.decode(("uint96[]", "bytes14[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40215
assert_type(decoder.decode(("uint96[]", "bytes15"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40216
assert_type(decoder.decode(("uint96[]", "bytes15[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40217
assert_type(decoder.decode(("uint96[]", "bytes16"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40218
assert_type(decoder.decode(("uint96[]", "bytes16[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40219
assert_type(decoder.decode(("uint96[]", "bytes17"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40220
assert_type(decoder.decode(("uint96[]", "bytes17[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40221
assert_type(decoder.decode(("uint96[]", "bytes18"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40222
assert_type(decoder.decode(("uint96[]", "bytes18[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40223
assert_type(decoder.decode(("uint96[]", "bytes19"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40224
assert_type(decoder.decode(("uint96[]", "bytes19[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40225
assert_type(decoder.decode(("uint96[]", "bytes1[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40226
assert_type(decoder.decode(("uint96[]", "bytes2"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40227
assert_type(decoder.decode(("uint96[]", "bytes20"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40228
assert_type(decoder.decode(("uint96[]", "bytes20[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40229
assert_type(decoder.decode(("uint96[]", "bytes21"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40230
assert_type(decoder.decode(("uint96[]", "bytes21[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40231
assert_type(decoder.decode(("uint96[]", "bytes22"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40232
assert_type(decoder.decode(("uint96[]", "bytes22[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40233
assert_type(decoder.decode(("uint96[]", "bytes23"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40234
assert_type(decoder.decode(("uint96[]", "bytes23[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40235
assert_type(decoder.decode(("uint96[]", "bytes24"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40236
assert_type(decoder.decode(("uint96[]", "bytes24[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40237
assert_type(decoder.decode(("uint96[]", "bytes25"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40238
assert_type(decoder.decode(("uint96[]", "bytes25[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40239
assert_type(decoder.decode(("uint96[]", "bytes26"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40240
assert_type(decoder.decode(("uint96[]", "bytes26[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40241
assert_type(decoder.decode(("uint96[]", "bytes27"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40242
assert_type(decoder.decode(("uint96[]", "bytes27[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40243
assert_type(decoder.decode(("uint96[]", "bytes28"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40244
assert_type(decoder.decode(("uint96[]", "bytes28[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40245
assert_type(decoder.decode(("uint96[]", "bytes29"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40246
assert_type(decoder.decode(("uint96[]", "bytes29[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40247
assert_type(decoder.decode(("uint96[]", "bytes2[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40248
assert_type(decoder.decode(("uint96[]", "bytes3"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40249
assert_type(decoder.decode(("uint96[]", "bytes30"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40250
assert_type(decoder.decode(("uint96[]", "bytes30[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40251
assert_type(decoder.decode(("uint96[]", "bytes31"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40252
assert_type(decoder.decode(("uint96[]", "bytes31[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40253
assert_type(decoder.decode(("uint96[]", "bytes32"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40254
assert_type(decoder.decode(("uint96[]", "bytes32[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40255
assert_type(decoder.decode(("uint96[]", "bytes3[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40256
assert_type(decoder.decode(("uint96[]", "bytes4"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40257
assert_type(decoder.decode(("uint96[]", "bytes4[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40258
assert_type(decoder.decode(("uint96[]", "bytes5"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40259
assert_type(decoder.decode(("uint96[]", "bytes5[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40260
assert_type(decoder.decode(("uint96[]", "bytes6"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40261
assert_type(decoder.decode(("uint96[]", "bytes6[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40262
assert_type(decoder.decode(("uint96[]", "bytes7"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40263
assert_type(decoder.decode(("uint96[]", "bytes7[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40264
assert_type(decoder.decode(("uint96[]", "bytes8"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40265
assert_type(decoder.decode(("uint96[]", "bytes8[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40266
assert_type(decoder.decode(("uint96[]", "bytes9"), data), Tuple[Tuple[int, ...], bytes])  # tuple case 40267
assert_type(decoder.decode(("uint96[]", "bytes9[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40268
assert_type(decoder.decode(("uint96[]", "bytes[]"), data), Tuple[Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 40269
assert_type(decoder.decode(("uint96[]", "int104"), data), Tuple[Tuple[int, ...], int])  # tuple case 40270
assert_type(decoder.decode(("uint96[]", "int104[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40271
assert_type(decoder.decode(("uint96[]", "int112"), data), Tuple[Tuple[int, ...], int])  # tuple case 40272
assert_type(decoder.decode(("uint96[]", "int112[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40273
assert_type(decoder.decode(("uint96[]", "int120"), data), Tuple[Tuple[int, ...], int])  # tuple case 40274
assert_type(decoder.decode(("uint96[]", "int120[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40275
assert_type(decoder.decode(("uint96[]", "int128"), data), Tuple[Tuple[int, ...], int])  # tuple case 40276
assert_type(decoder.decode(("uint96[]", "int128[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40277
assert_type(decoder.decode(("uint96[]", "int136"), data), Tuple[Tuple[int, ...], int])  # tuple case 40278
assert_type(decoder.decode(("uint96[]", "int136[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40279
assert_type(decoder.decode(("uint96[]", "int144"), data), Tuple[Tuple[int, ...], int])  # tuple case 40280
assert_type(decoder.decode(("uint96[]", "int144[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40281
assert_type(decoder.decode(("uint96[]", "int152"), data), Tuple[Tuple[int, ...], int])  # tuple case 40282
assert_type(decoder.decode(("uint96[]", "int152[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40283
assert_type(decoder.decode(("uint96[]", "int16"), data), Tuple[Tuple[int, ...], int])  # tuple case 40284
assert_type(decoder.decode(("uint96[]", "int160"), data), Tuple[Tuple[int, ...], int])  # tuple case 40285
assert_type(decoder.decode(("uint96[]", "int160[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40286
assert_type(decoder.decode(("uint96[]", "int168"), data), Tuple[Tuple[int, ...], int])  # tuple case 40287
assert_type(decoder.decode(("uint96[]", "int168[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40288
assert_type(decoder.decode(("uint96[]", "int16[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40289
assert_type(decoder.decode(("uint96[]", "int176"), data), Tuple[Tuple[int, ...], int])  # tuple case 40290
assert_type(decoder.decode(("uint96[]", "int176[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40291
assert_type(decoder.decode(("uint96[]", "int184"), data), Tuple[Tuple[int, ...], int])  # tuple case 40292
assert_type(decoder.decode(("uint96[]", "int184[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40293
assert_type(decoder.decode(("uint96[]", "int192"), data), Tuple[Tuple[int, ...], int])  # tuple case 40294
assert_type(decoder.decode(("uint96[]", "int192[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40295
assert_type(decoder.decode(("uint96[]", "int200"), data), Tuple[Tuple[int, ...], int])  # tuple case 40296
assert_type(decoder.decode(("uint96[]", "int200[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40297
assert_type(decoder.decode(("uint96[]", "int208"), data), Tuple[Tuple[int, ...], int])  # tuple case 40298
assert_type(decoder.decode(("uint96[]", "int208[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40299
assert_type(decoder.decode(("uint96[]", "int216"), data), Tuple[Tuple[int, ...], int])  # tuple case 40300
assert_type(decoder.decode(("uint96[]", "int216[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40301
assert_type(decoder.decode(("uint96[]", "int224"), data), Tuple[Tuple[int, ...], int])  # tuple case 40302
assert_type(decoder.decode(("uint96[]", "int224[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40303
assert_type(decoder.decode(("uint96[]", "int232"), data), Tuple[Tuple[int, ...], int])  # tuple case 40304
assert_type(decoder.decode(("uint96[]", "int232[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40305
assert_type(decoder.decode(("uint96[]", "int24"), data), Tuple[Tuple[int, ...], int])  # tuple case 40306
assert_type(decoder.decode(("uint96[]", "int240"), data), Tuple[Tuple[int, ...], int])  # tuple case 40307
assert_type(decoder.decode(("uint96[]", "int240[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40308
assert_type(decoder.decode(("uint96[]", "int248"), data), Tuple[Tuple[int, ...], int])  # tuple case 40309
assert_type(decoder.decode(("uint96[]", "int248[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40310
assert_type(decoder.decode(("uint96[]", "int24[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40311
assert_type(decoder.decode(("uint96[]", "int256"), data), Tuple[Tuple[int, ...], int])  # tuple case 40312
assert_type(decoder.decode(("uint96[]", "int256[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40313
assert_type(decoder.decode(("uint96[]", "int32"), data), Tuple[Tuple[int, ...], int])  # tuple case 40314
assert_type(decoder.decode(("uint96[]", "int32[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40315
assert_type(decoder.decode(("uint96[]", "int40"), data), Tuple[Tuple[int, ...], int])  # tuple case 40316
assert_type(decoder.decode(("uint96[]", "int40[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40317
assert_type(decoder.decode(("uint96[]", "int48"), data), Tuple[Tuple[int, ...], int])  # tuple case 40318
assert_type(decoder.decode(("uint96[]", "int48[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40319
assert_type(decoder.decode(("uint96[]", "int56"), data), Tuple[Tuple[int, ...], int])  # tuple case 40320
assert_type(decoder.decode(("uint96[]", "int56[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40321
assert_type(decoder.decode(("uint96[]", "int64"), data), Tuple[Tuple[int, ...], int])  # tuple case 40322
assert_type(decoder.decode(("uint96[]", "int64[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40323
assert_type(decoder.decode(("uint96[]", "int72"), data), Tuple[Tuple[int, ...], int])  # tuple case 40324
assert_type(decoder.decode(("uint96[]", "int72[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40325
assert_type(decoder.decode(("uint96[]", "int8"), data), Tuple[Tuple[int, ...], int])  # tuple case 40326
assert_type(decoder.decode(("uint96[]", "int80"), data), Tuple[Tuple[int, ...], int])  # tuple case 40327
assert_type(decoder.decode(("uint96[]", "int80[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40328
assert_type(decoder.decode(("uint96[]", "int88"), data), Tuple[Tuple[int, ...], int])  # tuple case 40329
assert_type(decoder.decode(("uint96[]", "int88[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40330
assert_type(decoder.decode(("uint96[]", "int8[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40331
assert_type(decoder.decode(("uint96[]", "int96"), data), Tuple[Tuple[int, ...], int])  # tuple case 40332
assert_type(decoder.decode(("uint96[]", "int96[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40333
assert_type(decoder.decode(("uint96[]", "string"), data), Tuple[Tuple[int, ...], str])  # tuple case 40334
assert_type(decoder.decode(("uint96[]", "string[]"), data), Tuple[Tuple[int, ...], Tuple[str, ...]])  # tuple case 40335
assert_type(decoder.decode(("uint96[]", "uint104"), data), Tuple[Tuple[int, ...], int])  # tuple case 40336
assert_type(decoder.decode(("uint96[]", "uint104[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40337
assert_type(decoder.decode(("uint96[]", "uint112"), data), Tuple[Tuple[int, ...], int])  # tuple case 40338
assert_type(decoder.decode(("uint96[]", "uint112[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40339
assert_type(decoder.decode(("uint96[]", "uint120"), data), Tuple[Tuple[int, ...], int])  # tuple case 40340
assert_type(decoder.decode(("uint96[]", "uint120[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40341
assert_type(decoder.decode(("uint96[]", "uint128"), data), Tuple[Tuple[int, ...], int])  # tuple case 40342
assert_type(decoder.decode(("uint96[]", "uint128[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40343
assert_type(decoder.decode(("uint96[]", "uint136"), data), Tuple[Tuple[int, ...], int])  # tuple case 40344
assert_type(decoder.decode(("uint96[]", "uint136[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40345
assert_type(decoder.decode(("uint96[]", "uint144"), data), Tuple[Tuple[int, ...], int])  # tuple case 40346
assert_type(decoder.decode(("uint96[]", "uint144[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40347
assert_type(decoder.decode(("uint96[]", "uint152"), data), Tuple[Tuple[int, ...], int])  # tuple case 40348
assert_type(decoder.decode(("uint96[]", "uint152[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40349
assert_type(decoder.decode(("uint96[]", "uint16"), data), Tuple[Tuple[int, ...], int])  # tuple case 40350
assert_type(decoder.decode(("uint96[]", "uint160"), data), Tuple[Tuple[int, ...], int])  # tuple case 40351
assert_type(decoder.decode(("uint96[]", "uint160[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40352
assert_type(decoder.decode(("uint96[]", "uint168"), data), Tuple[Tuple[int, ...], int])  # tuple case 40353
assert_type(decoder.decode(("uint96[]", "uint168[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40354
assert_type(decoder.decode(("uint96[]", "uint16[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40355
assert_type(decoder.decode(("uint96[]", "uint176"), data), Tuple[Tuple[int, ...], int])  # tuple case 40356
assert_type(decoder.decode(("uint96[]", "uint176[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40357
assert_type(decoder.decode(("uint96[]", "uint184"), data), Tuple[Tuple[int, ...], int])  # tuple case 40358
assert_type(decoder.decode(("uint96[]", "uint184[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40359
assert_type(decoder.decode(("uint96[]", "uint192"), data), Tuple[Tuple[int, ...], int])  # tuple case 40360
assert_type(decoder.decode(("uint96[]", "uint192[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40361
assert_type(decoder.decode(("uint96[]", "uint200"), data), Tuple[Tuple[int, ...], int])  # tuple case 40362
assert_type(decoder.decode(("uint96[]", "uint200[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40363
assert_type(decoder.decode(("uint96[]", "uint208"), data), Tuple[Tuple[int, ...], int])  # tuple case 40364
assert_type(decoder.decode(("uint96[]", "uint208[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40365
assert_type(decoder.decode(("uint96[]", "uint216"), data), Tuple[Tuple[int, ...], int])  # tuple case 40366
assert_type(decoder.decode(("uint96[]", "uint216[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40367
assert_type(decoder.decode(("uint96[]", "uint224"), data), Tuple[Tuple[int, ...], int])  # tuple case 40368
assert_type(decoder.decode(("uint96[]", "uint224[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40369
assert_type(decoder.decode(("uint96[]", "uint232"), data), Tuple[Tuple[int, ...], int])  # tuple case 40370
assert_type(decoder.decode(("uint96[]", "uint232[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40371
assert_type(decoder.decode(("uint96[]", "uint24"), data), Tuple[Tuple[int, ...], int])  # tuple case 40372
assert_type(decoder.decode(("uint96[]", "uint240"), data), Tuple[Tuple[int, ...], int])  # tuple case 40373
assert_type(decoder.decode(("uint96[]", "uint240[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40374
assert_type(decoder.decode(("uint96[]", "uint248"), data), Tuple[Tuple[int, ...], int])  # tuple case 40375
assert_type(decoder.decode(("uint96[]", "uint248[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40376
assert_type(decoder.decode(("uint96[]", "uint24[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40377
assert_type(decoder.decode(("uint96[]", "uint256"), data), Tuple[Tuple[int, ...], int])  # tuple case 40378
assert_type(decoder.decode(("uint96[]", "uint256[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40379
assert_type(decoder.decode(("uint96[]", "uint32"), data), Tuple[Tuple[int, ...], int])  # tuple case 40380
assert_type(decoder.decode(("uint96[]", "uint32[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40381
assert_type(decoder.decode(("uint96[]", "uint40"), data), Tuple[Tuple[int, ...], int])  # tuple case 40382
assert_type(decoder.decode(("uint96[]", "uint40[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40383
assert_type(decoder.decode(("uint96[]", "uint48"), data), Tuple[Tuple[int, ...], int])  # tuple case 40384
assert_type(decoder.decode(("uint96[]", "uint48[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40385
assert_type(decoder.decode(("uint96[]", "uint56"), data), Tuple[Tuple[int, ...], int])  # tuple case 40386
assert_type(decoder.decode(("uint96[]", "uint56[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40387
assert_type(decoder.decode(("uint96[]", "uint64"), data), Tuple[Tuple[int, ...], int])  # tuple case 40388
assert_type(decoder.decode(("uint96[]", "uint64[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40389
assert_type(decoder.decode(("uint96[]", "uint72"), data), Tuple[Tuple[int, ...], int])  # tuple case 40390
assert_type(decoder.decode(("uint96[]", "uint72[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40391
assert_type(decoder.decode(("uint96[]", "uint8"), data), Tuple[Tuple[int, ...], int])  # tuple case 40392
assert_type(decoder.decode(("uint96[]", "uint80"), data), Tuple[Tuple[int, ...], int])  # tuple case 40393
assert_type(decoder.decode(("uint96[]", "uint80[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40394
assert_type(decoder.decode(("uint96[]", "uint88"), data), Tuple[Tuple[int, ...], int])  # tuple case 40395
assert_type(decoder.decode(("uint96[]", "uint88[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40396
assert_type(decoder.decode(("uint96[]", "uint8[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40397
assert_type(decoder.decode(("uint96[]", "uint96"), data), Tuple[Tuple[int, ...], int])  # tuple case 40398
assert_type(decoder.decode(("uint96[]", "uint96[]"), data), Tuple[Tuple[int, ...], Tuple[int, ...]])  # tuple case 40399
assert_type(decoder.decode(("uint96[]", "someothertype"), data), Tuple[Tuple[int, ...], Any])  # tuple case 40400
assert_type(decoder.decode(("someothertype", "address"), data), Tuple[Any, HexAddress])  # tuple case 40401
assert_type(decoder.decode(("someothertype", "address[]"), data), Tuple[Any, Tuple[HexAddress, ...]])  # tuple case 40402
assert_type(decoder.decode(("someothertype", "bool"), data), Tuple[Any, bool])  # tuple case 40403
assert_type(decoder.decode(("someothertype", "bool[]"), data), Tuple[Any, Tuple[bool, ...]])  # tuple case 40404
assert_type(decoder.decode(("someothertype", "bytes"), data), Tuple[Any, bytes])  # tuple case 40405
assert_type(decoder.decode(("someothertype", "bytes1"), data), Tuple[Any, bytes])  # tuple case 40406
assert_type(decoder.decode(("someothertype", "bytes10"), data), Tuple[Any, bytes])  # tuple case 40407
assert_type(decoder.decode(("someothertype", "bytes10[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40408
assert_type(decoder.decode(("someothertype", "bytes11"), data), Tuple[Any, bytes])  # tuple case 40409
assert_type(decoder.decode(("someothertype", "bytes11[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40410
assert_type(decoder.decode(("someothertype", "bytes12"), data), Tuple[Any, bytes])  # tuple case 40411
assert_type(decoder.decode(("someothertype", "bytes12[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40412
assert_type(decoder.decode(("someothertype", "bytes13"), data), Tuple[Any, bytes])  # tuple case 40413
assert_type(decoder.decode(("someothertype", "bytes13[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40414
assert_type(decoder.decode(("someothertype", "bytes14"), data), Tuple[Any, bytes])  # tuple case 40415
assert_type(decoder.decode(("someothertype", "bytes14[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40416
assert_type(decoder.decode(("someothertype", "bytes15"), data), Tuple[Any, bytes])  # tuple case 40417
assert_type(decoder.decode(("someothertype", "bytes15[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40418
assert_type(decoder.decode(("someothertype", "bytes16"), data), Tuple[Any, bytes])  # tuple case 40419
assert_type(decoder.decode(("someothertype", "bytes16[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40420
assert_type(decoder.decode(("someothertype", "bytes17"), data), Tuple[Any, bytes])  # tuple case 40421
assert_type(decoder.decode(("someothertype", "bytes17[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40422
assert_type(decoder.decode(("someothertype", "bytes18"), data), Tuple[Any, bytes])  # tuple case 40423
assert_type(decoder.decode(("someothertype", "bytes18[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40424
assert_type(decoder.decode(("someothertype", "bytes19"), data), Tuple[Any, bytes])  # tuple case 40425
assert_type(decoder.decode(("someothertype", "bytes19[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40426
assert_type(decoder.decode(("someothertype", "bytes1[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40427
assert_type(decoder.decode(("someothertype", "bytes2"), data), Tuple[Any, bytes])  # tuple case 40428
assert_type(decoder.decode(("someothertype", "bytes20"), data), Tuple[Any, bytes])  # tuple case 40429
assert_type(decoder.decode(("someothertype", "bytes20[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40430
assert_type(decoder.decode(("someothertype", "bytes21"), data), Tuple[Any, bytes])  # tuple case 40431
assert_type(decoder.decode(("someothertype", "bytes21[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40432
assert_type(decoder.decode(("someothertype", "bytes22"), data), Tuple[Any, bytes])  # tuple case 40433
assert_type(decoder.decode(("someothertype", "bytes22[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40434
assert_type(decoder.decode(("someothertype", "bytes23"), data), Tuple[Any, bytes])  # tuple case 40435
assert_type(decoder.decode(("someothertype", "bytes23[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40436
assert_type(decoder.decode(("someothertype", "bytes24"), data), Tuple[Any, bytes])  # tuple case 40437
assert_type(decoder.decode(("someothertype", "bytes24[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40438
assert_type(decoder.decode(("someothertype", "bytes25"), data), Tuple[Any, bytes])  # tuple case 40439
assert_type(decoder.decode(("someothertype", "bytes25[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40440
assert_type(decoder.decode(("someothertype", "bytes26"), data), Tuple[Any, bytes])  # tuple case 40441
assert_type(decoder.decode(("someothertype", "bytes26[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40442
assert_type(decoder.decode(("someothertype", "bytes27"), data), Tuple[Any, bytes])  # tuple case 40443
assert_type(decoder.decode(("someothertype", "bytes27[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40444
assert_type(decoder.decode(("someothertype", "bytes28"), data), Tuple[Any, bytes])  # tuple case 40445
assert_type(decoder.decode(("someothertype", "bytes28[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40446
assert_type(decoder.decode(("someothertype", "bytes29"), data), Tuple[Any, bytes])  # tuple case 40447
assert_type(decoder.decode(("someothertype", "bytes29[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40448
assert_type(decoder.decode(("someothertype", "bytes2[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40449
assert_type(decoder.decode(("someothertype", "bytes3"), data), Tuple[Any, bytes])  # tuple case 40450
assert_type(decoder.decode(("someothertype", "bytes30"), data), Tuple[Any, bytes])  # tuple case 40451
assert_type(decoder.decode(("someothertype", "bytes30[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40452
assert_type(decoder.decode(("someothertype", "bytes31"), data), Tuple[Any, bytes])  # tuple case 40453
assert_type(decoder.decode(("someothertype", "bytes31[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40454
assert_type(decoder.decode(("someothertype", "bytes32"), data), Tuple[Any, bytes])  # tuple case 40455
assert_type(decoder.decode(("someothertype", "bytes32[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40456
assert_type(decoder.decode(("someothertype", "bytes3[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40457
assert_type(decoder.decode(("someothertype", "bytes4"), data), Tuple[Any, bytes])  # tuple case 40458
assert_type(decoder.decode(("someothertype", "bytes4[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40459
assert_type(decoder.decode(("someothertype", "bytes5"), data), Tuple[Any, bytes])  # tuple case 40460
assert_type(decoder.decode(("someothertype", "bytes5[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40461
assert_type(decoder.decode(("someothertype", "bytes6"), data), Tuple[Any, bytes])  # tuple case 40462
assert_type(decoder.decode(("someothertype", "bytes6[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40463
assert_type(decoder.decode(("someothertype", "bytes7"), data), Tuple[Any, bytes])  # tuple case 40464
assert_type(decoder.decode(("someothertype", "bytes7[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40465
assert_type(decoder.decode(("someothertype", "bytes8"), data), Tuple[Any, bytes])  # tuple case 40466
assert_type(decoder.decode(("someothertype", "bytes8[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40467
assert_type(decoder.decode(("someothertype", "bytes9"), data), Tuple[Any, bytes])  # tuple case 40468
assert_type(decoder.decode(("someothertype", "bytes9[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40469
assert_type(decoder.decode(("someothertype", "bytes[]"), data), Tuple[Any, Tuple[bytes, ...]])  # tuple case 40470
assert_type(decoder.decode(("someothertype", "int104"), data), Tuple[Any, int])  # tuple case 40471
assert_type(decoder.decode(("someothertype", "int104[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40472
assert_type(decoder.decode(("someothertype", "int112"), data), Tuple[Any, int])  # tuple case 40473
assert_type(decoder.decode(("someothertype", "int112[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40474
assert_type(decoder.decode(("someothertype", "int120"), data), Tuple[Any, int])  # tuple case 40475
assert_type(decoder.decode(("someothertype", "int120[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40476
assert_type(decoder.decode(("someothertype", "int128"), data), Tuple[Any, int])  # tuple case 40477
assert_type(decoder.decode(("someothertype", "int128[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40478
assert_type(decoder.decode(("someothertype", "int136"), data), Tuple[Any, int])  # tuple case 40479
assert_type(decoder.decode(("someothertype", "int136[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40480
assert_type(decoder.decode(("someothertype", "int144"), data), Tuple[Any, int])  # tuple case 40481
assert_type(decoder.decode(("someothertype", "int144[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40482
assert_type(decoder.decode(("someothertype", "int152"), data), Tuple[Any, int])  # tuple case 40483
assert_type(decoder.decode(("someothertype", "int152[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40484
assert_type(decoder.decode(("someothertype", "int16"), data), Tuple[Any, int])  # tuple case 40485
assert_type(decoder.decode(("someothertype", "int160"), data), Tuple[Any, int])  # tuple case 40486
assert_type(decoder.decode(("someothertype", "int160[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40487
assert_type(decoder.decode(("someothertype", "int168"), data), Tuple[Any, int])  # tuple case 40488
assert_type(decoder.decode(("someothertype", "int168[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40489
assert_type(decoder.decode(("someothertype", "int16[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40490
assert_type(decoder.decode(("someothertype", "int176"), data), Tuple[Any, int])  # tuple case 40491
assert_type(decoder.decode(("someothertype", "int176[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40492
assert_type(decoder.decode(("someothertype", "int184"), data), Tuple[Any, int])  # tuple case 40493
assert_type(decoder.decode(("someothertype", "int184[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40494
assert_type(decoder.decode(("someothertype", "int192"), data), Tuple[Any, int])  # tuple case 40495
assert_type(decoder.decode(("someothertype", "int192[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40496
assert_type(decoder.decode(("someothertype", "int200"), data), Tuple[Any, int])  # tuple case 40497
assert_type(decoder.decode(("someothertype", "int200[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40498
assert_type(decoder.decode(("someothertype", "int208"), data), Tuple[Any, int])  # tuple case 40499
assert_type(decoder.decode(("someothertype", "int208[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40500
assert_type(decoder.decode(("someothertype", "int216"), data), Tuple[Any, int])  # tuple case 40501
assert_type(decoder.decode(("someothertype", "int216[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40502
assert_type(decoder.decode(("someothertype", "int224"), data), Tuple[Any, int])  # tuple case 40503
assert_type(decoder.decode(("someothertype", "int224[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40504
assert_type(decoder.decode(("someothertype", "int232"), data), Tuple[Any, int])  # tuple case 40505
assert_type(decoder.decode(("someothertype", "int232[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40506
assert_type(decoder.decode(("someothertype", "int24"), data), Tuple[Any, int])  # tuple case 40507
assert_type(decoder.decode(("someothertype", "int240"), data), Tuple[Any, int])  # tuple case 40508
assert_type(decoder.decode(("someothertype", "int240[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40509
assert_type(decoder.decode(("someothertype", "int248"), data), Tuple[Any, int])  # tuple case 40510
assert_type(decoder.decode(("someothertype", "int248[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40511
assert_type(decoder.decode(("someothertype", "int24[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40512
assert_type(decoder.decode(("someothertype", "int256"), data), Tuple[Any, int])  # tuple case 40513
assert_type(decoder.decode(("someothertype", "int256[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40514
assert_type(decoder.decode(("someothertype", "int32"), data), Tuple[Any, int])  # tuple case 40515
assert_type(decoder.decode(("someothertype", "int32[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40516
assert_type(decoder.decode(("someothertype", "int40"), data), Tuple[Any, int])  # tuple case 40517
assert_type(decoder.decode(("someothertype", "int40[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40518
assert_type(decoder.decode(("someothertype", "int48"), data), Tuple[Any, int])  # tuple case 40519
assert_type(decoder.decode(("someothertype", "int48[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40520
assert_type(decoder.decode(("someothertype", "int56"), data), Tuple[Any, int])  # tuple case 40521
assert_type(decoder.decode(("someothertype", "int56[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40522
assert_type(decoder.decode(("someothertype", "int64"), data), Tuple[Any, int])  # tuple case 40523
assert_type(decoder.decode(("someothertype", "int64[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40524
assert_type(decoder.decode(("someothertype", "int72"), data), Tuple[Any, int])  # tuple case 40525
assert_type(decoder.decode(("someothertype", "int72[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40526
assert_type(decoder.decode(("someothertype", "int8"), data), Tuple[Any, int])  # tuple case 40527
assert_type(decoder.decode(("someothertype", "int80"), data), Tuple[Any, int])  # tuple case 40528
assert_type(decoder.decode(("someothertype", "int80[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40529
assert_type(decoder.decode(("someothertype", "int88"), data), Tuple[Any, int])  # tuple case 40530
assert_type(decoder.decode(("someothertype", "int88[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40531
assert_type(decoder.decode(("someothertype", "int8[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40532
assert_type(decoder.decode(("someothertype", "int96"), data), Tuple[Any, int])  # tuple case 40533
assert_type(decoder.decode(("someothertype", "int96[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40534
assert_type(decoder.decode(("someothertype", "string"), data), Tuple[Any, str])  # tuple case 40535
assert_type(decoder.decode(("someothertype", "string[]"), data), Tuple[Any, Tuple[str, ...]])  # tuple case 40536
assert_type(decoder.decode(("someothertype", "uint104"), data), Tuple[Any, int])  # tuple case 40537
assert_type(decoder.decode(("someothertype", "uint104[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40538
assert_type(decoder.decode(("someothertype", "uint112"), data), Tuple[Any, int])  # tuple case 40539
assert_type(decoder.decode(("someothertype", "uint112[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40540
assert_type(decoder.decode(("someothertype", "uint120"), data), Tuple[Any, int])  # tuple case 40541
assert_type(decoder.decode(("someothertype", "uint120[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40542
assert_type(decoder.decode(("someothertype", "uint128"), data), Tuple[Any, int])  # tuple case 40543
assert_type(decoder.decode(("someothertype", "uint128[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40544
assert_type(decoder.decode(("someothertype", "uint136"), data), Tuple[Any, int])  # tuple case 40545
assert_type(decoder.decode(("someothertype", "uint136[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40546
assert_type(decoder.decode(("someothertype", "uint144"), data), Tuple[Any, int])  # tuple case 40547
assert_type(decoder.decode(("someothertype", "uint144[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40548
assert_type(decoder.decode(("someothertype", "uint152"), data), Tuple[Any, int])  # tuple case 40549
assert_type(decoder.decode(("someothertype", "uint152[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40550
assert_type(decoder.decode(("someothertype", "uint16"), data), Tuple[Any, int])  # tuple case 40551
assert_type(decoder.decode(("someothertype", "uint160"), data), Tuple[Any, int])  # tuple case 40552
assert_type(decoder.decode(("someothertype", "uint160[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40553
assert_type(decoder.decode(("someothertype", "uint168"), data), Tuple[Any, int])  # tuple case 40554
assert_type(decoder.decode(("someothertype", "uint168[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40555
assert_type(decoder.decode(("someothertype", "uint16[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40556
assert_type(decoder.decode(("someothertype", "uint176"), data), Tuple[Any, int])  # tuple case 40557
assert_type(decoder.decode(("someothertype", "uint176[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40558
assert_type(decoder.decode(("someothertype", "uint184"), data), Tuple[Any, int])  # tuple case 40559
assert_type(decoder.decode(("someothertype", "uint184[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40560
assert_type(decoder.decode(("someothertype", "uint192"), data), Tuple[Any, int])  # tuple case 40561
assert_type(decoder.decode(("someothertype", "uint192[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40562
assert_type(decoder.decode(("someothertype", "uint200"), data), Tuple[Any, int])  # tuple case 40563
assert_type(decoder.decode(("someothertype", "uint200[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40564
assert_type(decoder.decode(("someothertype", "uint208"), data), Tuple[Any, int])  # tuple case 40565
assert_type(decoder.decode(("someothertype", "uint208[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40566
assert_type(decoder.decode(("someothertype", "uint216"), data), Tuple[Any, int])  # tuple case 40567
assert_type(decoder.decode(("someothertype", "uint216[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40568
assert_type(decoder.decode(("someothertype", "uint224"), data), Tuple[Any, int])  # tuple case 40569
assert_type(decoder.decode(("someothertype", "uint224[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40570
assert_type(decoder.decode(("someothertype", "uint232"), data), Tuple[Any, int])  # tuple case 40571
assert_type(decoder.decode(("someothertype", "uint232[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40572
assert_type(decoder.decode(("someothertype", "uint24"), data), Tuple[Any, int])  # tuple case 40573
assert_type(decoder.decode(("someothertype", "uint240"), data), Tuple[Any, int])  # tuple case 40574
assert_type(decoder.decode(("someothertype", "uint240[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40575
assert_type(decoder.decode(("someothertype", "uint248"), data), Tuple[Any, int])  # tuple case 40576
assert_type(decoder.decode(("someothertype", "uint248[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40577
assert_type(decoder.decode(("someothertype", "uint24[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40578
assert_type(decoder.decode(("someothertype", "uint256"), data), Tuple[Any, int])  # tuple case 40579
assert_type(decoder.decode(("someothertype", "uint256[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40580
assert_type(decoder.decode(("someothertype", "uint32"), data), Tuple[Any, int])  # tuple case 40581
assert_type(decoder.decode(("someothertype", "uint32[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40582
assert_type(decoder.decode(("someothertype", "uint40"), data), Tuple[Any, int])  # tuple case 40583
assert_type(decoder.decode(("someothertype", "uint40[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40584
assert_type(decoder.decode(("someothertype", "uint48"), data), Tuple[Any, int])  # tuple case 40585
assert_type(decoder.decode(("someothertype", "uint48[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40586
assert_type(decoder.decode(("someothertype", "uint56"), data), Tuple[Any, int])  # tuple case 40587
assert_type(decoder.decode(("someothertype", "uint56[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40588
assert_type(decoder.decode(("someothertype", "uint64"), data), Tuple[Any, int])  # tuple case 40589
assert_type(decoder.decode(("someothertype", "uint64[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40590
assert_type(decoder.decode(("someothertype", "uint72"), data), Tuple[Any, int])  # tuple case 40591
assert_type(decoder.decode(("someothertype", "uint72[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40592
assert_type(decoder.decode(("someothertype", "uint8"), data), Tuple[Any, int])  # tuple case 40593
assert_type(decoder.decode(("someothertype", "uint80"), data), Tuple[Any, int])  # tuple case 40594
assert_type(decoder.decode(("someothertype", "uint80[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40595
assert_type(decoder.decode(("someothertype", "uint88"), data), Tuple[Any, int])  # tuple case 40596
assert_type(decoder.decode(("someothertype", "uint88[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40597
assert_type(decoder.decode(("someothertype", "uint8[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40598
assert_type(decoder.decode(("someothertype", "uint96"), data), Tuple[Any, int])  # tuple case 40599
assert_type(decoder.decode(("someothertype", "uint96[]"), data), Tuple[Any, Tuple[int, ...]])  # tuple case 40600
assert_type(decoder.decode(("someothertype", "someothertype"), data), Tuple[Any, Any])  # tuple case 40601
