# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(decoder.decode(("someothertype", "uint96", "bool"), data), Tuple[Any, int, bool])  # tuple case 8160602
assert_type(decoder.decode(("someothertype", "uint96", "bool[]"), data), Tuple[Any, int, Tuple[bool, ...]])  # tuple case 8160603
assert_type(decoder.decode(("someothertype", "uint96", "bytes"), data), Tuple[Any, int, bytes])  # tuple case 8160604
assert_type(decoder.decode(("someothertype", "uint96", "bytes1"), data), Tuple[Any, int, bytes])  # tuple case 8160605
assert_type(decoder.decode(("someothertype", "uint96", "bytes10"), data), Tuple[Any, int, bytes])  # tuple case 8160606
assert_type(decoder.decode(("someothertype", "uint96", "bytes10[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160607
assert_type(decoder.decode(("someothertype", "uint96", "bytes11"), data), Tuple[Any, int, bytes])  # tuple case 8160608
assert_type(decoder.decode(("someothertype", "uint96", "bytes11[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160609
assert_type(decoder.decode(("someothertype", "uint96", "bytes12"), data), Tuple[Any, int, bytes])  # tuple case 8160610
assert_type(decoder.decode(("someothertype", "uint96", "bytes12[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160611
assert_type(decoder.decode(("someothertype", "uint96", "bytes13"), data), Tuple[Any, int, bytes])  # tuple case 8160612
assert_type(decoder.decode(("someothertype", "uint96", "bytes13[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160613
assert_type(decoder.decode(("someothertype", "uint96", "bytes14"), data), Tuple[Any, int, bytes])  # tuple case 8160614
assert_type(decoder.decode(("someothertype", "uint96", "bytes14[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160615
assert_type(decoder.decode(("someothertype", "uint96", "bytes15"), data), Tuple[Any, int, bytes])  # tuple case 8160616
assert_type(decoder.decode(("someothertype", "uint96", "bytes15[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160617
assert_type(decoder.decode(("someothertype", "uint96", "bytes16"), data), Tuple[Any, int, bytes])  # tuple case 8160618
assert_type(decoder.decode(("someothertype", "uint96", "bytes16[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160619
assert_type(decoder.decode(("someothertype", "uint96", "bytes17"), data), Tuple[Any, int, bytes])  # tuple case 8160620
assert_type(decoder.decode(("someothertype", "uint96", "bytes17[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160621
assert_type(decoder.decode(("someothertype", "uint96", "bytes18"), data), Tuple[Any, int, bytes])  # tuple case 8160622
assert_type(decoder.decode(("someothertype", "uint96", "bytes18[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160623
assert_type(decoder.decode(("someothertype", "uint96", "bytes19"), data), Tuple[Any, int, bytes])  # tuple case 8160624
assert_type(decoder.decode(("someothertype", "uint96", "bytes19[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160625
assert_type(decoder.decode(("someothertype", "uint96", "bytes1[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160626
assert_type(decoder.decode(("someothertype", "uint96", "bytes2"), data), Tuple[Any, int, bytes])  # tuple case 8160627
assert_type(decoder.decode(("someothertype", "uint96", "bytes20"), data), Tuple[Any, int, bytes])  # tuple case 8160628
assert_type(decoder.decode(("someothertype", "uint96", "bytes20[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160629
assert_type(decoder.decode(("someothertype", "uint96", "bytes21"), data), Tuple[Any, int, bytes])  # tuple case 8160630
assert_type(decoder.decode(("someothertype", "uint96", "bytes21[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160631
assert_type(decoder.decode(("someothertype", "uint96", "bytes22"), data), Tuple[Any, int, bytes])  # tuple case 8160632
assert_type(decoder.decode(("someothertype", "uint96", "bytes22[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160633
assert_type(decoder.decode(("someothertype", "uint96", "bytes23"), data), Tuple[Any, int, bytes])  # tuple case 8160634
assert_type(decoder.decode(("someothertype", "uint96", "bytes23[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160635
assert_type(decoder.decode(("someothertype", "uint96", "bytes24"), data), Tuple[Any, int, bytes])  # tuple case 8160636
assert_type(decoder.decode(("someothertype", "uint96", "bytes24[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160637
assert_type(decoder.decode(("someothertype", "uint96", "bytes25"), data), Tuple[Any, int, bytes])  # tuple case 8160638
assert_type(decoder.decode(("someothertype", "uint96", "bytes25[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160639
assert_type(decoder.decode(("someothertype", "uint96", "bytes26"), data), Tuple[Any, int, bytes])  # tuple case 8160640
assert_type(decoder.decode(("someothertype", "uint96", "bytes26[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160641
assert_type(decoder.decode(("someothertype", "uint96", "bytes27"), data), Tuple[Any, int, bytes])  # tuple case 8160642
assert_type(decoder.decode(("someothertype", "uint96", "bytes27[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160643
assert_type(decoder.decode(("someothertype", "uint96", "bytes28"), data), Tuple[Any, int, bytes])  # tuple case 8160644
assert_type(decoder.decode(("someothertype", "uint96", "bytes28[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160645
assert_type(decoder.decode(("someothertype", "uint96", "bytes29"), data), Tuple[Any, int, bytes])  # tuple case 8160646
assert_type(decoder.decode(("someothertype", "uint96", "bytes29[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160647
assert_type(decoder.decode(("someothertype", "uint96", "bytes2[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160648
assert_type(decoder.decode(("someothertype", "uint96", "bytes3"), data), Tuple[Any, int, bytes])  # tuple case 8160649
assert_type(decoder.decode(("someothertype", "uint96", "bytes30"), data), Tuple[Any, int, bytes])  # tuple case 8160650
assert_type(decoder.decode(("someothertype", "uint96", "bytes30[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160651
assert_type(decoder.decode(("someothertype", "uint96", "bytes31"), data), Tuple[Any, int, bytes])  # tuple case 8160652
assert_type(decoder.decode(("someothertype", "uint96", "bytes31[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160653
assert_type(decoder.decode(("someothertype", "uint96", "bytes32"), data), Tuple[Any, int, bytes])  # tuple case 8160654
assert_type(decoder.decode(("someothertype", "uint96", "bytes32[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160655
assert_type(decoder.decode(("someothertype", "uint96", "bytes3[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160656
assert_type(decoder.decode(("someothertype", "uint96", "bytes4"), data), Tuple[Any, int, bytes])  # tuple case 8160657
assert_type(decoder.decode(("someothertype", "uint96", "bytes4[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160658
assert_type(decoder.decode(("someothertype", "uint96", "bytes5"), data), Tuple[Any, int, bytes])  # tuple case 8160659
assert_type(decoder.decode(("someothertype", "uint96", "bytes5[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160660
assert_type(decoder.decode(("someothertype", "uint96", "bytes6"), data), Tuple[Any, int, bytes])  # tuple case 8160661
assert_type(decoder.decode(("someothertype", "uint96", "bytes6[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160662
assert_type(decoder.decode(("someothertype", "uint96", "bytes7"), data), Tuple[Any, int, bytes])  # tuple case 8160663
assert_type(decoder.decode(("someothertype", "uint96", "bytes7[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160664
assert_type(decoder.decode(("someothertype", "uint96", "bytes8"), data), Tuple[Any, int, bytes])  # tuple case 8160665
assert_type(decoder.decode(("someothertype", "uint96", "bytes8[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160666
assert_type(decoder.decode(("someothertype", "uint96", "bytes9"), data), Tuple[Any, int, bytes])  # tuple case 8160667
assert_type(decoder.decode(("someothertype", "uint96", "bytes9[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160668
assert_type(decoder.decode(("someothertype", "uint96", "bytes[]"), data), Tuple[Any, int, Tuple[bytes, ...]])  # tuple case 8160669
assert_type(decoder.decode(("someothertype", "uint96", "int104"), data), Tuple[Any, int, int])  # tuple case 8160670
assert_type(decoder.decode(("someothertype", "uint96", "int104[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160671
assert_type(decoder.decode(("someothertype", "uint96", "int112"), data), Tuple[Any, int, int])  # tuple case 8160672
assert_type(decoder.decode(("someothertype", "uint96", "int112[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160673
assert_type(decoder.decode(("someothertype", "uint96", "int120"), data), Tuple[Any, int, int])  # tuple case 8160674
assert_type(decoder.decode(("someothertype", "uint96", "int120[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160675
assert_type(decoder.decode(("someothertype", "uint96", "int128"), data), Tuple[Any, int, int])  # tuple case 8160676
assert_type(decoder.decode(("someothertype", "uint96", "int128[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160677
assert_type(decoder.decode(("someothertype", "uint96", "int136"), data), Tuple[Any, int, int])  # tuple case 8160678
assert_type(decoder.decode(("someothertype", "uint96", "int136[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160679
assert_type(decoder.decode(("someothertype", "uint96", "int144"), data), Tuple[Any, int, int])  # tuple case 8160680
assert_type(decoder.decode(("someothertype", "uint96", "int144[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160681
assert_type(decoder.decode(("someothertype", "uint96", "int152"), data), Tuple[Any, int, int])  # tuple case 8160682
assert_type(decoder.decode(("someothertype", "uint96", "int152[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160683
assert_type(decoder.decode(("someothertype", "uint96", "int16"), data), Tuple[Any, int, int])  # tuple case 8160684
assert_type(decoder.decode(("someothertype", "uint96", "int160"), data), Tuple[Any, int, int])  # tuple case 8160685
assert_type(decoder.decode(("someothertype", "uint96", "int160[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160686
assert_type(decoder.decode(("someothertype", "uint96", "int168"), data), Tuple[Any, int, int])  # tuple case 8160687
assert_type(decoder.decode(("someothertype", "uint96", "int168[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160688
assert_type(decoder.decode(("someothertype", "uint96", "int16[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160689
assert_type(decoder.decode(("someothertype", "uint96", "int176"), data), Tuple[Any, int, int])  # tuple case 8160690
assert_type(decoder.decode(("someothertype", "uint96", "int176[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160691
assert_type(decoder.decode(("someothertype", "uint96", "int184"), data), Tuple[Any, int, int])  # tuple case 8160692
assert_type(decoder.decode(("someothertype", "uint96", "int184[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160693
assert_type(decoder.decode(("someothertype", "uint96", "int192"), data), Tuple[Any, int, int])  # tuple case 8160694
assert_type(decoder.decode(("someothertype", "uint96", "int192[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160695
assert_type(decoder.decode(("someothertype", "uint96", "int200"), data), Tuple[Any, int, int])  # tuple case 8160696
assert_type(decoder.decode(("someothertype", "uint96", "int200[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160697
assert_type(decoder.decode(("someothertype", "uint96", "int208"), data), Tuple[Any, int, int])  # tuple case 8160698
assert_type(decoder.decode(("someothertype", "uint96", "int208[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160699
assert_type(decoder.decode(("someothertype", "uint96", "int216"), data), Tuple[Any, int, int])  # tuple case 8160700
assert_type(decoder.decode(("someothertype", "uint96", "int216[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160701
assert_type(decoder.decode(("someothertype", "uint96", "int224"), data), Tuple[Any, int, int])  # tuple case 8160702
assert_type(decoder.decode(("someothertype", "uint96", "int224[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160703
assert_type(decoder.decode(("someothertype", "uint96", "int232"), data), Tuple[Any, int, int])  # tuple case 8160704
assert_type(decoder.decode(("someothertype", "uint96", "int232[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160705
assert_type(decoder.decode(("someothertype", "uint96", "int24"), data), Tuple[Any, int, int])  # tuple case 8160706
assert_type(decoder.decode(("someothertype", "uint96", "int240"), data), Tuple[Any, int, int])  # tuple case 8160707
assert_type(decoder.decode(("someothertype", "uint96", "int240[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160708
assert_type(decoder.decode(("someothertype", "uint96", "int248"), data), Tuple[Any, int, int])  # tuple case 8160709
assert_type(decoder.decode(("someothertype", "uint96", "int248[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160710
assert_type(decoder.decode(("someothertype", "uint96", "int24[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160711
assert_type(decoder.decode(("someothertype", "uint96", "int256"), data), Tuple[Any, int, int])  # tuple case 8160712
assert_type(decoder.decode(("someothertype", "uint96", "int256[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160713
assert_type(decoder.decode(("someothertype", "uint96", "int32"), data), Tuple[Any, int, int])  # tuple case 8160714
assert_type(decoder.decode(("someothertype", "uint96", "int32[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160715
assert_type(decoder.decode(("someothertype", "uint96", "int40"), data), Tuple[Any, int, int])  # tuple case 8160716
assert_type(decoder.decode(("someothertype", "uint96", "int40[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160717
assert_type(decoder.decode(("someothertype", "uint96", "int48"), data), Tuple[Any, int, int])  # tuple case 8160718
assert_type(decoder.decode(("someothertype", "uint96", "int48[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160719
assert_type(decoder.decode(("someothertype", "uint96", "int56"), data), Tuple[Any, int, int])  # tuple case 8160720
assert_type(decoder.decode(("someothertype", "uint96", "int56[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160721
assert_type(decoder.decode(("someothertype", "uint96", "int64"), data), Tuple[Any, int, int])  # tuple case 8160722
assert_type(decoder.decode(("someothertype", "uint96", "int64[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160723
assert_type(decoder.decode(("someothertype", "uint96", "int72"), data), Tuple[Any, int, int])  # tuple case 8160724
assert_type(decoder.decode(("someothertype", "uint96", "int72[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160725
assert_type(decoder.decode(("someothertype", "uint96", "int8"), data), Tuple[Any, int, int])  # tuple case 8160726
assert_type(decoder.decode(("someothertype", "uint96", "int80"), data), Tuple[Any, int, int])  # tuple case 8160727
assert_type(decoder.decode(("someothertype", "uint96", "int80[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160728
assert_type(decoder.decode(("someothertype", "uint96", "int88"), data), Tuple[Any, int, int])  # tuple case 8160729
assert_type(decoder.decode(("someothertype", "uint96", "int88[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160730
assert_type(decoder.decode(("someothertype", "uint96", "int8[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160731
assert_type(decoder.decode(("someothertype", "uint96", "int96"), data), Tuple[Any, int, int])  # tuple case 8160732
assert_type(decoder.decode(("someothertype", "uint96", "int96[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160733
assert_type(decoder.decode(("someothertype", "uint96", "string"), data), Tuple[Any, int, str])  # tuple case 8160734
assert_type(decoder.decode(("someothertype", "uint96", "string[]"), data), Tuple[Any, int, Tuple[str, ...]])  # tuple case 8160735
assert_type(decoder.decode(("someothertype", "uint96", "uint104"), data), Tuple[Any, int, int])  # tuple case 8160736
assert_type(decoder.decode(("someothertype", "uint96", "uint104[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160737
assert_type(decoder.decode(("someothertype", "uint96", "uint112"), data), Tuple[Any, int, int])  # tuple case 8160738
assert_type(decoder.decode(("someothertype", "uint96", "uint112[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160739
assert_type(decoder.decode(("someothertype", "uint96", "uint120"), data), Tuple[Any, int, int])  # tuple case 8160740
assert_type(decoder.decode(("someothertype", "uint96", "uint120[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160741
assert_type(decoder.decode(("someothertype", "uint96", "uint128"), data), Tuple[Any, int, int])  # tuple case 8160742
assert_type(decoder.decode(("someothertype", "uint96", "uint128[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160743
assert_type(decoder.decode(("someothertype", "uint96", "uint136"), data), Tuple[Any, int, int])  # tuple case 8160744
assert_type(decoder.decode(("someothertype", "uint96", "uint136[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160745
assert_type(decoder.decode(("someothertype", "uint96", "uint144"), data), Tuple[Any, int, int])  # tuple case 8160746
assert_type(decoder.decode(("someothertype", "uint96", "uint144[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160747
assert_type(decoder.decode(("someothertype", "uint96", "uint152"), data), Tuple[Any, int, int])  # tuple case 8160748
assert_type(decoder.decode(("someothertype", "uint96", "uint152[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160749
assert_type(decoder.decode(("someothertype", "uint96", "uint16"), data), Tuple[Any, int, int])  # tuple case 8160750
assert_type(decoder.decode(("someothertype", "uint96", "uint160"), data), Tuple[Any, int, int])  # tuple case 8160751
assert_type(decoder.decode(("someothertype", "uint96", "uint160[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160752
assert_type(decoder.decode(("someothertype", "uint96", "uint168"), data), Tuple[Any, int, int])  # tuple case 8160753
assert_type(decoder.decode(("someothertype", "uint96", "uint168[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160754
assert_type(decoder.decode(("someothertype", "uint96", "uint16[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160755
assert_type(decoder.decode(("someothertype", "uint96", "uint176"), data), Tuple[Any, int, int])  # tuple case 8160756
assert_type(decoder.decode(("someothertype", "uint96", "uint176[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160757
assert_type(decoder.decode(("someothertype", "uint96", "uint184"), data), Tuple[Any, int, int])  # tuple case 8160758
assert_type(decoder.decode(("someothertype", "uint96", "uint184[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160759
assert_type(decoder.decode(("someothertype", "uint96", "uint192"), data), Tuple[Any, int, int])  # tuple case 8160760
assert_type(decoder.decode(("someothertype", "uint96", "uint192[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160761
assert_type(decoder.decode(("someothertype", "uint96", "uint200"), data), Tuple[Any, int, int])  # tuple case 8160762
assert_type(decoder.decode(("someothertype", "uint96", "uint200[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160763
assert_type(decoder.decode(("someothertype", "uint96", "uint208"), data), Tuple[Any, int, int])  # tuple case 8160764
assert_type(decoder.decode(("someothertype", "uint96", "uint208[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160765
assert_type(decoder.decode(("someothertype", "uint96", "uint216"), data), Tuple[Any, int, int])  # tuple case 8160766
assert_type(decoder.decode(("someothertype", "uint96", "uint216[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160767
assert_type(decoder.decode(("someothertype", "uint96", "uint224"), data), Tuple[Any, int, int])  # tuple case 8160768
assert_type(decoder.decode(("someothertype", "uint96", "uint224[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160769
assert_type(decoder.decode(("someothertype", "uint96", "uint232"), data), Tuple[Any, int, int])  # tuple case 8160770
assert_type(decoder.decode(("someothertype", "uint96", "uint232[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160771
assert_type(decoder.decode(("someothertype", "uint96", "uint24"), data), Tuple[Any, int, int])  # tuple case 8160772
assert_type(decoder.decode(("someothertype", "uint96", "uint240"), data), Tuple[Any, int, int])  # tuple case 8160773
assert_type(decoder.decode(("someothertype", "uint96", "uint240[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160774
assert_type(decoder.decode(("someothertype", "uint96", "uint248"), data), Tuple[Any, int, int])  # tuple case 8160775
assert_type(decoder.decode(("someothertype", "uint96", "uint248[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160776
assert_type(decoder.decode(("someothertype", "uint96", "uint24[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160777
assert_type(decoder.decode(("someothertype", "uint96", "uint256"), data), Tuple[Any, int, int])  # tuple case 8160778
assert_type(decoder.decode(("someothertype", "uint96", "uint256[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160779
assert_type(decoder.decode(("someothertype", "uint96", "uint32"), data), Tuple[Any, int, int])  # tuple case 8160780
assert_type(decoder.decode(("someothertype", "uint96", "uint32[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160781
assert_type(decoder.decode(("someothertype", "uint96", "uint40"), data), Tuple[Any, int, int])  # tuple case 8160782
assert_type(decoder.decode(("someothertype", "uint96", "uint40[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160783
assert_type(decoder.decode(("someothertype", "uint96", "uint48"), data), Tuple[Any, int, int])  # tuple case 8160784
assert_type(decoder.decode(("someothertype", "uint96", "uint48[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160785
assert_type(decoder.decode(("someothertype", "uint96", "uint56"), data), Tuple[Any, int, int])  # tuple case 8160786
assert_type(decoder.decode(("someothertype", "uint96", "uint56[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160787
assert_type(decoder.decode(("someothertype", "uint96", "uint64"), data), Tuple[Any, int, int])  # tuple case 8160788
assert_type(decoder.decode(("someothertype", "uint96", "uint64[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160789
assert_type(decoder.decode(("someothertype", "uint96", "uint72"), data), Tuple[Any, int, int])  # tuple case 8160790
assert_type(decoder.decode(("someothertype", "uint96", "uint72[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160791
assert_type(decoder.decode(("someothertype", "uint96", "uint8"), data), Tuple[Any, int, int])  # tuple case 8160792
assert_type(decoder.decode(("someothertype", "uint96", "uint80"), data), Tuple[Any, int, int])  # tuple case 8160793
assert_type(decoder.decode(("someothertype", "uint96", "uint80[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160794
assert_type(decoder.decode(("someothertype", "uint96", "uint88"), data), Tuple[Any, int, int])  # tuple case 8160795
assert_type(decoder.decode(("someothertype", "uint96", "uint88[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160796
assert_type(decoder.decode(("someothertype", "uint96", "uint8[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160797
assert_type(decoder.decode(("someothertype", "uint96", "uint96"), data), Tuple[Any, int, int])  # tuple case 8160798
assert_type(decoder.decode(("someothertype", "uint96", "uint96[]"), data), Tuple[Any, int, Tuple[int, ...]])  # tuple case 8160799
assert_type(decoder.decode(("someothertype", "uint96", "someothertype"), data), Tuple[Any, int, Any])  # tuple case 8160800
assert_type(decoder.decode(("someothertype", "uint96[]", "address"), data), Tuple[Any, Tuple[int, ...], HexAddress])  # tuple case 8160801
assert_type(decoder.decode(("someothertype", "uint96[]", "address[]"), data), Tuple[Any, Tuple[int, ...], Tuple[HexAddress, ...]])  # tuple case 8160802
assert_type(decoder.decode(("someothertype", "uint96[]", "bool"), data), Tuple[Any, Tuple[int, ...], bool])  # tuple case 8160803
assert_type(decoder.decode(("someothertype", "uint96[]", "bool[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bool, ...]])  # tuple case 8160804
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160805
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes1"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160806
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes10"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160807
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes10[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160808
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes11"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160809
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes11[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160810
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes12"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160811
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes12[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160812
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes13"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160813
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes13[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160814
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes14"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160815
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes14[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160816
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes15"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160817
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes15[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160818
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes16"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160819
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes16[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160820
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes17"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160821
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes17[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160822
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes18"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160823
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes18[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160824
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes19"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160825
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes19[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160826
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes1[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160827
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes2"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160828
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes20"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160829
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes20[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160830
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes21"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160831
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes21[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160832
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes22"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160833
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes22[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160834
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes23"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160835
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes23[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160836
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes24"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160837
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes24[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160838
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes25"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160839
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes25[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160840
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes26"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160841
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes26[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160842
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes27"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160843
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes27[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160844
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes28"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160845
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes28[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160846
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes29"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160847
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes29[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160848
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes2[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160849
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes3"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160850
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes30"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160851
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes30[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160852
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes31"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160853
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes31[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160854
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes32"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160855
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes32[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160856
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes3[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160857
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes4"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160858
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes4[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160859
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes5"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160860
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes5[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160861
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes6"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160862
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes6[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160863
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes7"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160864
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes7[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160865
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes8"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160866
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes8[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160867
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes9"), data), Tuple[Any, Tuple[int, ...], bytes])  # tuple case 8160868
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes9[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160869
assert_type(decoder.decode(("someothertype", "uint96[]", "bytes[]"), data), Tuple[Any, Tuple[int, ...], Tuple[bytes, ...]])  # tuple case 8160870
assert_type(decoder.decode(("someothertype", "uint96[]", "int104"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160871
assert_type(decoder.decode(("someothertype", "uint96[]", "int104[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160872
assert_type(decoder.decode(("someothertype", "uint96[]", "int112"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160873
assert_type(decoder.decode(("someothertype", "uint96[]", "int112[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160874
assert_type(decoder.decode(("someothertype", "uint96[]", "int120"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160875
assert_type(decoder.decode(("someothertype", "uint96[]", "int120[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160876
assert_type(decoder.decode(("someothertype", "uint96[]", "int128"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160877
assert_type(decoder.decode(("someothertype", "uint96[]", "int128[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160878
assert_type(decoder.decode(("someothertype", "uint96[]", "int136"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160879
assert_type(decoder.decode(("someothertype", "uint96[]", "int136[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160880
assert_type(decoder.decode(("someothertype", "uint96[]", "int144"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160881
assert_type(decoder.decode(("someothertype", "uint96[]", "int144[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160882
assert_type(decoder.decode(("someothertype", "uint96[]", "int152"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160883
assert_type(decoder.decode(("someothertype", "uint96[]", "int152[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160884
assert_type(decoder.decode(("someothertype", "uint96[]", "int16"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160885
assert_type(decoder.decode(("someothertype", "uint96[]", "int160"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160886
assert_type(decoder.decode(("someothertype", "uint96[]", "int160[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160887
assert_type(decoder.decode(("someothertype", "uint96[]", "int168"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160888
assert_type(decoder.decode(("someothertype", "uint96[]", "int168[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160889
assert_type(decoder.decode(("someothertype", "uint96[]", "int16[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160890
assert_type(decoder.decode(("someothertype", "uint96[]", "int176"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160891
assert_type(decoder.decode(("someothertype", "uint96[]", "int176[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160892
assert_type(decoder.decode(("someothertype", "uint96[]", "int184"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160893
assert_type(decoder.decode(("someothertype", "uint96[]", "int184[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160894
assert_type(decoder.decode(("someothertype", "uint96[]", "int192"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160895
assert_type(decoder.decode(("someothertype", "uint96[]", "int192[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160896
assert_type(decoder.decode(("someothertype", "uint96[]", "int200"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160897
assert_type(decoder.decode(("someothertype", "uint96[]", "int200[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160898
assert_type(decoder.decode(("someothertype", "uint96[]", "int208"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160899
assert_type(decoder.decode(("someothertype", "uint96[]", "int208[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160900
assert_type(decoder.decode(("someothertype", "uint96[]", "int216"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160901
assert_type(decoder.decode(("someothertype", "uint96[]", "int216[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160902
assert_type(decoder.decode(("someothertype", "uint96[]", "int224"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160903
assert_type(decoder.decode(("someothertype", "uint96[]", "int224[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160904
assert_type(decoder.decode(("someothertype", "uint96[]", "int232"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160905
assert_type(decoder.decode(("someothertype", "uint96[]", "int232[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160906
assert_type(decoder.decode(("someothertype", "uint96[]", "int24"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160907
assert_type(decoder.decode(("someothertype", "uint96[]", "int240"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160908
assert_type(decoder.decode(("someothertype", "uint96[]", "int240[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160909
assert_type(decoder.decode(("someothertype", "uint96[]", "int248"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160910
assert_type(decoder.decode(("someothertype", "uint96[]", "int248[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160911
assert_type(decoder.decode(("someothertype", "uint96[]", "int24[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160912
assert_type(decoder.decode(("someothertype", "uint96[]", "int256"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160913
assert_type(decoder.decode(("someothertype", "uint96[]", "int256[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160914
assert_type(decoder.decode(("someothertype", "uint96[]", "int32"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160915
assert_type(decoder.decode(("someothertype", "uint96[]", "int32[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160916
assert_type(decoder.decode(("someothertype", "uint96[]", "int40"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160917
assert_type(decoder.decode(("someothertype", "uint96[]", "int40[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160918
assert_type(decoder.decode(("someothertype", "uint96[]", "int48"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160919
assert_type(decoder.decode(("someothertype", "uint96[]", "int48[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160920
assert_type(decoder.decode(("someothertype", "uint96[]", "int56"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160921
assert_type(decoder.decode(("someothertype", "uint96[]", "int56[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160922
assert_type(decoder.decode(("someothertype", "uint96[]", "int64"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160923
assert_type(decoder.decode(("someothertype", "uint96[]", "int64[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160924
assert_type(decoder.decode(("someothertype", "uint96[]", "int72"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160925
assert_type(decoder.decode(("someothertype", "uint96[]", "int72[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160926
assert_type(decoder.decode(("someothertype", "uint96[]", "int8"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160927
assert_type(decoder.decode(("someothertype", "uint96[]", "int80"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160928
assert_type(decoder.decode(("someothertype", "uint96[]", "int80[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160929
assert_type(decoder.decode(("someothertype", "uint96[]", "int88"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160930
assert_type(decoder.decode(("someothertype", "uint96[]", "int88[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160931
assert_type(decoder.decode(("someothertype", "uint96[]", "int8[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160932
assert_type(decoder.decode(("someothertype", "uint96[]", "int96"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160933
assert_type(decoder.decode(("someothertype", "uint96[]", "int96[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160934
assert_type(decoder.decode(("someothertype", "uint96[]", "string"), data), Tuple[Any, Tuple[int, ...], str])  # tuple case 8160935
assert_type(decoder.decode(("someothertype", "uint96[]", "string[]"), data), Tuple[Any, Tuple[int, ...], Tuple[str, ...]])  # tuple case 8160936
assert_type(decoder.decode(("someothertype", "uint96[]", "uint104"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160937
assert_type(decoder.decode(("someothertype", "uint96[]", "uint104[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160938
assert_type(decoder.decode(("someothertype", "uint96[]", "uint112"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160939
assert_type(decoder.decode(("someothertype", "uint96[]", "uint112[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160940
assert_type(decoder.decode(("someothertype", "uint96[]", "uint120"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160941
assert_type(decoder.decode(("someothertype", "uint96[]", "uint120[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160942
assert_type(decoder.decode(("someothertype", "uint96[]", "uint128"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160943
assert_type(decoder.decode(("someothertype", "uint96[]", "uint128[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160944
assert_type(decoder.decode(("someothertype", "uint96[]", "uint136"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160945
assert_type(decoder.decode(("someothertype", "uint96[]", "uint136[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160946
assert_type(decoder.decode(("someothertype", "uint96[]", "uint144"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160947
assert_type(decoder.decode(("someothertype", "uint96[]", "uint144[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160948
assert_type(decoder.decode(("someothertype", "uint96[]", "uint152"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160949
assert_type(decoder.decode(("someothertype", "uint96[]", "uint152[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160950
assert_type(decoder.decode(("someothertype", "uint96[]", "uint16"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160951
assert_type(decoder.decode(("someothertype", "uint96[]", "uint160"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160952
assert_type(decoder.decode(("someothertype", "uint96[]", "uint160[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160953
assert_type(decoder.decode(("someothertype", "uint96[]", "uint168"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160954
assert_type(decoder.decode(("someothertype", "uint96[]", "uint168[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160955
assert_type(decoder.decode(("someothertype", "uint96[]", "uint16[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160956
assert_type(decoder.decode(("someothertype", "uint96[]", "uint176"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160957
assert_type(decoder.decode(("someothertype", "uint96[]", "uint176[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160958
assert_type(decoder.decode(("someothertype", "uint96[]", "uint184"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160959
assert_type(decoder.decode(("someothertype", "uint96[]", "uint184[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160960
assert_type(decoder.decode(("someothertype", "uint96[]", "uint192"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160961
assert_type(decoder.decode(("someothertype", "uint96[]", "uint192[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160962
assert_type(decoder.decode(("someothertype", "uint96[]", "uint200"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160963
assert_type(decoder.decode(("someothertype", "uint96[]", "uint200[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160964
assert_type(decoder.decode(("someothertype", "uint96[]", "uint208"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160965
assert_type(decoder.decode(("someothertype", "uint96[]", "uint208[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160966
assert_type(decoder.decode(("someothertype", "uint96[]", "uint216"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160967
assert_type(decoder.decode(("someothertype", "uint96[]", "uint216[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160968
assert_type(decoder.decode(("someothertype", "uint96[]", "uint224"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160969
assert_type(decoder.decode(("someothertype", "uint96[]", "uint224[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160970
assert_type(decoder.decode(("someothertype", "uint96[]", "uint232"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160971
assert_type(decoder.decode(("someothertype", "uint96[]", "uint232[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160972
assert_type(decoder.decode(("someothertype", "uint96[]", "uint24"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160973
assert_type(decoder.decode(("someothertype", "uint96[]", "uint240"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160974
assert_type(decoder.decode(("someothertype", "uint96[]", "uint240[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160975
assert_type(decoder.decode(("someothertype", "uint96[]", "uint248"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160976
assert_type(decoder.decode(("someothertype", "uint96[]", "uint248[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160977
assert_type(decoder.decode(("someothertype", "uint96[]", "uint24[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160978
assert_type(decoder.decode(("someothertype", "uint96[]", "uint256"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160979
assert_type(decoder.decode(("someothertype", "uint96[]", "uint256[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160980
assert_type(decoder.decode(("someothertype", "uint96[]", "uint32"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160981
assert_type(decoder.decode(("someothertype", "uint96[]", "uint32[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160982
assert_type(decoder.decode(("someothertype", "uint96[]", "uint40"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160983
assert_type(decoder.decode(("someothertype", "uint96[]", "uint40[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160984
assert_type(decoder.decode(("someothertype", "uint96[]", "uint48"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160985
assert_type(decoder.decode(("someothertype", "uint96[]", "uint48[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160986
assert_type(decoder.decode(("someothertype", "uint96[]", "uint56"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160987
assert_type(decoder.decode(("someothertype", "uint96[]", "uint56[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160988
assert_type(decoder.decode(("someothertype", "uint96[]", "uint64"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160989
assert_type(decoder.decode(("someothertype", "uint96[]", "uint64[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160990
assert_type(decoder.decode(("someothertype", "uint96[]", "uint72"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160991
assert_type(decoder.decode(("someothertype", "uint96[]", "uint72[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160992
assert_type(decoder.decode(("someothertype", "uint96[]", "uint8"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160993
assert_type(decoder.decode(("someothertype", "uint96[]", "uint80"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160994
assert_type(decoder.decode(("someothertype", "uint96[]", "uint80[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160995
assert_type(decoder.decode(("someothertype", "uint96[]", "uint88"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160996
assert_type(decoder.decode(("someothertype", "uint96[]", "uint88[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160997
assert_type(decoder.decode(("someothertype", "uint96[]", "uint8[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8160998
assert_type(decoder.decode(("someothertype", "uint96[]", "uint96"), data), Tuple[Any, Tuple[int, ...], int])  # tuple case 8160999
assert_type(decoder.decode(("someothertype", "uint96[]", "uint96[]"), data), Tuple[Any, Tuple[int, ...], Tuple[int, ...]])  # tuple case 8161000
assert_type(decoder.decode(("someothertype", "uint96[]", "someothertype"), data), Tuple[Any, Tuple[int, ...], Any])  # tuple case 8161001
assert_type(decoder.decode(("someothertype", "someothertype", "address"), data), Tuple[Any, Any, HexAddress])  # tuple case 8161002
assert_type(decoder.decode(("someothertype", "someothertype", "address[]"), data), Tuple[Any, Any, Tuple[HexAddress, ...]])  # tuple case 8161003
assert_type(decoder.decode(("someothertype", "someothertype", "bool"), data), Tuple[Any, Any, bool])  # tuple case 8161004
assert_type(decoder.decode(("someothertype", "someothertype", "bool[]"), data), Tuple[Any, Any, Tuple[bool, ...]])  # tuple case 8161005
assert_type(decoder.decode(("someothertype", "someothertype", "bytes"), data), Tuple[Any, Any, bytes])  # tuple case 8161006
assert_type(decoder.decode(("someothertype", "someothertype", "bytes1"), data), Tuple[Any, Any, bytes])  # tuple case 8161007
assert_type(decoder.decode(("someothertype", "someothertype", "bytes10"), data), Tuple[Any, Any, bytes])  # tuple case 8161008
assert_type(decoder.decode(("someothertype", "someothertype", "bytes10[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161009
assert_type(decoder.decode(("someothertype", "someothertype", "bytes11"), data), Tuple[Any, Any, bytes])  # tuple case 8161010
assert_type(decoder.decode(("someothertype", "someothertype", "bytes11[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161011
assert_type(decoder.decode(("someothertype", "someothertype", "bytes12"), data), Tuple[Any, Any, bytes])  # tuple case 8161012
assert_type(decoder.decode(("someothertype", "someothertype", "bytes12[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161013
assert_type(decoder.decode(("someothertype", "someothertype", "bytes13"), data), Tuple[Any, Any, bytes])  # tuple case 8161014
assert_type(decoder.decode(("someothertype", "someothertype", "bytes13[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161015
assert_type(decoder.decode(("someothertype", "someothertype", "bytes14"), data), Tuple[Any, Any, bytes])  # tuple case 8161016
assert_type(decoder.decode(("someothertype", "someothertype", "bytes14[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161017
assert_type(decoder.decode(("someothertype", "someothertype", "bytes15"), data), Tuple[Any, Any, bytes])  # tuple case 8161018
assert_type(decoder.decode(("someothertype", "someothertype", "bytes15[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161019
assert_type(decoder.decode(("someothertype", "someothertype", "bytes16"), data), Tuple[Any, Any, bytes])  # tuple case 8161020
assert_type(decoder.decode(("someothertype", "someothertype", "bytes16[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161021
assert_type(decoder.decode(("someothertype", "someothertype", "bytes17"), data), Tuple[Any, Any, bytes])  # tuple case 8161022
assert_type(decoder.decode(("someothertype", "someothertype", "bytes17[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161023
assert_type(decoder.decode(("someothertype", "someothertype", "bytes18"), data), Tuple[Any, Any, bytes])  # tuple case 8161024
assert_type(decoder.decode(("someothertype", "someothertype", "bytes18[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161025
assert_type(decoder.decode(("someothertype", "someothertype", "bytes19"), data), Tuple[Any, Any, bytes])  # tuple case 8161026
assert_type(decoder.decode(("someothertype", "someothertype", "bytes19[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161027
assert_type(decoder.decode(("someothertype", "someothertype", "bytes1[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161028
assert_type(decoder.decode(("someothertype", "someothertype", "bytes2"), data), Tuple[Any, Any, bytes])  # tuple case 8161029
assert_type(decoder.decode(("someothertype", "someothertype", "bytes20"), data), Tuple[Any, Any, bytes])  # tuple case 8161030
assert_type(decoder.decode(("someothertype", "someothertype", "bytes20[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161031
assert_type(decoder.decode(("someothertype", "someothertype", "bytes21"), data), Tuple[Any, Any, bytes])  # tuple case 8161032
assert_type(decoder.decode(("someothertype", "someothertype", "bytes21[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161033
assert_type(decoder.decode(("someothertype", "someothertype", "bytes22"), data), Tuple[Any, Any, bytes])  # tuple case 8161034
assert_type(decoder.decode(("someothertype", "someothertype", "bytes22[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161035
assert_type(decoder.decode(("someothertype", "someothertype", "bytes23"), data), Tuple[Any, Any, bytes])  # tuple case 8161036
assert_type(decoder.decode(("someothertype", "someothertype", "bytes23[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161037
assert_type(decoder.decode(("someothertype", "someothertype", "bytes24"), data), Tuple[Any, Any, bytes])  # tuple case 8161038
assert_type(decoder.decode(("someothertype", "someothertype", "bytes24[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161039
assert_type(decoder.decode(("someothertype", "someothertype", "bytes25"), data), Tuple[Any, Any, bytes])  # tuple case 8161040
assert_type(decoder.decode(("someothertype", "someothertype", "bytes25[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161041
assert_type(decoder.decode(("someothertype", "someothertype", "bytes26"), data), Tuple[Any, Any, bytes])  # tuple case 8161042
assert_type(decoder.decode(("someothertype", "someothertype", "bytes26[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161043
assert_type(decoder.decode(("someothertype", "someothertype", "bytes27"), data), Tuple[Any, Any, bytes])  # tuple case 8161044
assert_type(decoder.decode(("someothertype", "someothertype", "bytes27[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161045
assert_type(decoder.decode(("someothertype", "someothertype", "bytes28"), data), Tuple[Any, Any, bytes])  # tuple case 8161046
assert_type(decoder.decode(("someothertype", "someothertype", "bytes28[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161047
assert_type(decoder.decode(("someothertype", "someothertype", "bytes29"), data), Tuple[Any, Any, bytes])  # tuple case 8161048
assert_type(decoder.decode(("someothertype", "someothertype", "bytes29[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161049
assert_type(decoder.decode(("someothertype", "someothertype", "bytes2[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161050
assert_type(decoder.decode(("someothertype", "someothertype", "bytes3"), data), Tuple[Any, Any, bytes])  # tuple case 8161051
assert_type(decoder.decode(("someothertype", "someothertype", "bytes30"), data), Tuple[Any, Any, bytes])  # tuple case 8161052
assert_type(decoder.decode(("someothertype", "someothertype", "bytes30[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161053
assert_type(decoder.decode(("someothertype", "someothertype", "bytes31"), data), Tuple[Any, Any, bytes])  # tuple case 8161054
assert_type(decoder.decode(("someothertype", "someothertype", "bytes31[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161055
assert_type(decoder.decode(("someothertype", "someothertype", "bytes32"), data), Tuple[Any, Any, bytes])  # tuple case 8161056
assert_type(decoder.decode(("someothertype", "someothertype", "bytes32[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161057
assert_type(decoder.decode(("someothertype", "someothertype", "bytes3[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161058
assert_type(decoder.decode(("someothertype", "someothertype", "bytes4"), data), Tuple[Any, Any, bytes])  # tuple case 8161059
assert_type(decoder.decode(("someothertype", "someothertype", "bytes4[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161060
assert_type(decoder.decode(("someothertype", "someothertype", "bytes5"), data), Tuple[Any, Any, bytes])  # tuple case 8161061
assert_type(decoder.decode(("someothertype", "someothertype", "bytes5[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161062
assert_type(decoder.decode(("someothertype", "someothertype", "bytes6"), data), Tuple[Any, Any, bytes])  # tuple case 8161063
assert_type(decoder.decode(("someothertype", "someothertype", "bytes6[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161064
assert_type(decoder.decode(("someothertype", "someothertype", "bytes7"), data), Tuple[Any, Any, bytes])  # tuple case 8161065
assert_type(decoder.decode(("someothertype", "someothertype", "bytes7[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161066
assert_type(decoder.decode(("someothertype", "someothertype", "bytes8"), data), Tuple[Any, Any, bytes])  # tuple case 8161067
assert_type(decoder.decode(("someothertype", "someothertype", "bytes8[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161068
assert_type(decoder.decode(("someothertype", "someothertype", "bytes9"), data), Tuple[Any, Any, bytes])  # tuple case 8161069
assert_type(decoder.decode(("someothertype", "someothertype", "bytes9[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161070
assert_type(decoder.decode(("someothertype", "someothertype", "bytes[]"), data), Tuple[Any, Any, Tuple[bytes, ...]])  # tuple case 8161071
assert_type(decoder.decode(("someothertype", "someothertype", "int104"), data), Tuple[Any, Any, int])  # tuple case 8161072
assert_type(decoder.decode(("someothertype", "someothertype", "int104[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161073
assert_type(decoder.decode(("someothertype", "someothertype", "int112"), data), Tuple[Any, Any, int])  # tuple case 8161074
assert_type(decoder.decode(("someothertype", "someothertype", "int112[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161075
assert_type(decoder.decode(("someothertype", "someothertype", "int120"), data), Tuple[Any, Any, int])  # tuple case 8161076
assert_type(decoder.decode(("someothertype", "someothertype", "int120[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161077
assert_type(decoder.decode(("someothertype", "someothertype", "int128"), data), Tuple[Any, Any, int])  # tuple case 8161078
assert_type(decoder.decode(("someothertype", "someothertype", "int128[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161079
assert_type(decoder.decode(("someothertype", "someothertype", "int136"), data), Tuple[Any, Any, int])  # tuple case 8161080
assert_type(decoder.decode(("someothertype", "someothertype", "int136[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161081
assert_type(decoder.decode(("someothertype", "someothertype", "int144"), data), Tuple[Any, Any, int])  # tuple case 8161082
assert_type(decoder.decode(("someothertype", "someothertype", "int144[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161083
assert_type(decoder.decode(("someothertype", "someothertype", "int152"), data), Tuple[Any, Any, int])  # tuple case 8161084
assert_type(decoder.decode(("someothertype", "someothertype", "int152[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161085
assert_type(decoder.decode(("someothertype", "someothertype", "int16"), data), Tuple[Any, Any, int])  # tuple case 8161086
assert_type(decoder.decode(("someothertype", "someothertype", "int160"), data), Tuple[Any, Any, int])  # tuple case 8161087
assert_type(decoder.decode(("someothertype", "someothertype", "int160[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161088
assert_type(decoder.decode(("someothertype", "someothertype", "int168"), data), Tuple[Any, Any, int])  # tuple case 8161089
assert_type(decoder.decode(("someothertype", "someothertype", "int168[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161090
assert_type(decoder.decode(("someothertype", "someothertype", "int16[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161091
assert_type(decoder.decode(("someothertype", "someothertype", "int176"), data), Tuple[Any, Any, int])  # tuple case 8161092
assert_type(decoder.decode(("someothertype", "someothertype", "int176[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161093
assert_type(decoder.decode(("someothertype", "someothertype", "int184"), data), Tuple[Any, Any, int])  # tuple case 8161094
assert_type(decoder.decode(("someothertype", "someothertype", "int184[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161095
assert_type(decoder.decode(("someothertype", "someothertype", "int192"), data), Tuple[Any, Any, int])  # tuple case 8161096
assert_type(decoder.decode(("someothertype", "someothertype", "int192[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161097
assert_type(decoder.decode(("someothertype", "someothertype", "int200"), data), Tuple[Any, Any, int])  # tuple case 8161098
assert_type(decoder.decode(("someothertype", "someothertype", "int200[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161099
assert_type(decoder.decode(("someothertype", "someothertype", "int208"), data), Tuple[Any, Any, int])  # tuple case 8161100
assert_type(decoder.decode(("someothertype", "someothertype", "int208[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161101
assert_type(decoder.decode(("someothertype", "someothertype", "int216"), data), Tuple[Any, Any, int])  # tuple case 8161102
assert_type(decoder.decode(("someothertype", "someothertype", "int216[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161103
assert_type(decoder.decode(("someothertype", "someothertype", "int224"), data), Tuple[Any, Any, int])  # tuple case 8161104
assert_type(decoder.decode(("someothertype", "someothertype", "int224[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161105
assert_type(decoder.decode(("someothertype", "someothertype", "int232"), data), Tuple[Any, Any, int])  # tuple case 8161106
assert_type(decoder.decode(("someothertype", "someothertype", "int232[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161107
assert_type(decoder.decode(("someothertype", "someothertype", "int24"), data), Tuple[Any, Any, int])  # tuple case 8161108
assert_type(decoder.decode(("someothertype", "someothertype", "int240"), data), Tuple[Any, Any, int])  # tuple case 8161109
assert_type(decoder.decode(("someothertype", "someothertype", "int240[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161110
assert_type(decoder.decode(("someothertype", "someothertype", "int248"), data), Tuple[Any, Any, int])  # tuple case 8161111
assert_type(decoder.decode(("someothertype", "someothertype", "int248[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161112
assert_type(decoder.decode(("someothertype", "someothertype", "int24[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161113
assert_type(decoder.decode(("someothertype", "someothertype", "int256"), data), Tuple[Any, Any, int])  # tuple case 8161114
assert_type(decoder.decode(("someothertype", "someothertype", "int256[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161115
assert_type(decoder.decode(("someothertype", "someothertype", "int32"), data), Tuple[Any, Any, int])  # tuple case 8161116
assert_type(decoder.decode(("someothertype", "someothertype", "int32[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161117
assert_type(decoder.decode(("someothertype", "someothertype", "int40"), data), Tuple[Any, Any, int])  # tuple case 8161118
assert_type(decoder.decode(("someothertype", "someothertype", "int40[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161119
assert_type(decoder.decode(("someothertype", "someothertype", "int48"), data), Tuple[Any, Any, int])  # tuple case 8161120
assert_type(decoder.decode(("someothertype", "someothertype", "int48[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161121
assert_type(decoder.decode(("someothertype", "someothertype", "int56"), data), Tuple[Any, Any, int])  # tuple case 8161122
assert_type(decoder.decode(("someothertype", "someothertype", "int56[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161123
assert_type(decoder.decode(("someothertype", "someothertype", "int64"), data), Tuple[Any, Any, int])  # tuple case 8161124
assert_type(decoder.decode(("someothertype", "someothertype", "int64[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161125
assert_type(decoder.decode(("someothertype", "someothertype", "int72"), data), Tuple[Any, Any, int])  # tuple case 8161126
assert_type(decoder.decode(("someothertype", "someothertype", "int72[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161127
assert_type(decoder.decode(("someothertype", "someothertype", "int8"), data), Tuple[Any, Any, int])  # tuple case 8161128
assert_type(decoder.decode(("someothertype", "someothertype", "int80"), data), Tuple[Any, Any, int])  # tuple case 8161129
assert_type(decoder.decode(("someothertype", "someothertype", "int80[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161130
assert_type(decoder.decode(("someothertype", "someothertype", "int88"), data), Tuple[Any, Any, int])  # tuple case 8161131
assert_type(decoder.decode(("someothertype", "someothertype", "int88[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161132
assert_type(decoder.decode(("someothertype", "someothertype", "int8[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161133
assert_type(decoder.decode(("someothertype", "someothertype", "int96"), data), Tuple[Any, Any, int])  # tuple case 8161134
assert_type(decoder.decode(("someothertype", "someothertype", "int96[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161135
assert_type(decoder.decode(("someothertype", "someothertype", "string"), data), Tuple[Any, Any, str])  # tuple case 8161136
assert_type(decoder.decode(("someothertype", "someothertype", "string[]"), data), Tuple[Any, Any, Tuple[str, ...]])  # tuple case 8161137
assert_type(decoder.decode(("someothertype", "someothertype", "uint104"), data), Tuple[Any, Any, int])  # tuple case 8161138
assert_type(decoder.decode(("someothertype", "someothertype", "uint104[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161139
assert_type(decoder.decode(("someothertype", "someothertype", "uint112"), data), Tuple[Any, Any, int])  # tuple case 8161140
assert_type(decoder.decode(("someothertype", "someothertype", "uint112[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161141
assert_type(decoder.decode(("someothertype", "someothertype", "uint120"), data), Tuple[Any, Any, int])  # tuple case 8161142
assert_type(decoder.decode(("someothertype", "someothertype", "uint120[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161143
assert_type(decoder.decode(("someothertype", "someothertype", "uint128"), data), Tuple[Any, Any, int])  # tuple case 8161144
assert_type(decoder.decode(("someothertype", "someothertype", "uint128[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161145
assert_type(decoder.decode(("someothertype", "someothertype", "uint136"), data), Tuple[Any, Any, int])  # tuple case 8161146
assert_type(decoder.decode(("someothertype", "someothertype", "uint136[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161147
assert_type(decoder.decode(("someothertype", "someothertype", "uint144"), data), Tuple[Any, Any, int])  # tuple case 8161148
assert_type(decoder.decode(("someothertype", "someothertype", "uint144[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161149
assert_type(decoder.decode(("someothertype", "someothertype", "uint152"), data), Tuple[Any, Any, int])  # tuple case 8161150
assert_type(decoder.decode(("someothertype", "someothertype", "uint152[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161151
assert_type(decoder.decode(("someothertype", "someothertype", "uint16"), data), Tuple[Any, Any, int])  # tuple case 8161152
assert_type(decoder.decode(("someothertype", "someothertype", "uint160"), data), Tuple[Any, Any, int])  # tuple case 8161153
assert_type(decoder.decode(("someothertype", "someothertype", "uint160[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161154
assert_type(decoder.decode(("someothertype", "someothertype", "uint168"), data), Tuple[Any, Any, int])  # tuple case 8161155
assert_type(decoder.decode(("someothertype", "someothertype", "uint168[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161156
assert_type(decoder.decode(("someothertype", "someothertype", "uint16[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161157
assert_type(decoder.decode(("someothertype", "someothertype", "uint176"), data), Tuple[Any, Any, int])  # tuple case 8161158
assert_type(decoder.decode(("someothertype", "someothertype", "uint176[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161159
assert_type(decoder.decode(("someothertype", "someothertype", "uint184"), data), Tuple[Any, Any, int])  # tuple case 8161160
assert_type(decoder.decode(("someothertype", "someothertype", "uint184[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161161
assert_type(decoder.decode(("someothertype", "someothertype", "uint192"), data), Tuple[Any, Any, int])  # tuple case 8161162
assert_type(decoder.decode(("someothertype", "someothertype", "uint192[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161163
assert_type(decoder.decode(("someothertype", "someothertype", "uint200"), data), Tuple[Any, Any, int])  # tuple case 8161164
assert_type(decoder.decode(("someothertype", "someothertype", "uint200[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161165
assert_type(decoder.decode(("someothertype", "someothertype", "uint208"), data), Tuple[Any, Any, int])  # tuple case 8161166
assert_type(decoder.decode(("someothertype", "someothertype", "uint208[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161167
assert_type(decoder.decode(("someothertype", "someothertype", "uint216"), data), Tuple[Any, Any, int])  # tuple case 8161168
assert_type(decoder.decode(("someothertype", "someothertype", "uint216[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161169
assert_type(decoder.decode(("someothertype", "someothertype", "uint224"), data), Tuple[Any, Any, int])  # tuple case 8161170
assert_type(decoder.decode(("someothertype", "someothertype", "uint224[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161171
assert_type(decoder.decode(("someothertype", "someothertype", "uint232"), data), Tuple[Any, Any, int])  # tuple case 8161172
assert_type(decoder.decode(("someothertype", "someothertype", "uint232[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161173
assert_type(decoder.decode(("someothertype", "someothertype", "uint24"), data), Tuple[Any, Any, int])  # tuple case 8161174
assert_type(decoder.decode(("someothertype", "someothertype", "uint240"), data), Tuple[Any, Any, int])  # tuple case 8161175
assert_type(decoder.decode(("someothertype", "someothertype", "uint240[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161176
assert_type(decoder.decode(("someothertype", "someothertype", "uint248"), data), Tuple[Any, Any, int])  # tuple case 8161177
assert_type(decoder.decode(("someothertype", "someothertype", "uint248[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161178
assert_type(decoder.decode(("someothertype", "someothertype", "uint24[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161179
assert_type(decoder.decode(("someothertype", "someothertype", "uint256"), data), Tuple[Any, Any, int])  # tuple case 8161180
assert_type(decoder.decode(("someothertype", "someothertype", "uint256[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161181
assert_type(decoder.decode(("someothertype", "someothertype", "uint32"), data), Tuple[Any, Any, int])  # tuple case 8161182
assert_type(decoder.decode(("someothertype", "someothertype", "uint32[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161183
assert_type(decoder.decode(("someothertype", "someothertype", "uint40"), data), Tuple[Any, Any, int])  # tuple case 8161184
assert_type(decoder.decode(("someothertype", "someothertype", "uint40[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161185
assert_type(decoder.decode(("someothertype", "someothertype", "uint48"), data), Tuple[Any, Any, int])  # tuple case 8161186
assert_type(decoder.decode(("someothertype", "someothertype", "uint48[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161187
assert_type(decoder.decode(("someothertype", "someothertype", "uint56"), data), Tuple[Any, Any, int])  # tuple case 8161188
assert_type(decoder.decode(("someothertype", "someothertype", "uint56[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161189
assert_type(decoder.decode(("someothertype", "someothertype", "uint64"), data), Tuple[Any, Any, int])  # tuple case 8161190
assert_type(decoder.decode(("someothertype", "someothertype", "uint64[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161191
assert_type(decoder.decode(("someothertype", "someothertype", "uint72"), data), Tuple[Any, Any, int])  # tuple case 8161192
assert_type(decoder.decode(("someothertype", "someothertype", "uint72[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161193
assert_type(decoder.decode(("someothertype", "someothertype", "uint8"), data), Tuple[Any, Any, int])  # tuple case 8161194
assert_type(decoder.decode(("someothertype", "someothertype", "uint80"), data), Tuple[Any, Any, int])  # tuple case 8161195
assert_type(decoder.decode(("someothertype", "someothertype", "uint80[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161196
assert_type(decoder.decode(("someothertype", "someothertype", "uint88"), data), Tuple[Any, Any, int])  # tuple case 8161197
assert_type(decoder.decode(("someothertype", "someothertype", "uint88[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161198
assert_type(decoder.decode(("someothertype", "someothertype", "uint8[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161199
assert_type(decoder.decode(("someothertype", "someothertype", "uint96"), data), Tuple[Any, Any, int])  # tuple case 8161200
assert_type(decoder.decode(("someothertype", "someothertype", "uint96[]"), data), Tuple[Any, Any, Tuple[int, ...]])  # tuple case 8161201
assert_type(decoder.decode(("someothertype", "someothertype", "someothertype"), data), Tuple[Any, Any, Any])  # tuple case 8161202
