# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(decoder.decode(("unknown_type", "unknown_type", "bool"), data), Tuple[Any, Any, bool])  # tuple case 1010000
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes"), data), Tuple[Any, Any, bytes])  # tuple case 1010001
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes1"), data), Tuple[Any, Any, bytes])  # tuple case 1010002
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes10"), data), Tuple[Any, Any, bytes])  # tuple case 1010003
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes11"), data), Tuple[Any, Any, bytes])  # tuple case 1010004
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes12"), data), Tuple[Any, Any, bytes])  # tuple case 1010005
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes13"), data), Tuple[Any, Any, bytes])  # tuple case 1010006
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes14"), data), Tuple[Any, Any, bytes])  # tuple case 1010007
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes15"), data), Tuple[Any, Any, bytes])  # tuple case 1010008
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes16"), data), Tuple[Any, Any, bytes])  # tuple case 1010009
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes17"), data), Tuple[Any, Any, bytes])  # tuple case 1010010
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes18"), data), Tuple[Any, Any, bytes])  # tuple case 1010011
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes19"), data), Tuple[Any, Any, bytes])  # tuple case 1010012
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes2"), data), Tuple[Any, Any, bytes])  # tuple case 1010013
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes20"), data), Tuple[Any, Any, bytes])  # tuple case 1010014
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes21"), data), Tuple[Any, Any, bytes])  # tuple case 1010015
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes22"), data), Tuple[Any, Any, bytes])  # tuple case 1010016
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes23"), data), Tuple[Any, Any, bytes])  # tuple case 1010017
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes24"), data), Tuple[Any, Any, bytes])  # tuple case 1010018
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes25"), data), Tuple[Any, Any, bytes])  # tuple case 1010019
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes26"), data), Tuple[Any, Any, bytes])  # tuple case 1010020
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes27"), data), Tuple[Any, Any, bytes])  # tuple case 1010021
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes28"), data), Tuple[Any, Any, bytes])  # tuple case 1010022
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes29"), data), Tuple[Any, Any, bytes])  # tuple case 1010023
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes3"), data), Tuple[Any, Any, bytes])  # tuple case 1010024
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes30"), data), Tuple[Any, Any, bytes])  # tuple case 1010025
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes31"), data), Tuple[Any, Any, bytes])  # tuple case 1010026
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes32"), data), Tuple[Any, Any, bytes])  # tuple case 1010027
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes4"), data), Tuple[Any, Any, bytes])  # tuple case 1010028
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes5"), data), Tuple[Any, Any, bytes])  # tuple case 1010029
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes6"), data), Tuple[Any, Any, bytes])  # tuple case 1010030
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes7"), data), Tuple[Any, Any, bytes])  # tuple case 1010031
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes8"), data), Tuple[Any, Any, bytes])  # tuple case 1010032
assert_type(decoder.decode(("unknown_type", "unknown_type", "bytes9"), data), Tuple[Any, Any, bytes])  # tuple case 1010033
assert_type(decoder.decode(("unknown_type", "unknown_type", "int104"), data), Tuple[Any, Any, int])  # tuple case 1010034
assert_type(decoder.decode(("unknown_type", "unknown_type", "int112"), data), Tuple[Any, Any, int])  # tuple case 1010035
assert_type(decoder.decode(("unknown_type", "unknown_type", "int120"), data), Tuple[Any, Any, int])  # tuple case 1010036
assert_type(decoder.decode(("unknown_type", "unknown_type", "int128"), data), Tuple[Any, Any, int])  # tuple case 1010037
assert_type(decoder.decode(("unknown_type", "unknown_type", "int136"), data), Tuple[Any, Any, int])  # tuple case 1010038
assert_type(decoder.decode(("unknown_type", "unknown_type", "int144"), data), Tuple[Any, Any, int])  # tuple case 1010039
assert_type(decoder.decode(("unknown_type", "unknown_type", "int152"), data), Tuple[Any, Any, int])  # tuple case 1010040
assert_type(decoder.decode(("unknown_type", "unknown_type", "int16"), data), Tuple[Any, Any, int])  # tuple case 1010041
assert_type(decoder.decode(("unknown_type", "unknown_type", "int160"), data), Tuple[Any, Any, int])  # tuple case 1010042
assert_type(decoder.decode(("unknown_type", "unknown_type", "int168"), data), Tuple[Any, Any, int])  # tuple case 1010043
assert_type(decoder.decode(("unknown_type", "unknown_type", "int176"), data), Tuple[Any, Any, int])  # tuple case 1010044
assert_type(decoder.decode(("unknown_type", "unknown_type", "int184"), data), Tuple[Any, Any, int])  # tuple case 1010045
assert_type(decoder.decode(("unknown_type", "unknown_type", "int192"), data), Tuple[Any, Any, int])  # tuple case 1010046
assert_type(decoder.decode(("unknown_type", "unknown_type", "int200"), data), Tuple[Any, Any, int])  # tuple case 1010047
assert_type(decoder.decode(("unknown_type", "unknown_type", "int208"), data), Tuple[Any, Any, int])  # tuple case 1010048
assert_type(decoder.decode(("unknown_type", "unknown_type", "int216"), data), Tuple[Any, Any, int])  # tuple case 1010049
assert_type(decoder.decode(("unknown_type", "unknown_type", "int224"), data), Tuple[Any, Any, int])  # tuple case 1010050
assert_type(decoder.decode(("unknown_type", "unknown_type", "int232"), data), Tuple[Any, Any, int])  # tuple case 1010051
assert_type(decoder.decode(("unknown_type", "unknown_type", "int24"), data), Tuple[Any, Any, int])  # tuple case 1010052
assert_type(decoder.decode(("unknown_type", "unknown_type", "int240"), data), Tuple[Any, Any, int])  # tuple case 1010053
assert_type(decoder.decode(("unknown_type", "unknown_type", "int248"), data), Tuple[Any, Any, int])  # tuple case 1010054
assert_type(decoder.decode(("unknown_type", "unknown_type", "int256"), data), Tuple[Any, Any, int])  # tuple case 1010055
assert_type(decoder.decode(("unknown_type", "unknown_type", "int32"), data), Tuple[Any, Any, int])  # tuple case 1010056
assert_type(decoder.decode(("unknown_type", "unknown_type", "int40"), data), Tuple[Any, Any, int])  # tuple case 1010057
assert_type(decoder.decode(("unknown_type", "unknown_type", "int48"), data), Tuple[Any, Any, int])  # tuple case 1010058
assert_type(decoder.decode(("unknown_type", "unknown_type", "int56"), data), Tuple[Any, Any, int])  # tuple case 1010059
assert_type(decoder.decode(("unknown_type", "unknown_type", "int64"), data), Tuple[Any, Any, int])  # tuple case 1010060
assert_type(decoder.decode(("unknown_type", "unknown_type", "int72"), data), Tuple[Any, Any, int])  # tuple case 1010061
assert_type(decoder.decode(("unknown_type", "unknown_type", "int8"), data), Tuple[Any, Any, int])  # tuple case 1010062
assert_type(decoder.decode(("unknown_type", "unknown_type", "int80"), data), Tuple[Any, Any, int])  # tuple case 1010063
assert_type(decoder.decode(("unknown_type", "unknown_type", "int88"), data), Tuple[Any, Any, int])  # tuple case 1010064
assert_type(decoder.decode(("unknown_type", "unknown_type", "int96"), data), Tuple[Any, Any, int])  # tuple case 1010065
assert_type(decoder.decode(("unknown_type", "unknown_type", "string"), data), Tuple[Any, Any, str])  # tuple case 1010066
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint104"), data), Tuple[Any, Any, int])  # tuple case 1010067
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint112"), data), Tuple[Any, Any, int])  # tuple case 1010068
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint120"), data), Tuple[Any, Any, int])  # tuple case 1010069
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint128"), data), Tuple[Any, Any, int])  # tuple case 1010070
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint136"), data), Tuple[Any, Any, int])  # tuple case 1010071
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint144"), data), Tuple[Any, Any, int])  # tuple case 1010072
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint152"), data), Tuple[Any, Any, int])  # tuple case 1010073
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint16"), data), Tuple[Any, Any, int])  # tuple case 1010074
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint160"), data), Tuple[Any, Any, int])  # tuple case 1010075
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint168"), data), Tuple[Any, Any, int])  # tuple case 1010076
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint176"), data), Tuple[Any, Any, int])  # tuple case 1010077
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint184"), data), Tuple[Any, Any, int])  # tuple case 1010078
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint192"), data), Tuple[Any, Any, int])  # tuple case 1010079
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint200"), data), Tuple[Any, Any, int])  # tuple case 1010080
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint208"), data), Tuple[Any, Any, int])  # tuple case 1010081
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint216"), data), Tuple[Any, Any, int])  # tuple case 1010082
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint224"), data), Tuple[Any, Any, int])  # tuple case 1010083
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint232"), data), Tuple[Any, Any, int])  # tuple case 1010084
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint24"), data), Tuple[Any, Any, int])  # tuple case 1010085
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint240"), data), Tuple[Any, Any, int])  # tuple case 1010086
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint248"), data), Tuple[Any, Any, int])  # tuple case 1010087
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint256"), data), Tuple[Any, Any, int])  # tuple case 1010088
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint32"), data), Tuple[Any, Any, int])  # tuple case 1010089
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint40"), data), Tuple[Any, Any, int])  # tuple case 1010090
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint48"), data), Tuple[Any, Any, int])  # tuple case 1010091
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint56"), data), Tuple[Any, Any, int])  # tuple case 1010092
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint64"), data), Tuple[Any, Any, int])  # tuple case 1010093
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint72"), data), Tuple[Any, Any, int])  # tuple case 1010094
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint8"), data), Tuple[Any, Any, int])  # tuple case 1010095
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint80"), data), Tuple[Any, Any, int])  # tuple case 1010096
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint88"), data), Tuple[Any, Any, int])  # tuple case 1010097
assert_type(decoder.decode(("unknown_type", "unknown_type", "uint96"), data), Tuple[Any, Any, int])  # tuple case 1010098
assert_type(decoder.decode(("unknown_type", "unknown_type", "unknown_type"), data), Tuple[Any, Any, Any])  # tuple case 1010099
