# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(decoder.decode(["(address,int128)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 0
assert_type(decoder.decode(["(address,int16)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 1
assert_type(decoder.decode(["(address,int256)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 2
assert_type(decoder.decode(["(address,int64)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 3
assert_type(decoder.decode(["(address,int8)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 4
assert_type(decoder.decode(["(address,uint128)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 5
assert_type(decoder.decode(["(address,uint16)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 6
assert_type(decoder.decode(["(address,uint256)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 7
assert_type(decoder.decode(["(address,uint64)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 8
assert_type(decoder.decode(["(address,uint8)"], data), Tuple[Tuple[HexAddress, int], ...])  # iterable case 9
assert_type(decoder.decode(["(bool,int128)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 10
assert_type(decoder.decode(["(bool,int16)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 11
assert_type(decoder.decode(["(bool,int256)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 12
assert_type(decoder.decode(["(bool,int64)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 13
assert_type(decoder.decode(["(bool,int8)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 14
assert_type(decoder.decode(["(bool,uint128)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 15
assert_type(decoder.decode(["(bool,uint16)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 16
assert_type(decoder.decode(["(bool,uint256)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 17
assert_type(decoder.decode(["(bool,uint64)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 18
assert_type(decoder.decode(["(bool,uint8)"], data), Tuple[Tuple[bool, int], ...])  # iterable case 19
assert_type(decoder.decode(["(bytes,int128)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 20
assert_type(decoder.decode(["(bytes,int16)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 21
assert_type(decoder.decode(["(bytes,int256)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 22
assert_type(decoder.decode(["(bytes,int64)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 23
assert_type(decoder.decode(["(bytes,int8)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 24
assert_type(decoder.decode(["(bytes,uint128)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 25
assert_type(decoder.decode(["(bytes,uint16)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 26
assert_type(decoder.decode(["(bytes,uint256)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 27
assert_type(decoder.decode(["(bytes,uint64)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 28
assert_type(decoder.decode(["(bytes,uint8)"], data), Tuple[Tuple[bytes, int], ...])  # iterable case 29
assert_type(decoder.decode(["(int128,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 30
assert_type(decoder.decode(["(int128,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 31
assert_type(decoder.decode(["(int128,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 32
assert_type(decoder.decode(["(int128,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 33
assert_type(decoder.decode(["(int128,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 34
assert_type(decoder.decode(["(int128,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 35
assert_type(decoder.decode(["(int128,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 36
assert_type(decoder.decode(["(int128,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 37
assert_type(decoder.decode(["(int128,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 38
assert_type(decoder.decode(["(int128,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 39
assert_type(decoder.decode(["(int16,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 40
assert_type(decoder.decode(["(int16,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 41
assert_type(decoder.decode(["(int16,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 42
assert_type(decoder.decode(["(int16,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 43
assert_type(decoder.decode(["(int16,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 44
assert_type(decoder.decode(["(int16,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 45
assert_type(decoder.decode(["(int16,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 46
assert_type(decoder.decode(["(int16,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 47
assert_type(decoder.decode(["(int16,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 48
assert_type(decoder.decode(["(int16,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 49
assert_type(decoder.decode(["(int256,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 50
assert_type(decoder.decode(["(int256,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 51
assert_type(decoder.decode(["(int256,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 52
assert_type(decoder.decode(["(int256,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 53
assert_type(decoder.decode(["(int256,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 54
assert_type(decoder.decode(["(int256,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 55
assert_type(decoder.decode(["(int256,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 56
assert_type(decoder.decode(["(int256,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 57
assert_type(decoder.decode(["(int256,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 58
assert_type(decoder.decode(["(int256,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 59
assert_type(decoder.decode(["(int64,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 60
assert_type(decoder.decode(["(int64,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 61
assert_type(decoder.decode(["(int64,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 62
assert_type(decoder.decode(["(int64,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 63
assert_type(decoder.decode(["(int64,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 64
assert_type(decoder.decode(["(int64,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 65
assert_type(decoder.decode(["(int64,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 66
assert_type(decoder.decode(["(int64,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 67
assert_type(decoder.decode(["(int64,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 68
assert_type(decoder.decode(["(int64,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 69
assert_type(decoder.decode(["(int8,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 70
assert_type(decoder.decode(["(int8,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 71
assert_type(decoder.decode(["(int8,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 72
assert_type(decoder.decode(["(int8,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 73
assert_type(decoder.decode(["(int8,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 74
assert_type(decoder.decode(["(int8,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 75
assert_type(decoder.decode(["(int8,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 76
assert_type(decoder.decode(["(int8,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 77
assert_type(decoder.decode(["(int8,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 78
assert_type(decoder.decode(["(int8,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 79
assert_type(decoder.decode(["(string,int128)"], data), Tuple[Tuple[str, int], ...])  # iterable case 80
assert_type(decoder.decode(["(string,int16)"], data), Tuple[Tuple[str, int], ...])  # iterable case 81
assert_type(decoder.decode(["(string,int256)"], data), Tuple[Tuple[str, int], ...])  # iterable case 82
assert_type(decoder.decode(["(string,int64)"], data), Tuple[Tuple[str, int], ...])  # iterable case 83
assert_type(decoder.decode(["(string,int8)"], data), Tuple[Tuple[str, int], ...])  # iterable case 84
assert_type(decoder.decode(["(string,uint128)"], data), Tuple[Tuple[str, int], ...])  # iterable case 85
assert_type(decoder.decode(["(string,uint16)"], data), Tuple[Tuple[str, int], ...])  # iterable case 86
assert_type(decoder.decode(["(string,uint256)"], data), Tuple[Tuple[str, int], ...])  # iterable case 87
assert_type(decoder.decode(["(string,uint64)"], data), Tuple[Tuple[str, int], ...])  # iterable case 88
assert_type(decoder.decode(["(string,uint8)"], data), Tuple[Tuple[str, int], ...])  # iterable case 89
assert_type(decoder.decode(["(uint128,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 90
assert_type(decoder.decode(["(uint128,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 91
assert_type(decoder.decode(["(uint128,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 92
assert_type(decoder.decode(["(uint128,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 93
assert_type(decoder.decode(["(uint128,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 94
assert_type(decoder.decode(["(uint128,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 95
assert_type(decoder.decode(["(uint128,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 96
assert_type(decoder.decode(["(uint128,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 97
assert_type(decoder.decode(["(uint128,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 98
assert_type(decoder.decode(["(uint128,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 99
assert_type(decoder.decode(["(uint16,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 100
assert_type(decoder.decode(["(uint16,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 101
assert_type(decoder.decode(["(uint16,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 102
assert_type(decoder.decode(["(uint16,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 103
assert_type(decoder.decode(["(uint16,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 104
assert_type(decoder.decode(["(uint16,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 105
assert_type(decoder.decode(["(uint16,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 106
assert_type(decoder.decode(["(uint16,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 107
assert_type(decoder.decode(["(uint16,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 108
assert_type(decoder.decode(["(uint16,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 109
assert_type(decoder.decode(["(uint256,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 110
assert_type(decoder.decode(["(uint256,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 111
assert_type(decoder.decode(["(uint256,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 112
assert_type(decoder.decode(["(uint256,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 113
assert_type(decoder.decode(["(uint256,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 114
assert_type(decoder.decode(["(uint256,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 115
assert_type(decoder.decode(["(uint256,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 116
assert_type(decoder.decode(["(uint256,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 117
assert_type(decoder.decode(["(uint256,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 118
assert_type(decoder.decode(["(uint256,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 119
assert_type(decoder.decode(["(uint64,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 120
assert_type(decoder.decode(["(uint64,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 121
assert_type(decoder.decode(["(uint64,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 122
assert_type(decoder.decode(["(uint64,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 123
assert_type(decoder.decode(["(uint64,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 124
assert_type(decoder.decode(["(uint64,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 125
assert_type(decoder.decode(["(uint64,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 126
assert_type(decoder.decode(["(uint64,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 127
assert_type(decoder.decode(["(uint64,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 128
assert_type(decoder.decode(["(uint64,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 129
assert_type(decoder.decode(["(uint8,int128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 130
assert_type(decoder.decode(["(uint8,int16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 131
assert_type(decoder.decode(["(uint8,int256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 132
assert_type(decoder.decode(["(uint8,int64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 133
assert_type(decoder.decode(["(uint8,int8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 134
assert_type(decoder.decode(["(uint8,uint128)"], data), Tuple[Tuple[int, int], ...])  # iterable case 135
assert_type(decoder.decode(["(uint8,uint16)"], data), Tuple[Tuple[int, int], ...])  # iterable case 136
assert_type(decoder.decode(["(uint8,uint256)"], data), Tuple[Tuple[int, int], ...])  # iterable case 137
assert_type(decoder.decode(["(uint8,uint64)"], data), Tuple[Tuple[int, int], ...])  # iterable case 138
assert_type(decoder.decode(["(uint8,uint8)"], data), Tuple[Tuple[int, int], ...])  # iterable case 139
assert_type(decoder.decode(["address"], data), Tuple[HexAddress, ...])  # iterable case 140
assert_type(decoder.decode(["address[]"], data), Tuple[Tuple[HexAddress, ...], ...])  # iterable case 141
assert_type(decoder.decode(["bool"], data), Tuple[bool, ...])  # iterable case 142
assert_type(decoder.decode(["bool[]"], data), Tuple[Tuple[bool, ...], ...])  # iterable case 143
assert_type(decoder.decode(["bytes"], data), Tuple[bytes, ...])  # iterable case 144
assert_type(decoder.decode(["bytes1"], data), Tuple[bytes, ...])  # iterable case 145
assert_type(decoder.decode(["bytes10"], data), Tuple[bytes, ...])  # iterable case 146
assert_type(decoder.decode(["bytes10[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 147
assert_type(decoder.decode(["bytes11"], data), Tuple[bytes, ...])  # iterable case 148
assert_type(decoder.decode(["bytes11[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 149
assert_type(decoder.decode(["bytes12"], data), Tuple[bytes, ...])  # iterable case 150
assert_type(decoder.decode(["bytes12[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 151
assert_type(decoder.decode(["bytes13"], data), Tuple[bytes, ...])  # iterable case 152
assert_type(decoder.decode(["bytes13[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 153
assert_type(decoder.decode(["bytes14"], data), Tuple[bytes, ...])  # iterable case 154
assert_type(decoder.decode(["bytes14[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 155
assert_type(decoder.decode(["bytes15"], data), Tuple[bytes, ...])  # iterable case 156
assert_type(decoder.decode(["bytes15[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 157
assert_type(decoder.decode(["bytes16"], data), Tuple[bytes, ...])  # iterable case 158
assert_type(decoder.decode(["bytes16[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 159
assert_type(decoder.decode(["bytes17"], data), Tuple[bytes, ...])  # iterable case 160
assert_type(decoder.decode(["bytes17[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 161
assert_type(decoder.decode(["bytes18"], data), Tuple[bytes, ...])  # iterable case 162
assert_type(decoder.decode(["bytes18[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 163
assert_type(decoder.decode(["bytes19"], data), Tuple[bytes, ...])  # iterable case 164
assert_type(decoder.decode(["bytes19[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 165
assert_type(decoder.decode(["bytes1[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 166
assert_type(decoder.decode(["bytes2"], data), Tuple[bytes, ...])  # iterable case 167
assert_type(decoder.decode(["bytes20"], data), Tuple[bytes, ...])  # iterable case 168
assert_type(decoder.decode(["bytes20[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 169
assert_type(decoder.decode(["bytes21"], data), Tuple[bytes, ...])  # iterable case 170
assert_type(decoder.decode(["bytes21[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 171
assert_type(decoder.decode(["bytes22"], data), Tuple[bytes, ...])  # iterable case 172
assert_type(decoder.decode(["bytes22[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 173
assert_type(decoder.decode(["bytes23"], data), Tuple[bytes, ...])  # iterable case 174
assert_type(decoder.decode(["bytes23[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 175
assert_type(decoder.decode(["bytes24"], data), Tuple[bytes, ...])  # iterable case 176
assert_type(decoder.decode(["bytes24[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 177
assert_type(decoder.decode(["bytes25"], data), Tuple[bytes, ...])  # iterable case 178
assert_type(decoder.decode(["bytes25[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 179
assert_type(decoder.decode(["bytes26"], data), Tuple[bytes, ...])  # iterable case 180
assert_type(decoder.decode(["bytes26[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 181
assert_type(decoder.decode(["bytes27"], data), Tuple[bytes, ...])  # iterable case 182
assert_type(decoder.decode(["bytes27[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 183
assert_type(decoder.decode(["bytes28"], data), Tuple[bytes, ...])  # iterable case 184
assert_type(decoder.decode(["bytes28[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 185
assert_type(decoder.decode(["bytes29"], data), Tuple[bytes, ...])  # iterable case 186
assert_type(decoder.decode(["bytes29[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 187
assert_type(decoder.decode(["bytes2[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 188
assert_type(decoder.decode(["bytes3"], data), Tuple[bytes, ...])  # iterable case 189
assert_type(decoder.decode(["bytes30"], data), Tuple[bytes, ...])  # iterable case 190
assert_type(decoder.decode(["bytes30[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 191
assert_type(decoder.decode(["bytes31"], data), Tuple[bytes, ...])  # iterable case 192
assert_type(decoder.decode(["bytes31[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 193
assert_type(decoder.decode(["bytes32"], data), Tuple[bytes, ...])  # iterable case 194
assert_type(decoder.decode(["bytes32[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 195
assert_type(decoder.decode(["bytes3[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 196
assert_type(decoder.decode(["bytes4"], data), Tuple[bytes, ...])  # iterable case 197
assert_type(decoder.decode(["bytes4[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 198
assert_type(decoder.decode(["bytes5"], data), Tuple[bytes, ...])  # iterable case 199
assert_type(decoder.decode(["bytes5[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 200
assert_type(decoder.decode(["bytes6"], data), Tuple[bytes, ...])  # iterable case 201
assert_type(decoder.decode(["bytes6[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 202
assert_type(decoder.decode(["bytes7"], data), Tuple[bytes, ...])  # iterable case 203
assert_type(decoder.decode(["bytes7[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 204
assert_type(decoder.decode(["bytes8"], data), Tuple[bytes, ...])  # iterable case 205
assert_type(decoder.decode(["bytes8[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 206
assert_type(decoder.decode(["bytes9"], data), Tuple[bytes, ...])  # iterable case 207
assert_type(decoder.decode(["bytes9[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 208
assert_type(decoder.decode(["bytes[]"], data), Tuple[Tuple[bytes, ...], ...])  # iterable case 209
assert_type(decoder.decode(["int104"], data), Tuple[int, ...])  # iterable case 210
assert_type(decoder.decode(["int104[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 211
assert_type(decoder.decode(["int112"], data), Tuple[int, ...])  # iterable case 212
assert_type(decoder.decode(["int112[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 213
assert_type(decoder.decode(["int120"], data), Tuple[int, ...])  # iterable case 214
assert_type(decoder.decode(["int120[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 215
assert_type(decoder.decode(["int128"], data), Tuple[int, ...])  # iterable case 216
assert_type(decoder.decode(["int128[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 217
assert_type(decoder.decode(["int136"], data), Tuple[int, ...])  # iterable case 218
assert_type(decoder.decode(["int136[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 219
assert_type(decoder.decode(["int144"], data), Tuple[int, ...])  # iterable case 220
assert_type(decoder.decode(["int144[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 221
assert_type(decoder.decode(["int152"], data), Tuple[int, ...])  # iterable case 222
assert_type(decoder.decode(["int152[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 223
assert_type(decoder.decode(["int16"], data), Tuple[int, ...])  # iterable case 224
assert_type(decoder.decode(["int160"], data), Tuple[int, ...])  # iterable case 225
assert_type(decoder.decode(["int160[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 226
assert_type(decoder.decode(["int168"], data), Tuple[int, ...])  # iterable case 227
assert_type(decoder.decode(["int168[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 228
assert_type(decoder.decode(["int16[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 229
assert_type(decoder.decode(["int176"], data), Tuple[int, ...])  # iterable case 230
assert_type(decoder.decode(["int176[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 231
assert_type(decoder.decode(["int184"], data), Tuple[int, ...])  # iterable case 232
assert_type(decoder.decode(["int184[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 233
assert_type(decoder.decode(["int192"], data), Tuple[int, ...])  # iterable case 234
assert_type(decoder.decode(["int192[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 235
assert_type(decoder.decode(["int200"], data), Tuple[int, ...])  # iterable case 236
assert_type(decoder.decode(["int200[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 237
assert_type(decoder.decode(["int208"], data), Tuple[int, ...])  # iterable case 238
assert_type(decoder.decode(["int208[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 239
assert_type(decoder.decode(["int216"], data), Tuple[int, ...])  # iterable case 240
assert_type(decoder.decode(["int216[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 241
assert_type(decoder.decode(["int224"], data), Tuple[int, ...])  # iterable case 242
assert_type(decoder.decode(["int224[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 243
assert_type(decoder.decode(["int232"], data), Tuple[int, ...])  # iterable case 244
assert_type(decoder.decode(["int232[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 245
assert_type(decoder.decode(["int24"], data), Tuple[int, ...])  # iterable case 246
assert_type(decoder.decode(["int240"], data), Tuple[int, ...])  # iterable case 247
assert_type(decoder.decode(["int240[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 248
assert_type(decoder.decode(["int248"], data), Tuple[int, ...])  # iterable case 249
assert_type(decoder.decode(["int248[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 250
assert_type(decoder.decode(["int24[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 251
assert_type(decoder.decode(["int256"], data), Tuple[int, ...])  # iterable case 252
assert_type(decoder.decode(["int256[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 253
assert_type(decoder.decode(["int32"], data), Tuple[int, ...])  # iterable case 254
assert_type(decoder.decode(["int32[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 255
assert_type(decoder.decode(["int40"], data), Tuple[int, ...])  # iterable case 256
assert_type(decoder.decode(["int40[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 257
assert_type(decoder.decode(["int48"], data), Tuple[int, ...])  # iterable case 258
assert_type(decoder.decode(["int48[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 259
assert_type(decoder.decode(["int56"], data), Tuple[int, ...])  # iterable case 260
assert_type(decoder.decode(["int56[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 261
assert_type(decoder.decode(["int64"], data), Tuple[int, ...])  # iterable case 262
assert_type(decoder.decode(["int64[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 263
assert_type(decoder.decode(["int72"], data), Tuple[int, ...])  # iterable case 264
assert_type(decoder.decode(["int72[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 265
assert_type(decoder.decode(["int8"], data), Tuple[int, ...])  # iterable case 266
assert_type(decoder.decode(["int80"], data), Tuple[int, ...])  # iterable case 267
assert_type(decoder.decode(["int80[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 268
assert_type(decoder.decode(["int88"], data), Tuple[int, ...])  # iterable case 269
assert_type(decoder.decode(["int88[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 270
assert_type(decoder.decode(["int8[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 271
assert_type(decoder.decode(["int96"], data), Tuple[int, ...])  # iterable case 272
assert_type(decoder.decode(["int96[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 273
assert_type(decoder.decode(["string"], data), Tuple[str, ...])  # iterable case 274
assert_type(decoder.decode(["string[]"], data), Tuple[Tuple[str, ...], ...])  # iterable case 275
assert_type(decoder.decode(["uint104"], data), Tuple[int, ...])  # iterable case 276
assert_type(decoder.decode(["uint104[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 277
assert_type(decoder.decode(["uint112"], data), Tuple[int, ...])  # iterable case 278
assert_type(decoder.decode(["uint112[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 279
assert_type(decoder.decode(["uint120"], data), Tuple[int, ...])  # iterable case 280
assert_type(decoder.decode(["uint120[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 281
assert_type(decoder.decode(["uint128"], data), Tuple[int, ...])  # iterable case 282
assert_type(decoder.decode(["uint128[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 283
assert_type(decoder.decode(["uint136"], data), Tuple[int, ...])  # iterable case 284
assert_type(decoder.decode(["uint136[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 285
assert_type(decoder.decode(["uint144"], data), Tuple[int, ...])  # iterable case 286
assert_type(decoder.decode(["uint144[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 287
assert_type(decoder.decode(["uint152"], data), Tuple[int, ...])  # iterable case 288
assert_type(decoder.decode(["uint152[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 289
assert_type(decoder.decode(["uint16"], data), Tuple[int, ...])  # iterable case 290
assert_type(decoder.decode(["uint160"], data), Tuple[int, ...])  # iterable case 291
assert_type(decoder.decode(["uint160[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 292
assert_type(decoder.decode(["uint168"], data), Tuple[int, ...])  # iterable case 293
assert_type(decoder.decode(["uint168[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 294
assert_type(decoder.decode(["uint16[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 295
assert_type(decoder.decode(["uint176"], data), Tuple[int, ...])  # iterable case 296
assert_type(decoder.decode(["uint176[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 297
assert_type(decoder.decode(["uint184"], data), Tuple[int, ...])  # iterable case 298
assert_type(decoder.decode(["uint184[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 299
assert_type(decoder.decode(["uint192"], data), Tuple[int, ...])  # iterable case 300
assert_type(decoder.decode(["uint192[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 301
assert_type(decoder.decode(["uint200"], data), Tuple[int, ...])  # iterable case 302
assert_type(decoder.decode(["uint200[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 303
assert_type(decoder.decode(["uint208"], data), Tuple[int, ...])  # iterable case 304
assert_type(decoder.decode(["uint208[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 305
assert_type(decoder.decode(["uint216"], data), Tuple[int, ...])  # iterable case 306
assert_type(decoder.decode(["uint216[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 307
assert_type(decoder.decode(["uint224"], data), Tuple[int, ...])  # iterable case 308
assert_type(decoder.decode(["uint224[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 309
assert_type(decoder.decode(["uint232"], data), Tuple[int, ...])  # iterable case 310
assert_type(decoder.decode(["uint232[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 311
assert_type(decoder.decode(["uint24"], data), Tuple[int, ...])  # iterable case 312
assert_type(decoder.decode(["uint240"], data), Tuple[int, ...])  # iterable case 313
assert_type(decoder.decode(["uint240[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 314
assert_type(decoder.decode(["uint248"], data), Tuple[int, ...])  # iterable case 315
assert_type(decoder.decode(["uint248[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 316
assert_type(decoder.decode(["uint24[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 317
assert_type(decoder.decode(["uint256"], data), Tuple[int, ...])  # iterable case 318
assert_type(decoder.decode(["uint256[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 319
assert_type(decoder.decode(["uint32"], data), Tuple[int, ...])  # iterable case 320
assert_type(decoder.decode(["uint32[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 321
assert_type(decoder.decode(["uint40"], data), Tuple[int, ...])  # iterable case 322
assert_type(decoder.decode(["uint40[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 323
assert_type(decoder.decode(["uint48"], data), Tuple[int, ...])  # iterable case 324
assert_type(decoder.decode(["uint48[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 325
assert_type(decoder.decode(["uint56"], data), Tuple[int, ...])  # iterable case 326
assert_type(decoder.decode(["uint56[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 327
assert_type(decoder.decode(["uint64"], data), Tuple[int, ...])  # iterable case 328
assert_type(decoder.decode(["uint64[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 329
assert_type(decoder.decode(["uint72"], data), Tuple[int, ...])  # iterable case 330
assert_type(decoder.decode(["uint72[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 331
assert_type(decoder.decode(["uint8"], data), Tuple[int, ...])  # iterable case 332
assert_type(decoder.decode(["uint80"], data), Tuple[int, ...])  # iterable case 333
assert_type(decoder.decode(["uint80[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 334
assert_type(decoder.decode(["uint88"], data), Tuple[int, ...])  # iterable case 335
assert_type(decoder.decode(["uint88[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 336
assert_type(decoder.decode(["uint8[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 337
assert_type(decoder.decode(["uint96"], data), Tuple[int, ...])  # iterable case 338
assert_type(decoder.decode(["uint96[]"], data), Tuple[Tuple[int, ...], ...])  # iterable case 339
assert_type(decoder.decode(["someothertype"], data), Tuple[Any, ...])  # iterable case 340
