# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
data = b"\x00" * 32
assert_type(decoder.decode(["address"], data), Tuple[Any, ...])  # iterable case 0
assert_type(decoder.decode(["bool"], data), Tuple[bool, ...])  # iterable case 1
assert_type(decoder.decode(["bytes"], data), Tuple[bytes, ...])  # iterable case 2
assert_type(decoder.decode(["bytes1"], data), Tuple[bytes, ...])  # iterable case 3
assert_type(decoder.decode(["bytes10"], data), Tuple[bytes, ...])  # iterable case 4
assert_type(decoder.decode(["bytes11"], data), Tuple[bytes, ...])  # iterable case 5
assert_type(decoder.decode(["bytes12"], data), Tuple[bytes, ...])  # iterable case 6
assert_type(decoder.decode(["bytes13"], data), Tuple[bytes, ...])  # iterable case 7
assert_type(decoder.decode(["bytes14"], data), Tuple[bytes, ...])  # iterable case 8
assert_type(decoder.decode(["bytes15"], data), Tuple[bytes, ...])  # iterable case 9
assert_type(decoder.decode(["bytes16"], data), Tuple[bytes, ...])  # iterable case 10
assert_type(decoder.decode(["bytes17"], data), Tuple[bytes, ...])  # iterable case 11
assert_type(decoder.decode(["bytes18"], data), Tuple[bytes, ...])  # iterable case 12
assert_type(decoder.decode(["bytes19"], data), Tuple[bytes, ...])  # iterable case 13
assert_type(decoder.decode(["bytes2"], data), Tuple[bytes, ...])  # iterable case 14
assert_type(decoder.decode(["bytes20"], data), Tuple[bytes, ...])  # iterable case 15
assert_type(decoder.decode(["bytes21"], data), Tuple[bytes, ...])  # iterable case 16
assert_type(decoder.decode(["bytes22"], data), Tuple[bytes, ...])  # iterable case 17
assert_type(decoder.decode(["bytes23"], data), Tuple[bytes, ...])  # iterable case 18
assert_type(decoder.decode(["bytes24"], data), Tuple[bytes, ...])  # iterable case 19
assert_type(decoder.decode(["bytes25"], data), Tuple[bytes, ...])  # iterable case 20
assert_type(decoder.decode(["bytes26"], data), Tuple[bytes, ...])  # iterable case 21
assert_type(decoder.decode(["bytes27"], data), Tuple[bytes, ...])  # iterable case 22
assert_type(decoder.decode(["bytes28"], data), Tuple[bytes, ...])  # iterable case 23
assert_type(decoder.decode(["bytes29"], data), Tuple[bytes, ...])  # iterable case 24
assert_type(decoder.decode(["bytes3"], data), Tuple[bytes, ...])  # iterable case 25
assert_type(decoder.decode(["bytes30"], data), Tuple[bytes, ...])  # iterable case 26
assert_type(decoder.decode(["bytes31"], data), Tuple[bytes, ...])  # iterable case 27
assert_type(decoder.decode(["bytes32"], data), Tuple[bytes, ...])  # iterable case 28
assert_type(decoder.decode(["bytes4"], data), Tuple[bytes, ...])  # iterable case 29
assert_type(decoder.decode(["bytes5"], data), Tuple[bytes, ...])  # iterable case 30
assert_type(decoder.decode(["bytes6"], data), Tuple[bytes, ...])  # iterable case 31
assert_type(decoder.decode(["bytes7"], data), Tuple[bytes, ...])  # iterable case 32
assert_type(decoder.decode(["bytes8"], data), Tuple[bytes, ...])  # iterable case 33
assert_type(decoder.decode(["bytes9"], data), Tuple[bytes, ...])  # iterable case 34
assert_type(decoder.decode(["int104"], data), Tuple[int, ...])  # iterable case 35
assert_type(decoder.decode(["int112"], data), Tuple[int, ...])  # iterable case 36
assert_type(decoder.decode(["int120"], data), Tuple[int, ...])  # iterable case 37
assert_type(decoder.decode(["int128"], data), Tuple[int, ...])  # iterable case 38
assert_type(decoder.decode(["int136"], data), Tuple[int, ...])  # iterable case 39
assert_type(decoder.decode(["int144"], data), Tuple[int, ...])  # iterable case 40
assert_type(decoder.decode(["int152"], data), Tuple[int, ...])  # iterable case 41
assert_type(decoder.decode(["int16"], data), Tuple[int, ...])  # iterable case 42
assert_type(decoder.decode(["int160"], data), Tuple[int, ...])  # iterable case 43
assert_type(decoder.decode(["int168"], data), Tuple[int, ...])  # iterable case 44
assert_type(decoder.decode(["int176"], data), Tuple[int, ...])  # iterable case 45
assert_type(decoder.decode(["int184"], data), Tuple[int, ...])  # iterable case 46
assert_type(decoder.decode(["int192"], data), Tuple[int, ...])  # iterable case 47
assert_type(decoder.decode(["int200"], data), Tuple[int, ...])  # iterable case 48
assert_type(decoder.decode(["int208"], data), Tuple[int, ...])  # iterable case 49
assert_type(decoder.decode(["int216"], data), Tuple[int, ...])  # iterable case 50
assert_type(decoder.decode(["int224"], data), Tuple[int, ...])  # iterable case 51
assert_type(decoder.decode(["int232"], data), Tuple[int, ...])  # iterable case 52
assert_type(decoder.decode(["int24"], data), Tuple[int, ...])  # iterable case 53
assert_type(decoder.decode(["int240"], data), Tuple[int, ...])  # iterable case 54
assert_type(decoder.decode(["int248"], data), Tuple[int, ...])  # iterable case 55
assert_type(decoder.decode(["int256"], data), Tuple[int, ...])  # iterable case 56
assert_type(decoder.decode(["int32"], data), Tuple[int, ...])  # iterable case 57
assert_type(decoder.decode(["int40"], data), Tuple[int, ...])  # iterable case 58
assert_type(decoder.decode(["int48"], data), Tuple[int, ...])  # iterable case 59
assert_type(decoder.decode(["int56"], data), Tuple[int, ...])  # iterable case 60
assert_type(decoder.decode(["int64"], data), Tuple[int, ...])  # iterable case 61
assert_type(decoder.decode(["int72"], data), Tuple[int, ...])  # iterable case 62
assert_type(decoder.decode(["int8"], data), Tuple[int, ...])  # iterable case 63
assert_type(decoder.decode(["int80"], data), Tuple[int, ...])  # iterable case 64
assert_type(decoder.decode(["int88"], data), Tuple[int, ...])  # iterable case 65
assert_type(decoder.decode(["int96"], data), Tuple[int, ...])  # iterable case 66
assert_type(decoder.decode(["string"], data), Tuple[str, ...])  # iterable case 67
assert_type(decoder.decode(["uint104"], data), Tuple[int, ...])  # iterable case 68
assert_type(decoder.decode(["uint112"], data), Tuple[int, ...])  # iterable case 69
assert_type(decoder.decode(["uint120"], data), Tuple[int, ...])  # iterable case 70
assert_type(decoder.decode(["uint128"], data), Tuple[int, ...])  # iterable case 71
assert_type(decoder.decode(["uint136"], data), Tuple[int, ...])  # iterable case 72
assert_type(decoder.decode(["uint144"], data), Tuple[int, ...])  # iterable case 73
assert_type(decoder.decode(["uint152"], data), Tuple[int, ...])  # iterable case 74
assert_type(decoder.decode(["uint16"], data), Tuple[int, ...])  # iterable case 75
assert_type(decoder.decode(["uint160"], data), Tuple[int, ...])  # iterable case 76
assert_type(decoder.decode(["uint168"], data), Tuple[int, ...])  # iterable case 77
assert_type(decoder.decode(["uint176"], data), Tuple[int, ...])  # iterable case 78
assert_type(decoder.decode(["uint184"], data), Tuple[int, ...])  # iterable case 79
assert_type(decoder.decode(["uint192"], data), Tuple[int, ...])  # iterable case 80
assert_type(decoder.decode(["uint200"], data), Tuple[int, ...])  # iterable case 81
assert_type(decoder.decode(["uint208"], data), Tuple[int, ...])  # iterable case 82
assert_type(decoder.decode(["uint216"], data), Tuple[int, ...])  # iterable case 83
assert_type(decoder.decode(["uint224"], data), Tuple[int, ...])  # iterable case 84
assert_type(decoder.decode(["uint232"], data), Tuple[int, ...])  # iterable case 85
assert_type(decoder.decode(["uint24"], data), Tuple[int, ...])  # iterable case 86
assert_type(decoder.decode(["uint240"], data), Tuple[int, ...])  # iterable case 87
assert_type(decoder.decode(["uint248"], data), Tuple[int, ...])  # iterable case 88
assert_type(decoder.decode(["uint256"], data), Tuple[int, ...])  # iterable case 89
assert_type(decoder.decode(["uint32"], data), Tuple[int, ...])  # iterable case 90
assert_type(decoder.decode(["uint40"], data), Tuple[int, ...])  # iterable case 91
assert_type(decoder.decode(["uint48"], data), Tuple[int, ...])  # iterable case 92
assert_type(decoder.decode(["uint56"], data), Tuple[int, ...])  # iterable case 93
assert_type(decoder.decode(["uint64"], data), Tuple[int, ...])  # iterable case 94
assert_type(decoder.decode(["uint72"], data), Tuple[int, ...])  # iterable case 95
assert_type(decoder.decode(["uint8"], data), Tuple[int, ...])  # iterable case 96
assert_type(decoder.decode(["uint80"], data), Tuple[int, ...])  # iterable case 97
assert_type(decoder.decode(["uint88"], data), Tuple[int, ...])  # iterable case 98
assert_type(decoder.decode(["uint96"], data), Tuple[int, ...])  # iterable case 99
assert_type(decoder.decode(["someothertype"], data), Tuple[Any, ...])  # iterable case 100
