from typing import Any

class BaseCoder:
    is_dynamic: bool
    def __init__(self, **kwargs: Any) -> None: ...
    def validate(self) -> None: ...
    @classmethod
    def from_type_str(cls, type_str, registry) -> None: ...
