from eth_typing.abi import Decodable as Decodable, TypeStr as TypeStr
from faster_eth_abi._codec import decode_c as decode_c, encode_c as encode_c
from faster_eth_abi.decoding import ContextFramesBytesIO as ContextFramesBytesIO
from faster_eth_abi.exceptions import EncodingError as EncodingError, MultipleEntriesFound as MultipleEntriesFound
from faster_eth_abi.registry import ABIRegistry as ABIRegistry
from faster_eth_abi.typing import BoolTypeStr as BoolTypeStr, BytesTypeStr as BytesTypeStr, IntTypeStr as IntTypeStr, StringTypeStr as StringTypeStr, UintTypeStr as UintTypeStr
from typing import Any, Iterable, overload

DecodesToIntTypeStr = UintTypeStr | IntTypeStr

class BaseABICoder:
    def __init__(self, registry: ABIRegistry) -> None: ...

class ABIEncoder(BaseABICoder):
    def encode(self, types: Iterable[TypeStr], args: Iterable[Any]) -> bytes: ...
    def is_encodable(self, typ: TypeStr, arg: Any) -> bool: ...
    def is_encodable_type(self, typ: TypeStr) -> bool: ...

class ABIDecoder(BaseABICoder):
    stream_class = ContextFramesBytesIO
    @overload
    def decode(self, types: tuple[BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bytes]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, str]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, int]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, Any]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, str]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str, int]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bool]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[str, Any]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bytes]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[int, str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, int]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bool]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[int, Any]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bytes]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, str]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bool]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bool, Any]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bytes]: ...
    @overload
    def decode(self, types: tuple[TypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, str]: ...
    @overload
    def decode(self, types: tuple[TypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, int]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bool]: ...
    @overload
    def decode(self, types: tuple[TypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[Any, Any]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BytesTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bytes, bytes]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BytesTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bytes, str]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BytesTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bytes, int]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BytesTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bytes, bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BytesTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bytes, Any]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, StringTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, str, bytes]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, StringTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, str, str]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, StringTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, str, int]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, StringTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, str, bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, StringTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, str, Any]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, DecodesToIntTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, int, bytes]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, DecodesToIntTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, int, str]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, DecodesToIntTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, int, int]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, DecodesToIntTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, int, bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, DecodesToIntTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, int, Any]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BoolTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bool, bytes]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BoolTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bool, str]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BoolTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bool, int]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BoolTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bool, bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, BoolTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, bool, Any]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, TypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, Any, bytes]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, TypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, Any, str]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, TypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, Any, int]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, TypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, Any, bool]: ...
    @overload
    def decode(self, types: tuple[BytesTypeStr, TypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, Any, Any]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BytesTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bytes, bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BytesTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bytes, str]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BytesTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bytes, int]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BytesTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bytes, bool]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BytesTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[str, bytes, Any]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, StringTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[str, str, bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, StringTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, str, str]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, StringTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str, str, int]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, StringTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str, str, bool]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, StringTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[str, str, Any]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, DecodesToIntTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[str, int, bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, DecodesToIntTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, int, str]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, DecodesToIntTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str, int, int]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, DecodesToIntTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str, int, bool]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, DecodesToIntTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[str, int, Any]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BoolTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bool, bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BoolTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bool, str]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BoolTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bool, int]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BoolTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str, bool, bool]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, BoolTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[str, bool, Any]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, TypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[str, Any, bytes]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, TypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, Any, str]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, TypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str, Any, int]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, TypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str, Any, bool]: ...
    @overload
    def decode(self, types: tuple[StringTypeStr, TypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[str, Any, Any]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BytesTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bytes, bytes]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BytesTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bytes, str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BytesTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bytes, int]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BytesTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bytes, bool]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BytesTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[int, bytes, Any]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, StringTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[int, str, bytes]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, StringTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[int, str, str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, StringTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, str, int]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, StringTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int, str, bool]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, StringTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[int, str, Any]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, DecodesToIntTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[int, int, bytes]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, DecodesToIntTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[int, int, str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, DecodesToIntTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, int, int]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, DecodesToIntTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int, int, bool]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, DecodesToIntTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[int, int, Any]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BoolTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bool, bytes]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BoolTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bool, str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BoolTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bool, int]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BoolTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int, bool, bool]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, BoolTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[int, bool, Any]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, TypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[int, Any, bytes]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, TypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[int, Any, str]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, TypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, Any, int]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, TypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int, Any, bool]: ...
    @overload
    def decode(self, types: tuple[DecodesToIntTypeStr, TypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[int, Any, Any]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BytesTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bytes, bytes]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BytesTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bytes, str]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BytesTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bytes, int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BytesTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bytes, bool]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BytesTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bytes, Any]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, StringTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, str, bytes]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, StringTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, str, str]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, StringTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, str, int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, StringTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, str, bool]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, StringTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bool, str, Any]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, DecodesToIntTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, int, bytes]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, DecodesToIntTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, int, str]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, DecodesToIntTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, int, int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, DecodesToIntTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, int, bool]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, DecodesToIntTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bool, int, Any]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BoolTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bool, bytes]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BoolTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bool, str]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BoolTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bool, int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BoolTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bool, bool]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, BoolTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bool, bool, Any]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, TypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, Any, bytes]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, TypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, Any, str]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, TypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, Any, int]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, TypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, Any, bool]: ...
    @overload
    def decode(self, types: tuple[BoolTypeStr, TypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[bool, Any, Any]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BytesTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bytes, bytes]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BytesTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bytes, str]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BytesTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bytes, int]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BytesTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bytes, bool]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BytesTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bytes, Any]: ...
    @overload
    def decode(self, types: tuple[TypeStr, StringTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, str, bytes]: ...
    @overload
    def decode(self, types: tuple[TypeStr, StringTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, str, str]: ...
    @overload
    def decode(self, types: tuple[TypeStr, StringTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, str, int]: ...
    @overload
    def decode(self, types: tuple[TypeStr, StringTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, str, bool]: ...
    @overload
    def decode(self, types: tuple[TypeStr, StringTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[Any, str, Any]: ...
    @overload
    def decode(self, types: tuple[TypeStr, DecodesToIntTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, int, bytes]: ...
    @overload
    def decode(self, types: tuple[TypeStr, DecodesToIntTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, int, str]: ...
    @overload
    def decode(self, types: tuple[TypeStr, DecodesToIntTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, int, int]: ...
    @overload
    def decode(self, types: tuple[TypeStr, DecodesToIntTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, int, bool]: ...
    @overload
    def decode(self, types: tuple[TypeStr, DecodesToIntTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[Any, int, Any]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BoolTypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bool, bytes]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BoolTypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bool, str]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BoolTypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bool, int]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BoolTypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bool, bool]: ...
    @overload
    def decode(self, types: tuple[TypeStr, BoolTypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[Any, bool, Any]: ...
    @overload
    def decode(self, types: tuple[TypeStr, TypeStr, BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, Any, bytes]: ...
    @overload
    def decode(self, types: tuple[TypeStr, TypeStr, StringTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, Any, str]: ...
    @overload
    def decode(self, types: tuple[TypeStr, TypeStr, DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, Any, int]: ...
    @overload
    def decode(self, types: tuple[TypeStr, TypeStr, BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[Any, Any, bool]: ...
    @overload
    def decode(self, types: tuple[TypeStr, TypeStr, TypeStr], data: Decodable, strict: bool = True) -> tuple[Any, Any, Any]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes, ...]: ...
    @overload
    def decode(self, types: Iterable[StringTypeStr], data: Decodable, strict: bool = True) -> tuple[str, ...]: ...
    @overload
    def decode(self, types: Iterable[DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[int, ...]: ...
    @overload
    def decode(self, types: Iterable[BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bool, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | StringTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | str, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | int, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | bool, ...]: ...
    @overload
    def decode(self, types: Iterable[StringTypeStr | DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[str | int, ...]: ...
    @overload
    def decode(self, types: Iterable[StringTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str | bool, ...]: ...
    @overload
    def decode(self, types: Iterable[DecodesToIntTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[int | bool, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | StringTypeStr | DecodesToIntTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | str | int, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | StringTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | str | bool, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | DecodesToIntTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | int | bool, ...]: ...
    @overload
    def decode(self, types: Iterable[StringTypeStr | DecodesToIntTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[str | int | bool, ...]: ...
    @overload
    def decode(self, types: Iterable[BytesTypeStr | StringTypeStr | DecodesToIntTypeStr | BoolTypeStr], data: Decodable, strict: bool = True) -> tuple[bytes | str | int | bool, ...]: ...

class ABICodec(ABIEncoder, ABIDecoder): ...
