import eth_abi.exceptions

class EncodingError(eth_abi.exceptions.EncodingError): ...
class EncodingTypeError(EncodingError, eth_abi.exceptions.EncodingTypeError): ...
class IllegalValue(EncodingError, eth_abi.exceptions.IllegalValue): ...
class ValueOutOfBounds(IllegalValue, eth_abi.exceptions.ValueOutOfBounds): ...
class DecodingError(eth_abi.exceptions.DecodingError): ...
class InsufficientDataBytes(DecodingError, eth_abi.exceptions.InsufficientDataBytes): ...
class NonEmptyPaddingBytes(DecodingError, eth_abi.exceptions.NonEmptyPaddingBytes): ...
class InvalidPointer(DecodingError, eth_abi.exceptions.InvalidPointer): ...

class ParseError(eth_abi.exceptions.ParseError):
    def __str__(self) -> str: ...

class ABITypeError(eth_abi.exceptions.ABITypeError): ...
class PredicateMappingError(eth_abi.exceptions.PredicateMappingError): ...
class NoEntriesFound(PredicateMappingError, eth_abi.exceptions.NoEntriesFound): ...
class MultipleEntriesFound(PredicateMappingError, eth_abi.exceptions.MultipleEntriesFound): ...
