# AUTOGENERATED: Run scripts/generate_overload_tests.py to update.
# Requires mypy and Python 3.10+ (for typing.assert_type)
# To run: pip install mypy && mypy tests/typecheck

from typing import Any, Tuple, Union
from typing_extensions import assert_type
from eth_typing import HexAddress
from faster_eth_abi.codec import ABIDecoder
from faster_eth_abi.registry import ABIRegistry

decoder = ABIDecoder(ABIRegistry())
DATA = b"\x00" * 32
assert_type(decoder.decode(('address',), DATA), Tuple[Any])  # tuple case 0
assert_type(decoder.decode(('address[]',), DATA), Tuple[Any])  # tuple case 1
assert_type(decoder.decode(('bool',), DATA), Tuple[bool])  # tuple case 2
assert_type(decoder.decode(('bool[]',), DATA), Tuple[Tuple[bool, ...]])  # tuple case 3
assert_type(decoder.decode(('bytes',), DATA), Tuple[bytes])  # tuple case 4
assert_type(decoder.decode(('bytes1',), DATA), Tuple[bytes])  # tuple case 5
assert_type(decoder.decode(('bytes10',), DATA), Tuple[bytes])  # tuple case 6
assert_type(decoder.decode(('bytes11',), DATA), Tuple[bytes])  # tuple case 7
assert_type(decoder.decode(('bytes12',), DATA), Tuple[bytes])  # tuple case 8
assert_type(decoder.decode(('bytes13',), DATA), Tuple[bytes])  # tuple case 9
assert_type(decoder.decode(('bytes14',), DATA), Tuple[bytes])  # tuple case 10
assert_type(decoder.decode(('bytes15',), DATA), Tuple[bytes])  # tuple case 11
assert_type(decoder.decode(('bytes16',), DATA), Tuple[bytes])  # tuple case 12
assert_type(decoder.decode(('bytes17',), DATA), Tuple[bytes])  # tuple case 13
assert_type(decoder.decode(('bytes18',), DATA), Tuple[bytes])  # tuple case 14
assert_type(decoder.decode(('bytes19',), DATA), Tuple[bytes])  # tuple case 15
assert_type(decoder.decode(('bytes2',), DATA), Tuple[bytes])  # tuple case 16
assert_type(decoder.decode(('bytes20',), DATA), Tuple[bytes])  # tuple case 17
assert_type(decoder.decode(('bytes21',), DATA), Tuple[bytes])  # tuple case 18
assert_type(decoder.decode(('bytes22',), DATA), Tuple[bytes])  # tuple case 19
assert_type(decoder.decode(('bytes23',), DATA), Tuple[bytes])  # tuple case 20
assert_type(decoder.decode(('bytes24',), DATA), Tuple[bytes])  # tuple case 21
assert_type(decoder.decode(('bytes25',), DATA), Tuple[bytes])  # tuple case 22
assert_type(decoder.decode(('bytes26',), DATA), Tuple[bytes])  # tuple case 23
assert_type(decoder.decode(('bytes27',), DATA), Tuple[bytes])  # tuple case 24
assert_type(decoder.decode(('bytes28',), DATA), Tuple[bytes])  # tuple case 25
assert_type(decoder.decode(('bytes29',), DATA), Tuple[bytes])  # tuple case 26
assert_type(decoder.decode(('bytes3',), DATA), Tuple[bytes])  # tuple case 27
assert_type(decoder.decode(('bytes30',), DATA), Tuple[bytes])  # tuple case 28
assert_type(decoder.decode(('bytes31',), DATA), Tuple[bytes])  # tuple case 29
assert_type(decoder.decode(('bytes32',), DATA), Tuple[bytes])  # tuple case 30
assert_type(decoder.decode(('bytes4',), DATA), Tuple[bytes])  # tuple case 31
assert_type(decoder.decode(('bytes5',), DATA), Tuple[bytes])  # tuple case 32
assert_type(decoder.decode(('bytes6',), DATA), Tuple[bytes])  # tuple case 33
assert_type(decoder.decode(('bytes7',), DATA), Tuple[bytes])  # tuple case 34
assert_type(decoder.decode(('bytes8',), DATA), Tuple[bytes])  # tuple case 35
assert_type(decoder.decode(('bytes9',), DATA), Tuple[bytes])  # tuple case 36
assert_type(decoder.decode(('int104',), DATA), Tuple[int])  # tuple case 37
assert_type(decoder.decode(('int112',), DATA), Tuple[int])  # tuple case 38
assert_type(decoder.decode(('int120',), DATA), Tuple[int])  # tuple case 39
assert_type(decoder.decode(('int128',), DATA), Tuple[int])  # tuple case 40
assert_type(decoder.decode(('int136',), DATA), Tuple[int])  # tuple case 41
assert_type(decoder.decode(('int144',), DATA), Tuple[int])  # tuple case 42
assert_type(decoder.decode(('int152',), DATA), Tuple[int])  # tuple case 43
assert_type(decoder.decode(('int16',), DATA), Tuple[int])  # tuple case 44
assert_type(decoder.decode(('int160',), DATA), Tuple[int])  # tuple case 45
assert_type(decoder.decode(('int168',), DATA), Tuple[int])  # tuple case 46
assert_type(decoder.decode(('int176',), DATA), Tuple[int])  # tuple case 47
assert_type(decoder.decode(('int184',), DATA), Tuple[int])  # tuple case 48
assert_type(decoder.decode(('int192',), DATA), Tuple[int])  # tuple case 49
assert_type(decoder.decode(('int200',), DATA), Tuple[int])  # tuple case 50
assert_type(decoder.decode(('int208',), DATA), Tuple[int])  # tuple case 51
assert_type(decoder.decode(('int216',), DATA), Tuple[int])  # tuple case 52
assert_type(decoder.decode(('int224',), DATA), Tuple[int])  # tuple case 53
assert_type(decoder.decode(('int232',), DATA), Tuple[int])  # tuple case 54
assert_type(decoder.decode(('int24',), DATA), Tuple[int])  # tuple case 55
assert_type(decoder.decode(('int240',), DATA), Tuple[int])  # tuple case 56
assert_type(decoder.decode(('int248',), DATA), Tuple[int])  # tuple case 57
assert_type(decoder.decode(('int256',), DATA), Tuple[int])  # tuple case 58
assert_type(decoder.decode(('int32',), DATA), Tuple[int])  # tuple case 59
assert_type(decoder.decode(('int40',), DATA), Tuple[int])  # tuple case 60
assert_type(decoder.decode(('int48',), DATA), Tuple[int])  # tuple case 61
assert_type(decoder.decode(('int56',), DATA), Tuple[int])  # tuple case 62
assert_type(decoder.decode(('int64',), DATA), Tuple[int])  # tuple case 63
assert_type(decoder.decode(('int72',), DATA), Tuple[int])  # tuple case 64
assert_type(decoder.decode(('int8',), DATA), Tuple[int])  # tuple case 65
assert_type(decoder.decode(('int80',), DATA), Tuple[int])  # tuple case 66
assert_type(decoder.decode(('int88',), DATA), Tuple[int])  # tuple case 67
assert_type(decoder.decode(('int96',), DATA), Tuple[int])  # tuple case 68
assert_type(decoder.decode(('string',), DATA), Tuple[str])  # tuple case 69
assert_type(decoder.decode(('string[]',), DATA), Tuple[Any])  # tuple case 70
assert_type(decoder.decode(('uint104',), DATA), Tuple[int])  # tuple case 71
assert_type(decoder.decode(('uint112',), DATA), Tuple[int])  # tuple case 72
assert_type(decoder.decode(('uint120',), DATA), Tuple[int])  # tuple case 73
assert_type(decoder.decode(('uint128',), DATA), Tuple[int])  # tuple case 74
assert_type(decoder.decode(('uint136',), DATA), Tuple[int])  # tuple case 75
assert_type(decoder.decode(('uint144',), DATA), Tuple[int])  # tuple case 76
assert_type(decoder.decode(('uint152',), DATA), Tuple[int])  # tuple case 77
assert_type(decoder.decode(('uint16',), DATA), Tuple[int])  # tuple case 78
assert_type(decoder.decode(('uint160',), DATA), Tuple[int])  # tuple case 79
assert_type(decoder.decode(('uint168',), DATA), Tuple[int])  # tuple case 80
assert_type(decoder.decode(('uint176',), DATA), Tuple[int])  # tuple case 81
assert_type(decoder.decode(('uint184',), DATA), Tuple[int])  # tuple case 82
assert_type(decoder.decode(('uint192',), DATA), Tuple[int])  # tuple case 83
assert_type(decoder.decode(('uint200',), DATA), Tuple[int])  # tuple case 84
assert_type(decoder.decode(('uint208',), DATA), Tuple[int])  # tuple case 85
assert_type(decoder.decode(('uint216',), DATA), Tuple[int])  # tuple case 86
assert_type(decoder.decode(('uint224',), DATA), Tuple[int])  # tuple case 87
assert_type(decoder.decode(('uint232',), DATA), Tuple[int])  # tuple case 88
assert_type(decoder.decode(('uint24',), DATA), Tuple[int])  # tuple case 89
assert_type(decoder.decode(('uint240',), DATA), Tuple[int])  # tuple case 90
assert_type(decoder.decode(('uint248',), DATA), Tuple[int])  # tuple case 91
assert_type(decoder.decode(('uint256',), DATA), Tuple[int])  # tuple case 92
assert_type(decoder.decode(('uint32',), DATA), Tuple[int])  # tuple case 93
assert_type(decoder.decode(('uint40',), DATA), Tuple[int])  # tuple case 94
assert_type(decoder.decode(('uint48',), DATA), Tuple[int])  # tuple case 95
assert_type(decoder.decode(('uint56',), DATA), Tuple[int])  # tuple case 96
assert_type(decoder.decode(('uint64',), DATA), Tuple[int])  # tuple case 97
assert_type(decoder.decode(('uint72',), DATA), Tuple[int])  # tuple case 98
assert_type(decoder.decode(('uint8',), DATA), Tuple[int])  # tuple case 99
assert_type(decoder.decode(('uint80',), DATA), Tuple[int])  # tuple case 100
assert_type(decoder.decode(('uint88',), DATA), Tuple[int])  # tuple case 101
assert_type(decoder.decode(('uint96',), DATA), Tuple[int])  # tuple case 102
assert_type(decoder.decode(('someothertype',), DATA), Tuple[Any])  # tuple case 103
